import { DocumentTypesAltEnum } from '../../enums/document-types-alt.enum';
import { ApiDocumentTypesAltEnum } from '../../../swagger/models/api-document-types';

export function adaptApiDocumentTypesAltEnum(source?: DocumentTypesAltEnum | null): ApiDocumentTypesAltEnum {
  switch (source) {
    case DocumentTypesAltEnum.Unknown:
      return ApiDocumentTypesAltEnum.Unknown;
    case DocumentTypesAltEnum.EGRIP:
      return ApiDocumentTypesAltEnum.EGRIP;
    case DocumentTypesAltEnum.EGRYL:
      return ApiDocumentTypesAltEnum.EGRYL;
    case DocumentTypesAltEnum.FoundingDocument:
      return ApiDocumentTypesAltEnum.FoundingDocument;
    case DocumentTypesAltEnum.ConfirmationOfTheHeadOffice:
      return ApiDocumentTypesAltEnum.ConfirmationOfTheHeadOffice;
    case DocumentTypesAltEnum.ApprovalOfMajorTransactions:
      return ApiDocumentTypesAltEnum.ApprovalOfMajorTransactions;
    case DocumentTypesAltEnum.PowerOfAttorneyForAccreditation:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyForAccreditation;
    case DocumentTypesAltEnum.ConfirmationOfPowers:
      return ApiDocumentTypesAltEnum.ConfirmationOfPowers;
    case DocumentTypesAltEnum.DocumentPersonalIdentification:
      return ApiDocumentTypesAltEnum.DocumentPersonalIdentification;
    case DocumentTypesAltEnum.Custom:
      return ApiDocumentTypesAltEnum.Custom;
    case DocumentTypesAltEnum.RussianPassport:
      return ApiDocumentTypesAltEnum.RussianPassport;
    case DocumentTypesAltEnum.IndividualEntrepreneurCertificate:
      return ApiDocumentTypesAltEnum.IndividualEntrepreneurCertificate;
    case DocumentTypesAltEnum.ClientAgreement:
      return ApiDocumentTypesAltEnum.ClientAgreement;
    case DocumentTypesAltEnum.PartnershipAgreement:
      return ApiDocumentTypesAltEnum.PartnershipAgreement;
    case DocumentTypesAltEnum.ActReportOfAcceptanceOfService:
      return ApiDocumentTypesAltEnum.ActReportOfAcceptanceOfService;
    case DocumentTypesAltEnum.CertificateEntityOfTaxRegistration:
      return ApiDocumentTypesAltEnum.CertificateEntityOfTaxRegistration;
    case DocumentTypesAltEnum.LastYearTaxDeclaration:
      return ApiDocumentTypesAltEnum.LastYearTaxDeclaration;
    case DocumentTypesAltEnum.SimplifiedTaxNotification:
      return ApiDocumentTypesAltEnum.SimplifiedTaxNotification;
    case DocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportAGRO:
      return ApiDocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportAGRO;
    case DocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeAGRO:
      return ApiDocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeAGRO;
    case DocumentTypesAltEnum.OGRNIP:
      return ApiDocumentTypesAltEnum.OGRNIP;
    case DocumentTypesAltEnum.CertificateOfTaxRegistration:
      return ApiDocumentTypesAltEnum.CertificateOfTaxRegistration;
    case DocumentTypesAltEnum.OGRN:
      return ApiDocumentTypesAltEnum.OGRN;
    case DocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportCOMP:
      return ApiDocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportCOMP;
    case DocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeCOMP:
      return ApiDocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeCOMP;
    case DocumentTypesAltEnum.PersonalDataProcessingAgreementAGRO:
      return ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementAGRO;
    case DocumentTypesAltEnum.PersonalDataProcessingAgreementCOMP:
      return ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementCOMP;
    case DocumentTypesAltEnum.Other:
      return ApiDocumentTypesAltEnum.Other;
    case DocumentTypesAltEnum.PowerOfAttorneyJPOnOTCAGRO:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyJPOnOTCAGRO;
    case DocumentTypesAltEnum.PowerOfAttorneyJPOnOTCTENDER:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyJPOnOTCTENDER;
    case DocumentTypesAltEnum.PowerOfAttorneyForWorkOnRTSTENDER:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyForWorkOnRTSTENDER;
    case DocumentTypesAltEnum.PersonalDataProcessingAgreementRTSTENDER:
      return ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementRTSTENDER;
    case DocumentTypesAltEnum.UserSignedData:
      return ApiDocumentTypesAltEnum.UserSignedData;
    case DocumentTypesAltEnum.ProcurementRegulations:
      return ApiDocumentTypesAltEnum.ProcurementRegulations;
    case DocumentTypesAltEnum.ProcurementPlan:
      return ApiDocumentTypesAltEnum.ProcurementPlan;
    case DocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForIndividualEntrepreneur:
      return ApiDocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForIndividualEntrepreneur;
    case DocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForPhysicalPerson:
      return ApiDocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForPhysicalPerson;
    case DocumentTypesAltEnum.ApplicationForAccreditationRtsTender:
      return ApiDocumentTypesAltEnum.ApplicationForAccreditationRtsTender;
    case DocumentTypesAltEnum.PowerOfAttorneyJPOnRTSTENDER:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyJPOnRTSTENDER;
    case DocumentTypesAltEnum.PowerOfAttorneyIEOnRTSTENDER:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyIEOnRTSTENDER;
    case DocumentTypesAltEnum.PowerOfAttorneyIEOnOTCTENDER:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyIEOnOTCTENDER;
    case DocumentTypesAltEnum.PowerOfAttorneyPPOnOTCTENDER:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyPPOnOTCTENDER;
    case DocumentTypesAltEnum.PowerOfAttorneyIEOnOTCAGRO:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyIEOnOTCAGRO;
    case DocumentTypesAltEnum.PowerOfAttorneyPPOnOTCAGRO:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyPPOnOTCAGRO;
    case DocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportOTCMarket:
      return ApiDocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportOTCMarket;
    case DocumentTypesAltEnum.ChangeOrganizationFullNameContract:
      return ApiDocumentTypesAltEnum.ChangeOrganizationFullNameContract;
    case DocumentTypesAltEnum.ApplicationToJoinTheCryptoSiteRules:
      return ApiDocumentTypesAltEnum.ApplicationToJoinTheCryptoSiteRules;
    case DocumentTypesAltEnum.ApplicationForCertificateOfManufacture:
      return ApiDocumentTypesAltEnum.ApplicationForCertificateOfManufacture;
    case DocumentTypesAltEnum.ThePowerOfAttorneyForACertificate:
      return ApiDocumentTypesAltEnum.ThePowerOfAttorneyForACertificate;
    case DocumentTypesAltEnum.ApplicationForCertificateRestore:
      return ApiDocumentTypesAltEnum.ApplicationForCertificateRestore;
    case DocumentTypesAltEnum.ApplicationForJoinSublicenseContract:
      return ApiDocumentTypesAltEnum.ApplicationForJoinSublicenseContract;
    case DocumentTypesAltEnum.PowerOfAttorneyForToken:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyForToken;
    case DocumentTypesAltEnum.Snils:
      return ApiDocumentTypesAltEnum.Snils;
    case DocumentTypesAltEnum.PowerOfAttorneyForCertificateOwner:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyForCertificateOwner;
    case DocumentTypesAltEnum.AgreementOfAutomaticImportFromExternalSourcesOTCMarket:
      return ApiDocumentTypesAltEnum.AgreementOfAutomaticImportFromExternalSourcesOTCMarket;
    case DocumentTypesAltEnum.AccountingDocument:
      return ApiDocumentTypesAltEnum.AccountingDocument;
    case DocumentTypesAltEnum.PowerOfAccreditationWithoutAdmin:
      return ApiDocumentTypesAltEnum.PowerOfAccreditationWithoutAdmin;
    case DocumentTypesAltEnum.AgreementForGo:
      return ApiDocumentTypesAltEnum.AgreementForGo;
    case DocumentTypesAltEnum.LicenseContractForSupplier:
      return ApiDocumentTypesAltEnum.LicenseContractForSupplier;
    case DocumentTypesAltEnum.LicenseContractForCustomer:
      return ApiDocumentTypesAltEnum.LicenseContractForCustomer;
    case DocumentTypesAltEnum.SignListForSupplier:
      return ApiDocumentTypesAltEnum.SignListForSupplier;
    case DocumentTypesAltEnum.SignListForCustomer:
      return ApiDocumentTypesAltEnum.SignListForCustomer;
    case DocumentTypesAltEnum.SmpContract:
      return ApiDocumentTypesAltEnum.SmpContract;
    case DocumentTypesAltEnum.ForeignCountryRegistrationDocument:
      return ApiDocumentTypesAltEnum.ForeignCountryRegistrationDocument;
    case DocumentTypesAltEnum.SelfRegulationOrganizationCertificate:
      return ApiDocumentTypesAltEnum.SelfRegulationOrganizationCertificate;
    case DocumentTypesAltEnum.LicenseForCulturalObjectsRepair:
      return ApiDocumentTypesAltEnum.LicenseForCulturalObjectsRepair;
    case DocumentTypesAltEnum.LicenseForCulturalObjectsProjectDocumentationDesign:
      return ApiDocumentTypesAltEnum.LicenseForCulturalObjectsProjectDocumentationDesign;
    case DocumentTypesAltEnum.AtestatForElevatorsInspection:
      return ApiDocumentTypesAltEnum.AtestatForElevatorsInspection;
    case DocumentTypesAltEnum.CertificateForLackOfTaxDebt:
      return ApiDocumentTypesAltEnum.CertificateForLackOfTaxDebt;
    case DocumentTypesAltEnum.CalculationForInsurance:
      return ApiDocumentTypesAltEnum.CalculationForInsurance;
    case DocumentTypesAltEnum.ContractForSimilarWork:
      return ApiDocumentTypesAltEnum.ContractForSimilarWork;
    case DocumentTypesAltEnum.PowerOfPrequalificationParticipant:
      return ApiDocumentTypesAltEnum.PowerOfPrequalificationParticipant;
    case DocumentTypesAltEnum.StaffList:
      return ApiDocumentTypesAltEnum.StaffList;
    case DocumentTypesAltEnum.EmployeesList:
      return ApiDocumentTypesAltEnum.EmployeesList;
    case DocumentTypesAltEnum.EmploymentHistory:
      return ApiDocumentTypesAltEnum.EmploymentHistory;
    case DocumentTypesAltEnum.Diploma:
      return ApiDocumentTypesAltEnum.Diploma;
    case DocumentTypesAltEnum.Certificate:
      return ApiDocumentTypesAltEnum.Certificate;
    case DocumentTypesAltEnum.Atestate:
      return ApiDocumentTypesAltEnum.Atestate;
    case DocumentTypesAltEnum.ActOfAcceptanceOfTheExecutedWorks:
      return ApiDocumentTypesAltEnum.ActOfAcceptanceOfTheExecutedWorks;
    case DocumentTypesAltEnum.DeclarationOfAccessionForSupplier:
      return ApiDocumentTypesAltEnum.DeclarationOfAccessionForSupplier;
    case DocumentTypesAltEnum.DeclarationOfAccessionForCustomer:
      return ApiDocumentTypesAltEnum.DeclarationOfAccessionForCustomer;
    case DocumentTypesAltEnum.AuthorizationPaymentPrintForm:
      return ApiDocumentTypesAltEnum.AuthorizationPaymentPrintForm;
    case DocumentTypesAltEnum.BoostedAccreditationAgreementPrintForm:
      return ApiDocumentTypesAltEnum.BoostedAccreditationAgreementPrintForm;
    case DocumentTypesAltEnum.EruzOriginalEgrip:
      return ApiDocumentTypesAltEnum.EruzOriginalEgrip;
    case DocumentTypesAltEnum.EruzOriginalEgryl:
      return ApiDocumentTypesAltEnum.EruzOriginalEgryl;
    case DocumentTypesAltEnum.PersonalDataDisseminationAgreementRTSTENDER:
      return ApiDocumentTypesAltEnum.PersonalDataDisseminationAgreementRTSTENDER;
    case DocumentTypesAltEnum.Agreement2323:
      return ApiDocumentTypesAltEnum.Agreement2323;
    case DocumentTypesAltEnum.DeclarationOfAccession:
      return ApiDocumentTypesAltEnum.DeclarationOfAccession;
    case DocumentTypesAltEnum.PowerOfAttorneyForAccreditationBelarus:
      return ApiDocumentTypesAltEnum.PowerOfAttorneyForAccreditationBelarus;
    case DocumentTypesAltEnum.PersonalDataProcessingAgreementEAT:
      return ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementEAT;
    case DocumentTypesAltEnum.PersonalDataDisseminationAgreementEAT:
      return ApiDocumentTypesAltEnum.PersonalDataDisseminationAgreementEAT;
    default:
      throw new Error(`Enum value is not defined: DocumentTypesAltEnum=${String(source)}`);
  }
}
