import { DiscussionItemTypeEnum } from '../../enums/discussion-item-type.enum';
import { ApiDiscussionItemTypeEnum } from '../../../swagger/models/api-discussion-item-type-enum';

export function adaptApiDiscussionItemTypeEnum(source?: DiscussionItemTypeEnum | null): ApiDiscussionItemTypeEnum {
  switch (source) {
    case DiscussionItemTypeEnum.Deal:
      return ApiDiscussionItemTypeEnum.Deal;
    case DiscussionItemTypeEnum.Text:
      return ApiDiscussionItemTypeEnum.Text;
    case DiscussionItemTypeEnum.Contract:
      return ApiDiscussionItemTypeEnum.Contract;
    case DiscussionItemTypeEnum.TextWithFiles:
      return ApiDiscussionItemTypeEnum.TextWithFiles;
    case DiscussionItemTypeEnum.DealSystemSuccessMessage:
      return ApiDiscussionItemTypeEnum.DealSystemSuccessMessage;
    case DiscussionItemTypeEnum.ContractSystemSuccessMessage:
      return ApiDiscussionItemTypeEnum.ContractSystemSuccessMessage;
    case DiscussionItemTypeEnum.Application:
      return ApiDiscussionItemTypeEnum.Application;
    case DiscussionItemTypeEnum.EdsDealSignedBySender:
      return ApiDiscussionItemTypeEnum.EdsDealSignedBySender;
    case DiscussionItemTypeEnum.EdsDealSignedByRecipient:
      return ApiDiscussionItemTypeEnum.EdsDealSignedByRecipient;
    case DiscussionItemTypeEnum.ApplicationApproveMessage:
      return ApiDiscussionItemTypeEnum.ApplicationApproveMessage;
    case DiscussionItemTypeEnum.ApplicationRevoke:
      return ApiDiscussionItemTypeEnum.ApplicationRevoke;
    case DiscussionItemTypeEnum.ApplicationRetradingUpdateMessage:
      return ApiDiscussionItemTypeEnum.ApplicationRetradingUpdateMessage;
    case DiscussionItemTypeEnum.RejectDealByCustomer:
      return ApiDiscussionItemTypeEnum.RejectDealByCustomer;
    case DiscussionItemTypeEnum.CustomerDealCommentSystemMessage:
      return ApiDiscussionItemTypeEnum.CustomerDealCommentSystemMessage;
    case DiscussionItemTypeEnum.DealUpdatePrice:
      return ApiDiscussionItemTypeEnum.DealUpdatePrice;
    case DiscussionItemTypeEnum.MmoCreateDealSystemMessage:
      return ApiDiscussionItemTypeEnum.MmoCreateDealSystemMessage;
    case DiscussionItemTypeEnum.MmoParticipantMissedSigningTime:
      return ApiDiscussionItemTypeEnum.MmoParticipantMissedSigningTime;
    case DiscussionItemTypeEnum.MmoTradeFromDealSigningToDealNotSignedState:
      return ApiDiscussionItemTypeEnum.MmoTradeFromDealSigningToDealNotSignedState;
    case DiscussionItemTypeEnum.MmoTradeFromDealNotSignedToFillingApplicationsState:
      return ApiDiscussionItemTypeEnum.MmoTradeFromDealNotSignedToFillingApplicationsState;
    case DiscussionItemTypeEnum.DealSigningExpiredSystemMessage:
      return ApiDiscussionItemTypeEnum.DealSigningExpiredSystemMessage;
    case DiscussionItemTypeEnum.MmoDealOrAppExpiredSystemMessage:
      return ApiDiscussionItemTypeEnum.MmoDealOrAppExpiredSystemMessage;
    case DiscussionItemTypeEnum.ParticipantSuggestedToSignPaperDealSystemMessage:
      return ApiDiscussionItemTypeEnum.ParticipantSuggestedToSignPaperDealSystemMessage;
    case DiscussionItemTypeEnum.CustomerRefusedSigningPaperDealSystemMessage:
      return ApiDiscussionItemTypeEnum.CustomerRefusedSigningPaperDealSystemMessage;
    case DiscussionItemTypeEnum.CustomerAcceptedSigningPaperDealSystemMessage:
      return ApiDiscussionItemTypeEnum.CustomerAcceptedSigningPaperDealSystemMessage;
    case DiscussionItemTypeEnum.ParticipantSentDifferenceProtocolMessage:
      return ApiDiscussionItemTypeEnum.ParticipantSentDifferenceProtocolMessage;
    case DiscussionItemTypeEnum.CustomerSentContactInformationWithOrderProposing:
      return ApiDiscussionItemTypeEnum.CustomerSentContactInformationWithOrderProposing;
    case DiscussionItemTypeEnum.AdditionalAgreementSentMessage:
      return ApiDiscussionItemTypeEnum.AdditionalAgreementSentMessage;
    case DiscussionItemTypeEnum.AdditionalAgreementSignedMessage:
      return ApiDiscussionItemTypeEnum.AdditionalAgreementSignedMessage;
    case DiscussionItemTypeEnum.AdditionalAgreementRejectedMessage:
      return ApiDiscussionItemTypeEnum.AdditionalAgreementRejectedMessage;
    case DiscussionItemTypeEnum.ApplicationWithDeclaration:
      return ApiDiscussionItemTypeEnum.ApplicationWithDeclaration;
    case DiscussionItemTypeEnum.DealWithManyPositions:
      return ApiDiscussionItemTypeEnum.DealWithManyPositions;
    case DiscussionItemTypeEnum.PreliminaryOfferSentMessage:
      return ApiDiscussionItemTypeEnum.PreliminaryOfferSentMessage;
    case DiscussionItemTypeEnum.PreliminaryOfferSignDealAfterMoneyBlock:
      return ApiDiscussionItemTypeEnum.PreliminaryOfferSignDealAfterMoneyBlock;
    case DiscussionItemTypeEnum.DealCreatedFromCart:
      return ApiDiscussionItemTypeEnum.DealCreatedFromCart;
    case DiscussionItemTypeEnum.DealCreatedZep:
      return ApiDiscussionItemTypeEnum.DealCreatedZep;
    case DiscussionItemTypeEnum.DealRejectedBySupplier:
      return ApiDiscussionItemTypeEnum.DealRejectedBySupplier;
    case DiscussionItemTypeEnum.DealRejectedBySupplierZepToZc:
      return ApiDiscussionItemTypeEnum.DealRejectedBySupplierZepToZc;
    case DiscussionItemTypeEnum.DealConditionsChangedBySupplier:
      return ApiDiscussionItemTypeEnum.DealConditionsChangedBySupplier;
    case DiscussionItemTypeEnum.DealConditionsChangedByCustomer:
      return ApiDiscussionItemTypeEnum.DealConditionsChangedByCustomer;
    case DiscussionItemTypeEnum.DealAcceptedBySupplier:
      return ApiDiscussionItemTypeEnum.DealAcceptedBySupplier;
    case DiscussionItemTypeEnum.DealAcceptedBySupplierAsNeededToCustomer:
      return ApiDiscussionItemTypeEnum.DealAcceptedBySupplierAsNeededToCustomer;
    case DiscussionItemTypeEnum.ContractFileSentBySupplier:
      return ApiDiscussionItemTypeEnum.ContractFileSentBySupplier;
    case DiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomer:
      return ApiDiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomer;
    case DiscussionItemTypeEnum.ContractSigningByCustomerIsExpired:
      return ApiDiscussionItemTypeEnum.ContractSigningByCustomerIsExpired;
    case DiscussionItemTypeEnum.ContractSentByCustomerForRework:
      return ApiDiscussionItemTypeEnum.ContractSentByCustomerForRework;
    case DiscussionItemTypeEnum.ContractSentBySupplierForRework:
      return ApiDiscussionItemTypeEnum.ContractSentBySupplierForRework;
    case DiscussionItemTypeEnum.ContractSignedByCustomer:
      return ApiDiscussionItemTypeEnum.ContractSignedByCustomer;
    case DiscussionItemTypeEnum.ContractSignedBySupplier:
      return ApiDiscussionItemTypeEnum.ContractSignedBySupplier;
    case DiscussionItemTypeEnum.ApplicationRejectedSystemMessage:
      return ApiDiscussionItemTypeEnum.ApplicationRejectedSystemMessage;
    case DiscussionItemTypeEnum.PublishCustomerComissionProtocol:
      return ApiDiscussionItemTypeEnum.PublishCustomerComissionProtocol;
    case DiscussionItemTypeEnum.PositionalComparisonDealCreated:
      return ApiDiscussionItemTypeEnum.PositionalComparisonDealCreated;
    case DiscussionItemTypeEnum.PaperDealAutoCompleted:
      return ApiDiscussionItemTypeEnum.PaperDealAutoCompleted;
    case DiscussionItemTypeEnum.SingleSupplierSentPaperDealToCustomer:
      return ApiDiscussionItemTypeEnum.SingleSupplierSentPaperDealToCustomer;
    case DiscussionItemTypeEnum.CustomerSentPaperDealToSingleSupplier:
      return ApiDiscussionItemTypeEnum.CustomerSentPaperDealToSingleSupplier;
    case DiscussionItemTypeEnum.CustomerSentParticipantOfferToRepeatReviewing:
      return ApiDiscussionItemTypeEnum.CustomerSentParticipantOfferToRepeatReviewing;
    case DiscussionItemTypeEnum.PublishCustomerComissionProtocolToEis:
      return ApiDiscussionItemTypeEnum.PublishCustomerComissionProtocolToEis;
    case DiscussionItemTypeEnum.DealExecuted:
      return ApiDiscussionItemTypeEnum.DealExecuted;
    case DiscussionItemTypeEnum.DealTerminated:
      return ApiDiscussionItemTypeEnum.DealTerminated;
    case DiscussionItemTypeEnum.SelectedOtherSupplier:
      return ApiDiscussionItemTypeEnum.SelectedOtherSupplier;
    case DiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomerZmo:
      return ApiDiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomerZmo;
    case DiscussionItemTypeEnum.ApprovedDealRejectedBySupplier:
      return ApiDiscussionItemTypeEnum.ApprovedDealRejectedBySupplier;
    case DiscussionItemTypeEnum.ReturnContractToFormingSystemMessage:
      return ApiDiscussionItemTypeEnum.ReturnContractToFormingSystemMessage;
    case DiscussionItemTypeEnum.ApplicationClarificationRequest:
      return ApiDiscussionItemTypeEnum.ApplicationClarificationRequest;
    case DiscussionItemTypeEnum.ApplicationClarificationResponse:
      return ApiDiscussionItemTypeEnum.ApplicationClarificationResponse;
    case DiscussionItemTypeEnum.AdditionalAgreementSignedByParticipantMessage:
      return ApiDiscussionItemTypeEnum.AdditionalAgreementSignedByParticipantMessage;
    case DiscussionItemTypeEnum.QuotationSessionFinalProposalConfirmed:
      return ApiDiscussionItemTypeEnum.QuotationSessionFinalProposalConfirmed;
    case DiscussionItemTypeEnum.PreliminaryOfferReturnTradeToFillingApps:
      return ApiDiscussionItemTypeEnum.PreliminaryOfferReturnTradeToFillingApps;
    case DiscussionItemTypeEnum.DealAgreementChangedBySupplier:
      return ApiDiscussionItemTypeEnum.DealAgreementChangedBySupplier;
    case DiscussionItemTypeEnum.DealAgreementChangedByCustomer:
      return ApiDiscussionItemTypeEnum.DealAgreementChangedByCustomer;
    case DiscussionItemTypeEnum.ShipmentPointEntered:
      return ApiDiscussionItemTypeEnum.ShipmentPointEntered;
    default:
      throw new Error(`Enum value is not defined: DiscussionItemTypeEnum=${String(source)}`);
  }
}
