import { TradeView } from '../../models/trade-view.interface';
import { ApiTradeViewDto } from '../../../swagger/models/api-trade-view-dto';
import { adaptApiAdditionalRequirementDto } from './api-additional-requirement-dto.adapter';
import { adaptApiCustomerContactInfoAltDto } from './api-customer-contact-info.adapter';
import { adaptApiDealStateEnum } from './api-deal-state-enum.adapter';
import { adaptApiDocumentDto } from './api-document-dto.adapter';
import { adaptApiM4DDealSignRequiredEnum } from './api-m-4-d-deal-sign-required-enum.adapter';
import { adaptApiProductDto } from './api-product-dto.adapter';
import { adaptApiSourcePlatformEnum } from './api-source-platform-enum.adapter';
import { adaptApiStateOfIncreasingForFillingApplicationEndDateAltEnum } from './api-state-of-increasing-for-filling-application-end-date.adapter';
import { adaptApiSuppliersListReportResultDto } from './api-suppliers-list-report-result-dto.adapter';
import { adaptApiTradeBusinessFlowEnum } from './api-trade-business-flow-enum.adapter';
import { adaptApiTradeGroupViewDto } from './api-trade-group-view-dto.adapter';
import { adaptApiTradeStateEnum } from './api-trade-state-enum.adapter';
import { adaptApiViewApplicationsForTradeDto } from './api-view-applications-for-trade-dto.adapter';
import { adaptApiZmoFinanceSourceEnum } from './api-zmo-finance-source-enum.adapter';

export function adaptApiTradeViewDto(source?: TradeView | null): ApiTradeViewDto {
  return {
    ActualChildOrderId: source?.actualChildOrderId,
    ActualChildTradeId: source?.actualChildTradeId,
    AdditionalInfo: source?.additionalInfo,
    AdditionalRequirements: (source?.additionalRequirements ?? []).map((item) => adaptApiAdditionalRequirementDto(item)),
    ApplicationSet: adaptApiViewApplicationsForTradeDto(source?.applicationSet),
    AutoInvitationVendors: source?.autoInvitationVendors,
    CanBeShownOnZmo: source?.canBeShownOnZmo,
    CanCheckParticipant: source?.canCheckParticipant,
    CanDownloadApplicationsData: source?.canDownloadApplicationsData,
    CanManageApplications: source?.canManageApplications,
    CanPossibleCreateDealOutsideEShop: source?.canPossibleCreateDealOutsideEShop,
    CancellationReason: source?.cancellationReason,
    ConcludeReviewApplication: source?.concludeReviewApplication,
    ConditionsOfPayment: source?.conditionsOfPayment,
    ContactInfo: adaptApiCustomerContactInfoAltDto(source?.contactInfo),
    CurrentCustomerHasDealForThisTrade: source?.currentCustomerHasDealForThisTrade,
    CurrentParticipantHasDealForThisTrade: source?.currentParticipantHasDealForThisTrade,
    CurrentStageId: source?.currentStageId,
    CustomerFullName: source?.customerFullName,
    CustomerId: source?.customerId,
    CustomerInn: source?.customerInn,
    CustomerPhysAddress: source?.customerPhysAddress,
    DealExecutionDate: source?.dealExecutionDate,
    DealState: adaptApiDealStateEnum(source?.dealState),
    DefaultPriceForSignDealOutSide: source?.defaultPriceForSignDealOutSide,
    DeliveryKladrRegionCode: source?.deliveryKladrRegionCode,
    DeliveryKladrRegionName: source?.deliveryKladrRegionName,
    DeliveryPlace: source?.deliveryPlace,
    DeliveryTerms: source?.deliveryTerms,
    Description: source?.description,
    EnableKtruCode: source?.enableKtruCode,
    EnableKtruSpecifications: source?.enableKtruSpecifications,
    EnableMonetizationZmo: source?.enableMonetizationZmo,
    EnablePositionCharacteristics: source?.enablePositionCharacteristics,
    ExternalContractTemplateId: source?.externalContractTemplateId,
    ExternalSourcePlatformNumber: source?.externalSourcePlatformNumber,
    ExternalSystemId: source?.externalSystemId,
    FillingApplicationEndDate: source?.fillingApplicationEndDate,
    FreeWinnerSelectionEnabled: source?.freeWinnerSelectionEnabled,
    HasDealSignedOutsideEShop: source?.hasDealSignedOutsideEShop,
    Id: source?.id,
    InitialPrice: source?.initialPrice,
    IsCustomerAcceptOnlyManualOffers: source?.isCustomerAcceptOnlyManualOffers,
    IsEisConcludeDealRequired: source?.isEisConcludeDealRequired,
    IsHideParticipantPrice: source?.isHideParticipantPrice,
    IsHideParticipantsApplications: source?.isHideParticipantsApplications,
    IsImmediate: source?.isImmediate,
    IsInitialPriceDefined: source?.isInitialPriceDefined,
    IsLapsed: source?.isLapsed,
    IsOnlySmp: source?.isOnlySmp,
    IsOrderCreationFromExternalNotTookPlaceTradeAvailable: source?.isOrderCreationFromExternalNotTookPlaceTradeAvailable,
    IsParentContractNumberNotSpecified: source?.isParentContractNumberNotSpecified,
    IsSendContractAllowed: source?.isSendContractAllowed,
    IsSendToNonPublicEis: source?.isSendToNonPublicEis,
    IsTradeForPartner: source?.isTradeForPartner,
    IsTradeNeedConfirmCustomerTermsWhenOffer: source?.isTradeNeedConfirmCustomerTermsWhenOffer,
    IsUnitBidding: source?.isUnitBidding,
    IsWaitingPeriodEnabled: source?.isWaitingPeriodEnabled,
    LastModificationDate: source?.lastModificationDate,
    LotAuctionId: source?.lotAuctionId,
    LotId: source?.lotId,
    LotItemsSumPrice: source?.lotItemsSumPrice,
    M4DDealSignRequired: adaptApiM4DDealSignRequiredEnum(source?.m4DDealSignRequired),
    MaxDealPrice: source?.maxDealPrice,
    OrganizerId: source?.organizerId,
    OrganizerInn: source?.organizerInn,
    OrganizerName: source?.organizerName,
    OrganizerPhysAddress: source?.organizerPhysAddress,
    OriginTradeId: source?.originTradeId,
    ParentContractNumber: source?.parentContractNumber,
    ParticipantCanCreateApplication: source?.participantCanCreateApplication,
    PaymentByBankCardEnable: source?.paymentByBankCardEnable,
    PlanedDealSignDate: source?.planedDealSignDate,
    PriceWithVat: source?.priceWithVat,
    Products: (source?.products ?? []).map((item) => adaptApiProductDto(item)),
    ProhibitPostingCustomerComissionProtocol: source?.prohibitPostingCustomerComissionProtocol,
    PublicationDate: source?.publicationDate,
    ReadOnly: source?.readOnly,
    RedirectOn223Url: source?.redirectOn223Url,
    RelatedOrderId: source?.relatedOrderId,
    ResultsDeliveryType: source?.resultsDeliveryType,
    RussianPurchaseAdvantageInfo: source?.russianPurchaseAdvantageInfo,
    ShowProtocol: source?.showProtocol,
    SourcePlatform: adaptApiSourcePlatformEnum(source?.sourcePlatform),
    StateOfIncreasing: adaptApiStateOfIncreasingForFillingApplicationEndDateAltEnum(source?.stateOfIncreasing),
    SupplierWithSmallBusinessRequirements: source?.supplierWithSmallBusinessRequirements,
    SupplierWithUniversalRequirements: source?.supplierWithUniversalRequirements,
    SuppliersListReportResult: adaptApiSuppliersListReportResultDto(source?.suppliersListReportResult),
    TenantId: source?.tenantId,
    TradeBusinessFlow: adaptApiTradeBusinessFlowEnum(source?.tradeBusinessFlow),
    TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz: source?.tradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz,
    TradeDocuments: (source?.tradeDocuments ?? []).map((item) => adaptApiDocumentDto(item)),
    TradeGroups: (source?.tradeGroups ?? []).map((item) => adaptApiTradeGroupViewDto(item)),
    TradeIdentificationCode: source?.tradeIdentificationCode,
    TradeName: source?.tradeName,
    TradeState: adaptApiTradeStateEnum(source?.tradeState),
    TradeWaitingTime: source?.tradeWaitingTime,
    ZmoFinanceSource: adaptApiZmoFinanceSourceEnum(source?.zmoFinanceSource),
    ZmoFzType: source?.zmoFzType,
  };
}
