import { MarketTradeView } from '../../models/market-trade-view.interface';
import { ApiMarketTradeViewDto } from '../../../swagger/models/api-market-trade-view-dto';
import { adaptApiAdditionalRequirementDto2 } from './api-additional-requirement-dto-2.adapter';
import { adaptApiApplicationParametersDto } from './api-application-parameters-dto.adapter';
import { adaptApiApplicationStateEnum } from './api-application-state-enum.adapter';
import { adaptApiAvailableVatTypeEnum } from './api-available-vat-type-enum.adapter';
import { adaptApiDealSignerAltDto } from './api-deal-signer.adapter';
import { adaptApiDealStateEnum } from './api-deal-state-enum.adapter';
import { adaptApiDeliveryMethodAltEnum } from './api-delivery-method.adapter';
import { adaptApiDictionaryItemAltDto } from './api-dictionary-item.adapter';
import { adaptApiEisIntegrationDataAltDto } from './api-eis-integration-data.adapter';
import { adaptApiEisTradeInfoAltDto } from './api-eis-trade-info.adapter';
import { adaptApiFederalLawLimitAltEnum } from './api-federal-law-limit.adapter';
import { adaptApiLotStateEnum } from './api-lot-state-enum.adapter';
import { adaptApiM4DDealSignRequiredEnum } from './api-m-4-d-deal-sign-required-enum.adapter';
import { adaptApiMarketDealStateEnum } from './api-market-deal-state-enum.adapter';
import { adaptApiMarketEntityTypeAltEnum } from './api-market-entity-type.adapter';
import { adaptApiMarketTradeDealAltDto } from './api-market-trade-deal.adapter';
import { adaptApiMarketTradePersonAltDto } from './api-market-trade-person.adapter';
import { adaptApiMarketTradeProductAltDto } from './api-market-trade-product.adapter';
import { adaptApiMeetsRequirementsEnum } from './api-meets-requirements-enum.adapter';
import { adaptApiMyTermsAltDto } from './api-my-terms.adapter';
import { adaptApiOrderStateEnum } from './api-order-state-enum.adapter';
import { adaptApiPriceCorridorDto } from './api-price-corridor-dto.adapter';
import { adaptApiPurchaseMethodTypeEnum } from './api-purchase-method-type-enum.adapter';
import { adaptApiRegulationInfoDto } from './api-regulation-info-dto.adapter';
import { adaptApiRetradingTypeEnum } from './api-retrading-type-enum.adapter';
import { adaptApiShortTenantSettingAltDto } from './api-short-tenant-setting.adapter';
import { adaptApiTradeBusinessFlowEnum } from './api-trade-business-flow-enum.adapter';
import { adaptApiTradeLotSpecificationDto } from './api-trade-lot-specification-dto.adapter';
import { adaptApiTradeStateEnum } from './api-trade-state-enum.adapter';
import { adaptApiTradeViewFormOptionsDto } from './api-trade-view-form-options-dto.adapter';
import { adaptApiVatRateStateEnum } from './api-vat-rate-state-enum.adapter';
import { adaptApiZmoFinanceSourceEnum } from './api-zmo-finance-source-enum.adapter';

export function adaptApiMarketTradeViewDto(source?: MarketTradeView | null): ApiMarketTradeViewDto {
  return {
    AdditionalRequirements: (source?.additionalRequirements ?? []).map((item) => adaptApiAdditionalRequirementDto2(item)),
    AllowApplicationReject: source?.allowApplicationReject,
    ApplicationId: source?.applicationId,
    ApplicationParameters: adaptApiApplicationParametersDto(source?.applicationParameters),
    ApplicationState: adaptApiApplicationStateEnum(source?.applicationState),
    BusinessFlowType: adaptApiTradeBusinessFlowEnum(source?.businessFlowType),
    CanSuggestPaperFormSigning: source?.canSuggestPaperFormSigning,
    ChildTradeBusinessFlowType: adaptApiTradeBusinessFlowEnum(source?.childTradeBusinessFlowType),
    ChildTradeHosts: source?.childTradeHosts ?? [],
    ChildTradeId: source?.childTradeId,
    ConditionsOfPayment: source?.conditionsOfPayment,
    ContactPerson: adaptApiMarketTradePersonAltDto(source?.contactPerson),
    ContractAmountInfo: source?.contractAmountInfo,
    CurrencyCode: source?.currencyCode,
    CurrentStageId: source?.currentStageId,
    CustomerExternalOrganizationId: source?.customerExternalOrganizationId,
    CustomerFullName: source?.customerFullName,
    CustomerGuid: source?.customerGuid,
    CustomerId: source?.customerId,
    CustomerPhysAddress: source?.customerPhysAddress,
    CustomerSource: source?.customerSource,
    DealBelongToCurrentOrg: source?.dealBelongToCurrentOrg,
    DealConclusionTermInfo: source?.dealConclusionTermInfo,
    DealDirectionFlow: source?.dealDirectionFlow,
    DealExecutionDate: source?.dealExecutionDate,
    DealId: source?.dealId,
    DealState: adaptApiDealStateEnum(source?.dealState),
    Deals: (source?.deals ?? []).map((item) => adaptApiMarketTradeDealAltDto(item)),
    DeliveryKladrRegionCode: source?.deliveryKladrRegionCode,
    DeliveryKladrRegionCodes: (source?.deliveryKladrRegionCodes ?? []).map((item) => adaptApiDictionaryItemAltDto(item)),
    DeliveryKladrRegionName: source?.deliveryKladrRegionName,
    DeliveryMethod: adaptApiDeliveryMethodAltEnum(source?.deliveryMethod),
    DeliveryTerms: source?.deliveryTerms,
    Description: source?.description,
    DisplayApproveBtn: source?.displayApproveBtn,
    DisplayDealDontConcludeBtn: source?.displayDealDontConcludeBtn,
    EisIntegrationData: adaptApiEisIntegrationDataAltDto(source?.eisIntegrationData),
    EisTradeInfo: adaptApiEisTradeInfoAltDto(source?.eisTradeInfo),
    EnableKtruSpecifications: source?.enableKtruSpecifications,
    EnableMonetizationMarket: source?.enableMonetizationMarket,
    EnablePositionCharacteristics: source?.enablePositionCharacteristics,
    EntityType: adaptApiMarketEntityTypeAltEnum(source?.entityType),
    ExternalId: source?.externalId,
    ExternalSystemId: source?.externalSystemId,
    FederalLawLimit: adaptApiFederalLawLimitAltEnum(source?.federalLawLimit),
    FillingApplicationEndDate: source?.fillingApplicationEndDate,
    HasDealFile: source?.hasDealFile,
    HasManualParticipantOfferToTrade: source?.hasManualParticipantOfferToTrade,
    HasUncompletedEisOutgoingSaga: source?.hasUncompletedEisOutgoingSaga,
    Hosts: source?.hosts ?? [],
    Id: source?.id,
    InitialPriceWithVat: source?.initialPriceWithVat,
    InitialPriceWithoutVat: source?.initialPriceWithoutVat,
    InitialTenantSetting: adaptApiShortTenantSettingAltDto(source?.initialTenantSetting),
    IsApprovalRequestExists: source?.isApprovalRequestExists,
    IsAutoCreateDealAfterReviewApplications: source?.isAutoCreateDealAfterReviewApplications,
    IsAvailableSelectOnlyOneOfferForItem: source?.isAvailableSelectOnlyOneOfferForItem,
    IsBy223Fz: source?.isBy223Fz,
    IsBy44Fz: source?.isBy44Fz,
    IsContractInElectronicForm: source?.isContractInElectronicForm,
    IsCustomPrice: source?.isCustomPrice,
    IsCustomer: source?.isCustomer,
    IsCustomerAcceptByOkeiOffers: source?.isCustomerAcceptByOkeiOffers,
    IsCustomerAcceptOnlyManualOffers: source?.isCustomerAcceptOnlyManualOffers,
    IsDealSigningExpired: source?.isDealSigningExpired,
    IsEditable: source?.isEditable,
    IsEisConcludeDealRequired: source?.isEisConcludeDealRequired,
    IsEisTradeAccelerated: source?.isEisTradeAccelerated,
    IsFederalLawsEnable: source?.isFederalLawsEnable,
    IsHiddenContract: source?.isHiddenContract,
    IsImmediate: source?.isImmediate,
    IsImportPhaseout: source?.isImportPhaseout,
    IsInEisWasChanged: source?.isInEisWasChanged,
    IsInitialPriceDefined: source?.isInitialPriceDefined,
    IsInitialPriceReduction: source?.isInitialPriceReduction,
    IsLapsed: source?.isLapsed,
    IsLotPriceEnteredWithVAT: source?.isLotPriceEnteredWithVAT,
    IsLotPriceWithVat: source?.isLotPriceWithVat,
    IsModificationSentToOos: source?.isModificationSentToOos,
    IsOnlySmp: source?.isOnlySmp,
    IsOrganizer: source?.isOrganizer,
    IsParentContractNumberNotSpecified: source?.isParentContractNumberNotSpecified,
    IsPositionalVatEnable: source?.isPositionalVatEnable,
    IsPrivate: source?.isPrivate,
    IsRetradingEnabled: source?.isRetradingEnabled,
    IsRussianPurchaseObjectHasAdvantage: source?.isRussianPurchaseObjectHasAdvantage,
    IsSanctionedPurchase: source?.isSanctionedPurchase,
    IsSendToEis: source?.isSendToEis,
    IsSingleWinner: source?.isSingleWinner,
    IsSmallBusinessEntity: source?.isSmallBusinessEntity,
    IsSortApplicationsByPriceWithoutVat: source?.isSortApplicationsByPriceWithoutVat,
    IsTradeNeedConfirmCustomerTermsWhenOffer: source?.isTradeNeedConfirmCustomerTermsWhenOffer,
    IsUnitBidding: source?.isUnitBidding,
    ItemsCount: source?.itemsCount,
    LotAuctionId: source?.lotAuctionId,
    LotId: source?.lotId,
    LotItemsSumPrice: source?.lotItemsSumPrice,
    M4DDealSignRequired: adaptApiM4DDealSignRequiredEnum(source?.m4DDealSignRequired),
    MarketState: adaptApiMarketDealStateEnum(source?.marketState),
    MarketStateDescription: source?.marketStateDescription,
    MaxDealPriceWithVat: source?.maxDealPriceWithVat,
    MaxDealPriceWithoutVat: source?.maxDealPriceWithoutVat,
    MeetsRequirements: adaptApiMeetsRequirementsEnum(source?.meetsRequirements),
    MovingProLink: source?.movingProLink,
    NeedBlockMoney: source?.needBlockMoney,
    OfferId: source?.offerId,
    OfferTerms: adaptApiMyTermsAltDto(source?.offerTerms),
    OnlyOneRetradingBidAllowed: source?.onlyOneRetradingBidAllowed,
    OrderState: adaptApiOrderStateEnum(source?.orderState),
    OrganizerExternalOrganizationId: source?.organizerExternalOrganizationId,
    OrganizerFullName: source?.organizerFullName,
    OrganizerGuid: source?.organizerGuid,
    OrganizerId: source?.organizerId,
    OrganizerSource: source?.organizerSource,
    Original223TradeLotState: adaptApiLotStateEnum(source?.original223TradeLotState),
    ParentContractNumber: source?.parentContractNumber,
    ParentNotTookPlaceTradeBusinessFlowType: adaptApiTradeBusinessFlowEnum(source?.parentNotTookPlaceTradeBusinessFlowType),
    ParentNotTookPlaceTradeHosts: source?.parentNotTookPlaceTradeHosts ?? [],
    ParentNotTookPlaceTradeId: source?.parentNotTookPlaceTradeId,
    ParticipantExternalOrganizationId: source?.participantExternalOrganizationId,
    ParticipantFullName: source?.participantFullName,
    ParticipantGuid: source?.participantGuid,
    ParticipantId: source?.participantId,
    ParticipantSource: source?.participantSource,
    PictureGuids: source?.pictureGuids ?? [],
    PlanNumber: source?.planNumber,
    PlanPositionNumber: source?.planPositionNumber,
    PlanedDealSignDate: source?.planedDealSignDate,
    PossibleSelfDelivery: source?.possibleSelfDelivery,
    PossibleSendByTransportCompany: source?.possibleSendByTransportCompany,
    Price: source?.price,
    PriceCorridor: adaptApiPriceCorridorDto(source?.priceCorridor),
    PriceWithVat: source?.priceWithVat,
    Products: (source?.products ?? []).map((item) => adaptApiMarketTradeProductAltDto(item)),
    ProhibitPostingCustomerComissionProtocol: source?.prohibitPostingCustomerComissionProtocol,
    ProtocolReadyToPublish: source?.protocolReadyToPublish,
    PublicationDate: source?.publicationDate,
    PurchaseMethodType: adaptApiPurchaseMethodTypeEnum(source?.purchaseMethodType),
    RateVat: adaptApiAvailableVatTypeEnum(source?.rateVat),
    RegulationInfo: adaptApiRegulationInfoDto(source?.regulationInfo),
    RequiredSupplierRegistration: source?.requiredSupplierRegistration,
    RequirementsInfo: source?.requirementsInfo,
    RetradingBidLeftCount: source?.retradingBidLeftCount,
    RetradingEndDate: source?.retradingEndDate,
    RetradingStartDate: source?.retradingStartDate,
    RetradingType: adaptApiRetradingTypeEnum(source?.retradingType),
    RussianPurchaseAdvantageInfo: source?.russianPurchaseAdvantageInfo,
    ShowProtocol: source?.showProtocol,
    ShowProtocolDocument: source?.showProtocolDocument,
    Signer: adaptApiDealSignerAltDto(source?.signer),
    Specifications: (source?.specifications ?? []).map((item) => adaptApiTradeLotSpecificationDto(item)),
    SupplierWithSmallBusinessRequirements: source?.supplierWithSmallBusinessRequirements,
    SupplierWithUniversalRequirements: source?.supplierWithUniversalRequirements,
    Tags: source?.tags ?? [],
    TenantId: source?.tenantId,
    TradeName: source?.tradeName,
    TradeNumber: source?.tradeNumber,
    TradeState: adaptApiTradeStateEnum(source?.tradeState),
    TradeSum: source?.tradeSum,
    TradeViewFormOptions: adaptApiTradeViewFormOptionsDto(source?.tradeViewFormOptions),
    VatRate: source?.vatRate,
    VatRateDescription: source?.vatRateDescription,
    VatRateState: adaptApiVatRateStateEnum(source?.vatRateState),
    WinnerTradeLotApplicationId: source?.winnerTradeLotApplicationId,
    WorkGroupIds: source?.workGroupIds ?? [],
    ZmoFinanceSource: adaptApiZmoFinanceSourceEnum(source?.zmoFinanceSource),
    ZmoFinanceSourceDescription: source?.zmoFinanceSourceDescription,
    ZmoFzType: source?.zmoFzType,
    ZmoFzTypeDescription: source?.zmoFzTypeDescription,
    ZmoFzTypeHint: source?.zmoFzTypeHint,
    ZmoFzTypeName: source?.zmoFzTypeName,
  };
}
