import { AdditionalService } from './additional-service.interface';
import { ApplicationDocument } from './application-document.interface';
import { ApplicationItem } from './application-item.interface';
import { ApplicationProduct } from './application-product.interface';
import { ApplicationSourceEnum } from '../enums/application-source.enum';
import { ApplicationStateEnum } from '../enums/application-state.enum';
import { AuctionBid } from './auction-bid.interface';
import { AvailableVatTypeEnum } from '../enums/available-vat-type.enum';
import { ContactInfo } from './contact-info.interface';
import { OrganizationRegistryDocument } from './organization-registry-document.interface';
import { PaymentMethodEnum } from '../enums/payment-method.enum';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { TradeStateEnum } from '../enums/trade-state.enum';
import { VatRateStateEnum } from '../enums/vat-rate-state.enum';

// @ts-ignore
export interface ApplicationDto2 {
  accountNumber: string;
  additionalServices: AdditionalService[];
  agreeWithCustomerConditions: boolean;
  applicationDocuments: ApplicationDocument[];
  applicationItems: ApplicationItem[];
  applicationSource: ApplicationSourceEnum;
  applicationState: ApplicationStateEnum;
  applicationStateDescription: string;
  applicationStateId: number;
  auctionBids: AuctionBid[];
  bankingDetailId: number;
  canDelete: boolean;
  canEdit: boolean;
  canWithdraw: boolean;
  conditionsOfPayment: string;
  contactInfo: ContactInfo;
  createdByCustomer: boolean;
  defineCustomPriceForEachProduct: boolean;
  deliveryPlace: string;
  deliveryTerms: string;
  emailForReceipt: string;
  enableKtruSpecifications: boolean;
  enablePositionCharacteristics: boolean;
  id: number;
  incomplianceWithTheRequirementsReason: string;
  isLotPriceWithVat: boolean;
  isOrderApplication: boolean;
  isPriceEnteredWithVat: boolean;
  isPublicOffer: boolean;
  isQuotationWithVat: boolean;
  isRequirementsConfirmationCheck: boolean;
  isSelfDelivery: boolean;
  isSellerDelivery: boolean;
  isTransportCompanyDelivery: boolean;
  neverExpired: boolean;
  offerExpiryDate: string;
  organizationRegistryDocuments: OrganizationRegistryDocument[];
  payCommissionReportGuid: string;
  paymentMethod: PaymentMethodEnum;
  price: number;
  priceWithVat: number;
  products: ApplicationProduct[];
  publicationDate: string;
  rateVat: AvailableVatTypeEnum;
  reductionCoefficient: number;
  resultPosition: number;
  rowVersion: number;
  selfDeliveryPlace: string;
  sellerDeliveryPrice: number;
  shipmentPoint: string;
  submitterId: string;
  submitterName: string;
  sumVat: number;
  tenantSource: number;
  tradeBusinessFlow: TradeBusinessFlowEnum;
  tradeId: number;
  tradeLotId: number;
  tradeOrganizerId: number;
  tradeState: TradeStateEnum;
  transportCompanyDeliveryPrice: number;
  vatRate: number;
  vatRateDescription: string;
  vatRateState: VatRateStateEnum;
  wasRejected: boolean;
}
