import { AdditionalAgreement } from './additional-agreement.interface';
import { ApplicationStateEnum } from '../enums/application-state.enum';
import { ContactInfo } from './contact-info.interface';
import { DealDocument } from './deal-document.interface';
import { DealEisIntegrationDataAlt } from './deal-eis-integration-data-alt.interface';
import { DealFormEnum } from '../enums/deal-form.enum';
import { DealObjectEnum } from '../enums/deal-object.enum';
import { DealPosition } from './deal-position.interface';
import { DealStateEnum } from '../enums/deal-state.enum';
import { OrganizationCountryAltEnum } from '../enums/organization-country-alt.enum';
import { PartisipantInfoForDealOutSideEShopAlt } from './partisipant-info-for-deal-out-side-e-shop-alt.interface';

export interface FullDeal {
  additionalAgreements: AdditionalAgreement[];
  allowPaperDealForm: boolean;
  applicationId: number;
  applicationState: ApplicationStateEnum;
  budgetId: number;
  buyerAgreementComment: string;
  cancellationReason: string;
  changeRequestReason: string;
  chatId: number;
  conclusionDate: string;
  contactInfo: ContactInfo;
  contractExecutionDate: string;
  customContractNumber: string;
  customerCancellationReason: string;
  dealComment: string;
  dealCustomNumber: string;
  dealEisCustomNumber: string;
  dealObject: DealObjectEnum;
  dealObjectName: string;
  dealOutSideEshop: boolean;
  dealPositions: DealPosition[];
  differenceProtocolReason: string;
  documents: DealDocument[];
  eisIntegrationData: DealEisIntegrationDataAlt;
  executionFrom: string;
  executionTo: string;
  externalSystemId: number;
  form: DealFormEnum;
  id: number;
  isAttachPaperDealDocumentsAllowed: boolean;
  isContractSignedOutOfEp: boolean;
  isCreateAdditionalAgreementsAllowed: boolean;
  isDealExecutionOrTerminationAllowed: boolean;
  isPriceChanged: boolean;
  isSendContractAllowed: boolean;
  isSendDealToEisAllowed: boolean;
  isUnitBidding: boolean;
  participantExternalOrganizationId: string;
  participantGuid: string;
  participantId: string;
  participantInn: string;
  participantKpp: string;
  participantName: string;
  participantOrganizationCountry: OrganizationCountryAltEnum;
  participantPhone: string;
  participantSource: number;
  participantWarningMessage: string;
  partisipantInfo: PartisipantInfoForDealOutSideEShopAlt;
  price: number;
  priceWarningMessage: string;
  readOnly: boolean;
  refusedByCustomerDate: string;
  requestReason: boolean;
  sendToProviderDate: string;
  showDownloadFileLinks: boolean;
  signByProviderDate: string;
  signedByOrganizer: boolean;
  state: DealStateEnum;
  tradeId: number;
  tradeIdentificationCode: string;
  tradeLotId: number;
  workGroupIds: number[];
}
