import { ApprovalRequestStateEnum } from '../enums/approval-request-state.enum';
import { DictionaryItemAlt } from './dictionary-item-alt.interface';
import { DiscussionItemTypeEnum } from '../enums/discussion-item-type.enum';
import { MarketDealStateEnum } from '../enums/market-deal-state.enum';
import { PurchaseMethodTypeEnum } from '../enums/purchase-method-type.enum';
import { RetradingTypeEnum } from '../enums/retrading-type.enum';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';

// @ts-ignore
export interface MarketDealAlt {
  approvalRequestState: ApprovalRequestStateEnum;
  auctionEndDate: string;
  bidsCount: number;
  businessFlowType: TradeBusinessFlowEnum;
  countApplications: number;
  counterPartyOrganizationGuid: string;
  counterPartyOrganizationId: number;
  currencyCode: string;
  customerExternalOrganizationId: string;
  customerGuid: string;
  customerNameAndInn: string;
  customerSource: number;
  dealStateId: number;
  dealStateName: string;
  deliveryKladrRegionName: string;
  deliveryKladrs: DictionaryItemAlt[];
  discussionId: number;
  downloads: number;
  externalId: string;
  externalSystemId: number;
  fillingApplicationEndDate: string;
  hosts: string[];
  id: number;
  isAnyApplicationExists: boolean;
  isContractSigningSuspended: boolean;
  isDetailedMetricsAccessible: boolean;
  isImmediate: boolean;
  isImportPhaseout: boolean;
  isPublicApplication: boolean;
  isRetradingEnabled: boolean;
  isSuspended: boolean;
  isUnitBidding: boolean;
  lastDiscussionItemDate: string;
  lastDiscussionItemType: DiscussionItemTypeEnum;
  lotItemsCount: number;
  marketDealState: MarketDealStateEnum;
  marketDealStateDescription: string;
  onlyOneRetradingBidAllowed: boolean;
  orderChangeQuantity: number;
  orderChangeUnitPrice: number;
  organizerGuid: string;
  organizerNameAndInn: string;
  pictureFileGuids: string[];
  planNumber: string;
  planPositionNumber: string;
  price: number;
  publicationDate: string;
  purchaseMethodType: PurchaseMethodTypeEnum;
  quantity: number;
  retradingEndDate: string;
  retradingStartDate: string;
  retradingType: RetradingTypeEnum;
  shortOkeiName: string;
  tradeName: string;
  tradeNumber: string;
  unitPrice: number;
  unitPriceInCurrency: number;
  views: number;
}
