import { AdditionalRequirementDto2 } from './additional-requirement-dto-2.interface';
import { ApplicationParameters } from './application-parameters.interface';
import { ApplicationStateEnum } from '../enums/application-state.enum';
import { AvailableVatTypeEnum } from '../enums/available-vat-type.enum';
import { DealSignerAlt } from './deal-signer-alt.interface';
import { DealStateEnum } from '../enums/deal-state.enum';
import { DeliveryMethodAltEnum } from '../enums/delivery-method-alt.enum';
import { DictionaryItemAlt } from './dictionary-item-alt.interface';
import { EisIntegrationDataAlt } from './eis-integration-data-alt.interface';
import { EisTradeInfoAlt } from './eis-trade-info-alt.interface';
import { FederalLawLimitAltEnum } from '../enums/federal-law-limit-alt.enum';
import { LotStateEnum } from '../enums/lot-state.enum';
import { M4DDealSignRequiredEnum } from '../enums/m-4-d-deal-sign-required.enum';
import { MarketDealStateEnum } from '../enums/market-deal-state.enum';
import { MarketEntityTypeAltEnum } from '../enums/market-entity-type-alt.enum';
import { MarketTradeDealAlt } from './market-trade-deal-alt.interface';
import { MarketTradePersonAlt } from './market-trade-person-alt.interface';
import { MarketTradeProductAlt } from './market-trade-product-alt.interface';
import { MeetsRequirementsEnum } from '../enums/meets-requirements.enum';
import { MyTermsAlt } from './my-terms-alt.interface';
import { OrderStateEnum } from '../enums/order-state.enum';
import { PriceCorridor } from './price-corridor.interface';
import { PurchaseMethodTypeEnum } from '../enums/purchase-method-type.enum';
import { RegulationInfo } from './regulation-info.interface';
import { RetradingTypeEnum } from '../enums/retrading-type.enum';
import { ShortTenantSettingAlt } from './short-tenant-setting-alt.interface';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { TradeLotSpecification } from './trade-lot-specification.interface';
import { TradeStateEnum } from '../enums/trade-state.enum';
import { TradeViewFormOptions } from './trade-view-form-options.interface';
import { VatRateStateEnum } from '../enums/vat-rate-state.enum';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

// @ts-ignore
export interface MarketTradeView {
  additionalRequirements: AdditionalRequirementDto2[];
  allowApplicationReject: boolean;
  applicationId: number;
  applicationParameters: ApplicationParameters;
  applicationState: ApplicationStateEnum;
  businessFlowType: TradeBusinessFlowEnum;
  canSuggestPaperFormSigning: boolean;
  childTradeBusinessFlowType: TradeBusinessFlowEnum;
  childTradeHosts: string[];
  childTradeId: number;
  conditionsOfPayment: string;
  contactPerson: MarketTradePersonAlt;
  contractAmountInfo: string;
  currencyCode: string;
  currentStageId: number;
  customerExternalOrganizationId: string;
  customerFullName: string;
  customerGuid: string;
  customerId: number;
  customerPhysAddress: string;
  customerSource: number;
  dealBelongToCurrentOrg: boolean;
  dealConclusionTermInfo: string;
  dealDirectionFlow: number;
  dealExecutionDate: string;
  dealId: number;
  dealState: DealStateEnum;
  deals: MarketTradeDealAlt[];
  deliveryKladrRegionCode: string;
  deliveryKladrRegionCodes: DictionaryItemAlt[];
  deliveryKladrRegionName: string;
  deliveryMethod: DeliveryMethodAltEnum;
  deliveryTerms: string;
  description: string;
  displayApproveBtn: boolean;
  displayDealDontConcludeBtn: boolean;
  eisIntegrationData: EisIntegrationDataAlt;
  eisTradeInfo: EisTradeInfoAlt;
  enableKtruSpecifications: boolean;
  enableMonetizationMarket: boolean;
  enablePositionCharacteristics: boolean;
  entityType: MarketEntityTypeAltEnum;
  externalId: string;
  externalSystemId: number;
  federalLawLimit: FederalLawLimitAltEnum;
  fillingApplicationEndDate: string;
  hasDealFile: boolean;
  hasManualParticipantOfferToTrade: boolean;
  hasUncompletedEisOutgoingSaga: boolean;
  hosts: string[];
  id: number;
  initialPriceWithVat: number;
  initialPriceWithoutVat: number;
  initialTenantSetting: ShortTenantSettingAlt;
  isApprovalRequestExists: boolean;
  isAutoCreateDealAfterReviewApplications: boolean;
  isAvailableSelectOnlyOneOfferForItem: boolean;
  isBy223Fz: boolean;
  isBy44Fz: boolean;
  isContractInElectronicForm: boolean;
  isCustomPrice: boolean;
  isCustomer: boolean;
  isCustomerAcceptByOkeiOffers: boolean;
  isCustomerAcceptOnlyManualOffers: boolean;
  isDealSigningExpired: boolean;
  isEditable: boolean;
  isEisConcludeDealRequired: boolean;
  isEisTradeAccelerated: boolean;
  isFederalLawsEnable: boolean;
  isHiddenContract: boolean;
  isImmediate: boolean;
  isImportPhaseout: boolean;
  isInEisWasChanged: boolean;
  isInitialPriceDefined: boolean;
  isInitialPriceReduction: boolean;
  isLapsed: boolean;
  isLotPriceEnteredWithVAT: boolean;
  isLotPriceWithVat: boolean;
  isModificationSentToOos: boolean;
  isOnlySmp: boolean;
  isOrganizer: boolean;
  isParentContractNumberNotSpecified: boolean;
  isPositionalVatEnable: boolean;
  isPrivate: boolean;
  isRetradingEnabled: boolean;
  isRussianPurchaseObjectHasAdvantage: boolean;
  isSanctionedPurchase: boolean;
  isSendToEis: boolean;
  isSingleWinner: boolean;
  isSmallBusinessEntity: boolean;
  isSortApplicationsByPriceWithoutVat: boolean;
  isTradeNeedConfirmCustomerTermsWhenOffer: boolean;
  isUnitBidding: boolean;
  itemsCount: number;
  lotAuctionId: number;
  lotId: number;
  lotItemsSumPrice: number;
  m4DDealSignRequired: M4DDealSignRequiredEnum;
  marketState: MarketDealStateEnum;
  marketStateDescription: string;
  maxDealPriceWithVat: number;
  maxDealPriceWithoutVat: number;
  meetsRequirements: MeetsRequirementsEnum;
  movingProLink: string;
  needBlockMoney: boolean;
  offerId: number;
  offerTerms: MyTermsAlt;
  onlyOneRetradingBidAllowed: boolean;
  orderState: OrderStateEnum;
  organizerExternalOrganizationId: string;
  organizerFullName: string;
  organizerGuid: string;
  organizerId: number;
  organizerSource: number;
  original223TradeLotState: LotStateEnum;
  parentContractNumber: string;
  parentNotTookPlaceTradeBusinessFlowType: TradeBusinessFlowEnum;
  parentNotTookPlaceTradeHosts: string[];
  parentNotTookPlaceTradeId: number;
  participantExternalOrganizationId: string;
  participantFullName: string;
  participantGuid: string;
  participantId: number;
  participantSource: number;
  pictureGuids: string[];
  planNumber: string;
  planPositionNumber: string;
  planedDealSignDate: string;
  possibleSelfDelivery: boolean;
  possibleSendByTransportCompany: boolean;
  price: number;
  priceCorridor: PriceCorridor;
  priceWithVat: boolean;
  products: MarketTradeProductAlt[];
  prohibitPostingCustomerComissionProtocol: boolean;
  protocolReadyToPublish: boolean;
  publicationDate: string;
  purchaseMethodType: PurchaseMethodTypeEnum;
  rateVat: AvailableVatTypeEnum;
  regulationInfo: RegulationInfo;
  requiredSupplierRegistration: boolean;
  requirementsInfo: string;
  retradingBidLeftCount: number;
  retradingEndDate: string;
  retradingStartDate: string;
  retradingType: RetradingTypeEnum;
  russianPurchaseAdvantageInfo: string;
  showProtocol: boolean;
  showProtocolDocument: boolean;
  signer: DealSignerAlt;
  specifications: TradeLotSpecification[];
  supplierWithSmallBusinessRequirements: boolean;
  supplierWithUniversalRequirements: boolean;
  tags: string[];
  tenantId: number;
  tradeName: string;
  tradeNumber: string;
  tradeState: TradeStateEnum;
  tradeSum: number;
  tradeViewFormOptions: TradeViewFormOptions;
  vatRate: number;
  vatRateDescription: string;
  vatRateState: VatRateStateEnum;
  winnerTradeLotApplicationId: number;
  workGroupIds: number[];
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFinanceSourceDescription: string;
  zmoFzType: number;
  zmoFzTypeDescription: string;
  zmoFzTypeHint: string;
  zmoFzTypeName: string;
}
