import { ExternalSystemsSettings } from './external-systems-settings.interface';
import { MarketOfficeOrganizationContact } from './market-office-organization-contact.interface';
import { MarketProtocolSettings } from './market-protocol-settings.interface';
import { MarketPurchaseSettings } from './market-purchase-settings.interface';
import { OrgAccreditationLevel } from './org-accreditation-level.interface';
import { OrganizationActivityInfo } from './organization-activity-info.interface';
import { OrganizationBankInfo } from './organization-bank-info.interface';
import { OrganizationContacts } from './organization-contacts.interface';
import { OrganizationDescription } from './organization-description.interface';
import { OrganizationDesign } from './organization-design.interface';
import { OrganizationEmployeesInfo } from './organization-employees-info.interface';
import { OrganizationProfileDocument } from './organization-profile-document.interface';
import { OrganizationTypeEnum } from '../enums/organization-type.enum';
import { Restrictions } from './restrictions.interface';
import { TagView } from './tag-view.interface';

export interface MarketOrganizationFullInfo {
  activityInfo: OrganizationActivityInfo;
  bankInfos: OrganizationBankInfo[];
  categories: string[];
  contacts: OrganizationContacts;
  description: OrganizationDescription;
  design: OrganizationDesign;
  director: string;
  documents: OrganizationProfileDocument[];
  domainName: string;
  email: string;
  employeesInfo: OrganizationEmployeesInfo;
  externalSystemsSettings: ExternalSystemsSettings;
  guid: string;
  id: number;
  industries: string[];
  inn: string;
  instagram: string;
  isExporter: boolean;
  isManufacturer: boolean;
  isSmb: boolean;
  kpp: string;
  name: string;
  offices: MarketOfficeOrganizationContact[];
  ogrn: string;
  okato: string;
  okpo: string;
  okved: string;
  orgAccreditationLevel: OrgAccreditationLevel;
  phoneNumber: string;
  protocolSettings: MarketProtocolSettings;
  purchaseSettings: MarketPurchaseSettings;
  restrictions: Restrictions;
  tags: TagView[];
  telegram: string;
  type: OrganizationTypeEnum;
  videoUrls: string[];
  vkontakte: string;
  webSiteUrl: string;
  youtube: string;
}
