import { B2BCategory } from './b-2-b-category.interface';
import { Characteristic } from './characteristic.interface';
import { CharacteristicValues } from './characteristic-values.interface';
import { Country } from './country.interface';
import { DeliveryRegionInfo } from './delivery-region-info.interface';
import { DisplayCharacteristic } from './display-characteristic.interface';
import { ManufacturerCountryRegistryTypeEnum } from '../enums/manufacturer-country-registry-type.enum';
import { OfferCreatedMethodEnum } from '../enums/offer-created-method.enum';
import { Okpd2Market } from './okpd-2-market.interface';
import { OrganizationCountryAltEnum } from '../enums/organization-country-alt.enum';
import { ParticipantOfferActions } from './participant-offer-actions.interface';
import { ParticipantOfferDocument } from './participant-offer-document.interface';
import { ParticipantOfferSourceEnum } from '../enums/participant-offer-source.enum';
import { ParticipantOfferSpecificFlagEnum } from '../enums/participant-offer-specific-flag.enum';
import { ParticipantOfferStateEnum } from '../enums/participant-offer-state.enum';
import { ParticipantOfferTypeEnum } from '../enums/participant-offer-type.enum';
import { PriceListStateEnum } from '../enums/price-list-state.enum';
import { PriceListTypeEnum } from '../enums/price-list-type.enum';
import { PriceRegionDetail } from './price-region-detail.interface';
import { RegionKladr } from './region-kladr.interface';
import { TagView } from './tag-view.interface';
import { TruTypeEnum } from '../enums/tru-type.enum';
import { UsedClassificatorTypeEnum } from '../enums/used-classificator-type.enum';
import { VatRateStateEnum } from '../enums/vat-rate-state.enum';
import { YmlParam } from './yml-param.interface';

// @ts-ignore
export interface MarketParticipantOfferInfo {
  actions: ParticipantOfferActions;
  barCode: string;
  category: B2BCategory;
  characteristicValues: CharacteristicValues[];
  characteristics: Characteristic[];
  classificatorCode: string;
  classificatorDescription: string;
  country: Country;
  countryCode: string;
  countryOfOrigin: string;
  createdMethod: OfferCreatedMethodEnum;
  currencyCode: string;
  deliveryCost: number;
  deliveryPlace: string;
  deliveryRegionInfos: DeliveryRegionInfo[];
  deliveryRegions: string;
  deliveryTerms: string;
  displayCharacteristics: DisplayCharacteristic[];
  dosageForm: string;
  dosageMeasureUnits: string;
  drugDosage: string;
  duringDays: number;
  exclusiveToTradeId: number;
  exclusiveToTradeNumber: string;
  externalSystemIdentifier: string;
  externalSystemIdentifierNumeric: number;
  id: number;
  isFromGuarnteeSupplier: boolean;
  isOwner: boolean;
  isParticipatesInRequirementRequests: boolean;
  isPhysicalPerson: boolean;
  isPublicOffer: boolean;
  ksrCode: string;
  ksrName: string;
  ksrUnit: string;
  manufacturer: string;
  manufacturerCountryRegistryNumber: string;
  manufacturerCountryRegistryType: ManufacturerCountryRegistryTypeEnum;
  manufacturerCountryScore: number;
  movingProLink: string;
  offerOwner: boolean;
  offerState: ParticipantOfferStateEnum;
  offerStateDescription: string;
  offerTerms: string;
  offerType: ParticipantOfferTypeEnum;
  offerTypeDescription: string;
  okeiCode: string;
  okeiDescription: string;
  okpd2Values: Okpd2Market[];
  params: YmlParam[];
  participantCountry: OrganizationCountryAltEnum;
  participantForeignId: string;
  participantGuid: string;
  participantId: number;
  participantInn: string;
  participantKpp: string;
  participantName: string;
  participantOfferDocuments: ParticipantOfferDocument[];
  participantOfferSource: ParticipantOfferSourceEnum;
  participantOfferSpecific: ParticipantOfferSpecificFlagEnum;
  participantSource: number;
  possibleDeliveryBySeller: boolean;
  possibleSelfDelivery: boolean;
  possibleSendByTransportCompany: boolean;
  priceListDeliveryRegionInfos: DeliveryRegionInfo[];
  priceListId: number;
  priceListState: PriceListStateEnum;
  priceListType: PriceListTypeEnum;
  priceRegionDetails: PriceRegionDetail[];
  printFormFileName: string;
  printFormGuid: string;
  producer: string;
  productDescription: string;
  productMNN: string;
  productName: string;
  publishDate: string;
  publishDateStart: string;
  recipientOrganizationInn: string;
  recipientOrganizationKpp: string;
  recipientOrganizationName: string;
  regionalProductSignCanEdit: boolean;
  regionalProductSignChecked: boolean;
  regionalProductSignTenantId: number;
  regions: RegionKladr[];
  requestDateEnd: string;
  requestDateStart: string;
  selfDeliveryPlace: string;
  sellerCode: string;
  shortOkeiName: string;
  signature: string;
  tags: TagView[];
  truType: TruTypeEnum;
  unitPrice: number;
  unitPriceInCurrency: number;
  usedClassificatorType: UsedClassificatorTypeEnum;
  usedClassificatorTypeDescription: string;
  vatRate: number;
  vatRateDecimal: number;
  vatRateDescription: string;
  vatRateState: VatRateStateEnum;
  vendorCode: string;
  wholesalePercentage: number;
}
