import { CustomerContactInfoAlt } from './customer-contact-info-alt.interface';
import { DealDirectionFlowEnum } from '../enums/deal-direction-flow.enum';
import { DealStateEnum } from '../enums/deal-state.enum';
import { FederalLawLimitAltEnum } from '../enums/federal-law-limit-alt.enum';
import { M4DDealSignRequiredEnum } from '../enums/m-4-d-deal-sign-required.enum';
import { OrderDetail } from './order-detail.interface';
import { OrderDocument } from './order-document.interface';
import { OrderStateEnum } from '../enums/order-state.enum';
import { OrganizationCountryAltEnum } from '../enums/organization-country-alt.enum';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { ViewApplicationsForTrade } from './view-applications-for-trade.interface';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface OrderView {
  applicationId: number;
  applicationSet: ViewApplicationsForTrade;
  businessFlowType: TradeBusinessFlowEnum;
  canSignDeal: boolean;
  cancellationReason: string;
  contactInfo: CustomerContactInfoAlt;
  creatorUserId: number;
  currentCustomerHasDealForThisOrder: boolean;
  currentParticipantHasDealForThisOrder: boolean;
  currentStageId: number;
  customerFullName: string;
  customerId: string;
  customerInn: string;
  customerPhysAddress: string;
  dealConclusionTermInfo: string;
  dealDirectionFlow: DealDirectionFlowEnum;
  dealState: DealStateEnum;
  deliveryPlace: string;
  deliveryTerms: string;
  description: string;
  enableMonetizationMarket: boolean;
  enableMonetizationZmo: boolean;
  externalContractTemplateId: number;
  federalLawLimit: FederalLawLimitAltEnum;
  freeWinnerSelectionEnabled: boolean;
  id: number;
  initialPrice: number;
  isBasedOnPublicOffer: boolean;
  isContractInElectronicForm: boolean;
  isEisConcludeDealRequired: boolean;
  isFederalLawsEnable: boolean;
  isParentContractNumberNotSpecified: boolean;
  isParticipantCanCreateDeal: boolean;
  isSendContractAllowed: boolean;
  lastModificationDate: string;
  lotAuctionId: number;
  lotId: number;
  m4DDealSignRequired: M4DDealSignRequiredEnum;
  orderDetails: OrderDetail[];
  orderDocuments: OrderDocument[];
  orderName: string;
  orderState: OrderStateEnum;
  originTradeId: number;
  parentContractNumber: string;
  parentNotTookPlaceTradeId: number;
  participantComment: string;
  participantFullName: string;
  participantGuid: string;
  participantId: string;
  participantInn: string;
  participantOrganizationCountry: OrganizationCountryAltEnum;
  planedDealSignDate: string;
  publicationDate: string;
  readOnly: boolean;
  regionCode: string;
  tradeIdentificationCode: string;
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFzType: number;
}
