import { AdditionalRequirement } from './additional-requirement.interface';
import { CustomerContactInfoAlt } from './customer-contact-info-alt.interface';
import { DeliveryMethodAltEnum } from '../enums/delivery-method-alt.enum';
import { FederalLawLimitAltEnum } from '../enums/federal-law-limit-alt.enum';
import { OrderDetail } from './order-detail.interface';
import { OrderDocument } from './order-document.interface';
import { OrderStateEnum } from '../enums/order-state.enum';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { TradeExtCustomerInfoExcel } from './trade-ext-customer-info-excel.interface';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface Order {
  additionalRequirements: AdditionalRequirement[];
  businessFlowType: TradeBusinessFlowEnum;
  comment: string;
  contactInfo: CustomerContactInfoAlt;
  creatorUserId: number;
  currencyCode: string;
  customerId: string;
  dealConclusionTermInfo: string;
  deliveryMethod: DeliveryMethodAltEnum;
  deliveryPlace: string;
  deliveryTerms: string;
  description: string;
  externalSystemId: number;
  federalLawLimit: FederalLawLimitAltEnum;
  id: number;
  initialPrice: number;
  isAutoCompleteDeal: boolean;
  isBasedOnPublicOffer: boolean;
  isCartOrder: boolean;
  isContractInElectronicForm: boolean;
  isCustomPrice: boolean;
  isFederalLawsEnable: boolean;
  isParentContractNumberNotSpecified: boolean;
  isParticipantCanCreateDeal: boolean;
  isSanctionedPurchase: boolean;
  isUnitBidding: boolean;
  keepGuaranteeForAllParticipants: boolean;
  keepGuaranteeForParticipantsCount: number;
  lastModificationDate: string;
  maxDealPrice: number;
  orderDetails: OrderDetail[];
  orderDocuments: OrderDocument[];
  orderName: string;
  orderState: OrderStateEnum;
  parentContractNumber: string;
  parentNotTookPlaceTradeId: number;
  participantComment: string;
  participantId: string;
  planedDealSignDate: string;
  possibleSendByTransportCompany: boolean;
  regionCode: string;
  tradeExtCustomerInfo: TradeExtCustomerInfoExcel;
  tradeIdentificationCode: string;
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFzType: number;
}
