import { AvailableVatTypeEnum } from '../enums/available-vat-type.enum';
import { ExternalFieldValueAlt } from './external-field-value-alt.interface';
import { JustificationForNonUseNationalModeTypeEnum } from '../enums/justification-for-non-use-national-mode-type.enum';
import { KtruCharacteristicValues } from './ktru-characteristic-values.interface';
import { NationalModeRequirementTypeEnum } from '../enums/national-mode-requirement-type.enum';
import { Okpd2CodeMarket } from './okpd-2-code-market.interface';
import { TruTypeEnum } from '../enums/tru-type.enum';
import { UsedClassificatorTypeEnum } from '../enums/used-classificator-type.enum';

// @ts-ignore
export interface ProductDto2 {
  classificatorCode: string;
  classificatorDescription: string;
  classificatorType: UsedClassificatorTypeEnum;
  description: string;
  externalFieldValues: ExternalFieldValueAlt[];
  gost: string;
  id: number;
  justificationForNonUseNationalModeAdditionalInfo: string;
  justificationForNonUseNationalModeType: JustificationForNonUseNationalModeTypeEnum;
  ksrCode: string;
  ksrName: string;
  ksrUnit: string;
  ksrUnitQuantity: number;
  ktruCharacteristicValues: KtruCharacteristicValues[];
  ktruCode: string;
  ktruInfo: string;
  ktruName: string;
  ktruSpecification: string;
  ktruVersionNumber: number;
  mark: string;
  name: string;
  nationalModeRequirementType: NationalModeRequirementTypeEnum;
  offerId: number;
  okeiCode: string;
  okeiDescription: string;
  okpd2Codes: Okpd2CodeMarket[];
  okved2Code: string;
  parameters: string;
  positionNumber: number;
  price: number;
  quantity: number;
  shortOkeiName: string;
  sum: number;
  sumWithVat: number;
  type: TruTypeEnum;
  uniqueId: string;
  userDictionaryPositionName: string;
  userDictionaryPositionNumber: string;
  vatRate: AvailableVatTypeEnum;
}
