import { AvailableVatTypeEnum } from '../enums/available-vat-type.enum';
import { ConditionsOfVatAltEnum } from '../enums/conditions-of-vat-alt.enum';
import { ContactInformation } from './contact-information.interface';
import { Document } from './document.interface';
import { Invitation } from './invitation.interface';
import { InvitationMethodEnum } from '../enums/invitation-method.enum';
import { QuotationSessionDetailAlt } from './quotation-session-detail-alt.interface';
import { VatRateStateEnum } from '../enums/vat-rate-state.enum';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface QuotationSessionAlt {
  autoProlongation: number;
  bidStepInfo: string;
  conditionsOfPayment: string;
  conditionsOfVat: ConditionsOfVatAltEnum;
  contactInfo: ContactInformation;
  customerId: number;
  deliveryAddress: string;
  deliveryRegion: string;
  deliveryTerms: string;
  description: string;
  details: QuotationSessionDetailAlt[];
  documents: Document[];
  duration: number;
  endDate: string;
  guid: string;
  id: number;
  initialPrice: number;
  initialPriceWithVat: number;
  initialPriceWithoutVat: number;
  invitationIsAllRegions: boolean;
  invitationMethod: InvitationMethodEnum;
  invitationRegions: string[];
  invitationTags: string[];
  invitations: Invitation[];
  isContractInElectronicForm: boolean;
  isFederalLawsEnable: boolean;
  isManualEnterPriceForEachProduct: boolean;
  isOnlySmp: boolean;
  kladrRegionCodes: string[];
  lotId: number;
  name: string;
  planedDealSignDate: string;
  sumVat: number;
  vatRate: AvailableVatTypeEnum;
  vatRateState: VatRateStateEnum;
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFzType: number;
}
