import { AvailableVatTypeEnum } from '../enums/available-vat-type.enum';
import { ConditionsOfVatAltEnum } from '../enums/conditions-of-vat-alt.enum';
import { DealSignerAlt } from './deal-signer-alt.interface';
import { M4DDealSignRequiredEnum } from '../enums/m-4-d-deal-sign-required.enum';
import { MarketDealStateEnum } from '../enums/market-deal-state.enum';
import { MarketTradePersonAlt } from './market-trade-person-alt.interface';
import { QuotationSessionDeal } from './quotation-session-deal.interface';
import { VatRateStateEnum } from '../enums/vat-rate-state.enum';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface QuotationSessionView {
  autoProlongation: number;
  conditionsOfPayment: string;
  conditionsOfVat: ConditionsOfVatAltEnum;
  contactPerson: MarketTradePersonAlt;
  customerAddress: string;
  customerFullName: string;
  customerGuid: string;
  customerId: number;
  customerRegionName: string;
  deals: QuotationSessionDeal[];
  deliveryTerms: string;
  description: string;
  endDate: string;
  financeSource: ZmoFinanceSourceEnum;
  financeSourceDescription: string;
  fzType: number;
  fzTypeDescription: string;
  fzTypeHint: string;
  fzTypeName: string;
  id: number;
  isContractInElectronicForm: boolean;
  isCustomer: boolean;
  isEisConcludeDealRequired: boolean;
  isOnlySmp: boolean;
  isOrganizer: boolean;
  itemsCount: number;
  lotId: number;
  m4DDealSignRequired: M4DDealSignRequiredEnum;
  maxStepPercent: number;
  minStepPercent: number;
  monetizationMarketWithoutNmz: boolean;
  name: string;
  planedDealSignDate: string;
  price: number;
  priceWithVat: number;
  publicationDate: string;
  rateVat: AvailableVatTypeEnum;
  showProtocol: boolean;
  signer: DealSignerAlt;
  state: MarketDealStateEnum;
  stateDescription: string;
  supplierWithSmallBusinessRequirements: boolean;
  supplierWithUniversalRequirements: boolean;
  vatRateState: VatRateStateEnum;
}
