import { DealStateEnum } from '../enums/deal-state.enum';
import { DeliveryMethodAltEnum } from '../enums/delivery-method-alt.enum';
import { M4DDealSignRequiredEnum } from '../enums/m-4-d-deal-sign-required.enum';
import { MarketDealStateEnum } from '../enums/market-deal-state.enum';
import { SingleSupplierTradeProductAlt } from './single-supplier-trade-product-alt.interface';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';

export interface SingleSupplierTradeView {
  businessFlowType: TradeBusinessFlowEnum;
  customerFullName: string;
  customerGuid: string;
  customerPhysAddress: string;
  dealConclusionTermInfo: string;
  dealId: number;
  dealState: DealStateEnum;
  deliveryKladrRegionName: string;
  deliveryMethod: DeliveryMethodAltEnum;
  deliveryTerms: string;
  fillingApplicationEndDate: string;
  id: number;
  initialPriceWithVat: number;
  initialPriceWithoutVat: number;
  isContractInElectronicForm: boolean;
  isCustomPrice: boolean;
  isCustomer: boolean;
  isOrganizer: boolean;
  isParentContractNumberNotSpecified: boolean;
  isRussianPurchaseObjectHasAdvantage: boolean;
  isSanctionedPurchase: boolean;
  isUnitBidding: boolean;
  lotId: number;
  m4DDealSignRequired: M4DDealSignRequiredEnum;
  marketState: MarketDealStateEnum;
  marketStateDescription: string;
  movingProLink: string;
  parentContractNumber: string;
  parentNotTookPlaceTradeHost: string;
  parentNotTookPlaceTradeId: number;
  participantFullName: string;
  participantGuid: string;
  planedDealSignDate: string;
  products: SingleSupplierTradeProductAlt[];
  publicationDate: string;
  tradeName: string;
  tradeNumber: string;
  zmoFinanceSourceDescription: string;
  zmoFzTypeDescription: string;
  zmoFzTypeName: string;
}
