import { BusinessOperatorIdEnum } from '../enums/business-operator-id.enum';
import { HideApplicationDataForCustomerModeEnum } from '../enums/hide-application-data-for-customer-mode.enum';
import { HideApplicationDataForParticipantModeEnum } from '../enums/hide-application-data-for-participant-mode.enum';
import { HideApplicationDataModeOpenPartEnum } from '../enums/hide-application-data-mode-open-part.enum';
import { MenuCustomItemTemplate } from './menu-custom-item-template.interface';
import { MessageKindAltEnum } from '../enums/message-kind-alt.enum';
import { PositionsImportExcelTemplateTypeEnum } from '../enums/positions-import-excel-template-type.enum';
import { SectionEnum } from '../enums/section.enum';
import { SideFilterStructure } from './side-filter-structure.interface';
import { TenantFlowTypeAltEnum } from '../enums/tenant-flow-type-alt.enum';
import { TenantRegionalProductSignSetting } from './tenant-regional-product-sign-setting.interface';
import { TradeDocumentTypeEnum } from '../enums/trade-document-type.enum';

// @ts-ignore
export interface TenantSetting {
  allowSendToMovingPro: boolean;
  allowUserManagement: boolean;
  availableRegions: string[];
  bannerHtml: string;
  businessOperatorId: BusinessOperatorIdEnum;
  canLinkNotTookPlaceTrade: boolean;
  canLinkNotTookPlaceTradeOnce: boolean;
  commercialOfferFromOpenPartIsEnabled: boolean;
  commercialOfferOwnerGuid: string;
  customCss: string;
  denyTradePriceRaise: boolean;
  enableApplicationsDenyPriceRaise: boolean;
  enableMonetizationMarket: boolean;
  enableRaiseApplicationPriceMoreThanTradePrice: boolean;
  footerHtml: string;
  headerHtml: string;
  headerTitle: string;
  hideApplicationDataForCustomerMode: HideApplicationDataForCustomerModeEnum;
  hideApplicationDataForParticipantMode: HideApplicationDataForParticipantModeEnum;
  hideApplicationDataOpenPartMode: HideApplicationDataModeOpenPartEnum;
  hidedSection: SectionEnum[];
  id: number;
  immediateTradesDisable: boolean;
  importExcelTemplateType: PositionsImportExcelTemplateTypeEnum;
  instructionFileGuid: string;
  isCartEnable: boolean;
  isChangeSingleSupplierTradeToPriceRequest: boolean;
  isClarificationRequestsEnabled: boolean;
  isDealAgreementEnabled: boolean;
  isDealsOutOfEtpEnabled: boolean;
  isGlobalMarket: boolean;
  isImportOffersFromYMLEnabled: boolean;
  isImportPositionsFromExcelEnabled: boolean;
  isLandingEnable: boolean;
  isLandingSwitchEnabled: boolean;
  isManufacturerEnabled: boolean;
  isMyPriceListsEnabled: boolean;
  isNeedTradeApprove: boolean;
  isOfferContentComplaintsEnabled: boolean;
  isOfferModerationEnable: boolean;
  isPassportAuthEnable: boolean;
  isPriceCorridorEnabled: boolean;
  isProposalDocsRequired: boolean;
  isSalesTechAuthEnable: boolean;
  isStarOkServiceEnabled: boolean;
  isStoriesEnabled: boolean;
  isTableEditingModeEnabled: boolean;
  isTelegramEnabled: boolean;
  isZeroSingleSupplierTradeEnabled: boolean;
  landingBannerForCustomerLargeText: string;
  landingBannerForCustomerSmallText: string;
  landingBannerForSupplierLargeText: string;
  landingBannerForSupplierSmallText: string;
  landingMetaDescriptionContent: string;
  landingSchemeColorName: string;
  landingUrl: string;
  landingYandexMetrikaCode: number;
  logoSrc: string;
  mainMenuCustomItems: MenuCustomItemTemplate[];
  maxNmz: number;
  messageKind: MessageKindAltEnum;
  monetizationMarketWithoutNmz: boolean;
  newDealSignFlowForBft: number[];
  ordersSideFilterStructure: SideFilterStructure;
  priceListsSideFilterStructure: SideFilterStructure;
  regionalProductSigns: TenantRegionalProductSignSetting[];
  requiredTradeDocumentTypes: TradeDocumentTypeEnum[];
  showBankingDetailsOnCreateApplicationForm: boolean;
  showTradeCustomerInfo: boolean;
  statisticsAndAnalyticsReportUrl: string;
  tenantFlowType: TenantFlowTypeAltEnum;
  tenantHosts: string[];
  zmoPersonalAccountUrl: string;
}
