import { AdditionalRequirement } from './additional-requirement.interface';
import { Characteristic } from './characteristic.interface';
import { CustomerContactInfoAlt } from './customer-contact-info-alt.interface';
import { DictionaryItemAlt } from './dictionary-item-alt.interface';
import { ExternalFieldValueAlt } from './external-field-value-alt.interface';
import { FederalLawLimitAltEnum } from '../enums/federal-law-limit-alt.enum';
import { Product } from './product.interface';
import { SourcePlatformEnum } from '../enums/source-platform.enum';
import { TradeBiddingTypeEnum } from '../enums/trade-bidding-type.enum';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { TradeDocument } from './trade-document.interface';
import { TradeStateEnum } from '../enums/trade-state.enum';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface Trade {
  additionalInfo: string;
  additionalRequirements: AdditionalRequirement[];
  alwaysSendInvitationsForVendors: boolean;
  autoInvitationVendors: boolean;
  businessFlowType: TradeBusinessFlowEnum;
  characteristicFileGuid: string;
  characteristicFromUi: boolean;
  characteristics: Characteristic[];
  clientTimeZoneMinutesOffset: number;
  conditionsOfPayment: string;
  contactInfo: CustomerContactInfoAlt;
  customerId: number;
  customerOrgFullName: string;
  customerOrganizationId: number;
  customerWorkGroupNames: string[];
  dealDocument: TradeDocument;
  dealExecutionDate: string;
  deliveryPlace: string;
  deliveryTerms: string;
  description: string;
  enableKtruSpecifications: boolean;
  enablePositionCharacteristics: boolean;
  externalContractTemplateId: number;
  externalFieldValues: ExternalFieldValueAlt[];
  externalId: string;
  externalSourcePlatformNumber: string;
  externalSystemId: number;
  federalLawLimit: FederalLawLimitAltEnum;
  fillingApplicationEndDate: string;
  id: number;
  initialPrice: number;
  initialPriceWithVat: number;
  initialPriceWithoutVat: number;
  invitedOrganizationIds: number[];
  isAutoCompleteDeal: boolean;
  isBasedOnPublicOffer: boolean;
  isContractInElectronicForm: boolean;
  isImmediate: boolean;
  isInitialPriceDefined: boolean;
  isLotPriceWithVat: boolean;
  isManualEnterPriceForEachProduct: boolean;
  isOnlySmp: boolean;
  isParentContractNumberNotSpecified: boolean;
  isRussianPurchaseObjectHasAdvantage: boolean;
  isUnitBidding: boolean;
  keepGuaranteeForAllParticipants: boolean;
  keepGuaranteeForParticipantsCount: number;
  kladrRegionCode: string;
  kladrRegionCodes: DictionaryItemAlt[];
  lastModificationDate: string;
  lotItemsSumPrice: number;
  maxDealPrice: number;
  minFillingApplicationEndDateForImmediate: string;
  organizerId: number;
  parentContractNumber: string;
  planNumber: string;
  planPositionNumber: string;
  planedDealSignDate: string;
  products: Product[];
  regulationDocumentUrl: string;
  resultsDeliveryType: number;
  rowVersion: number;
  sourcePlatform: SourcePlatformEnum;
  supplierWithSmallBusinessRequirements: boolean;
  supplierWithUniversalRequirements: boolean;
  tradeBiddingType: TradeBiddingTypeEnum;
  tradeDocuments: TradeDocument[];
  tradeFiles: TradeDocument[];
  tradeIdentificationCode: string;
  tradeName: string;
  tradeState: TradeStateEnum;
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFzType: number;
}
