import { AdditionalRequirementDto2 } from './additional-requirement-dto-2.interface';
import { AvailableVatTypeEnum } from '../enums/available-vat-type.enum';
import { Characteristic } from './characteristic.interface';
import { CustomerContactInfoAlt } from './customer-contact-info-alt.interface';
import { DictionaryItemAlt } from './dictionary-item-alt.interface';
import { EisIntegrationDataAlt } from './eis-integration-data-alt.interface';
import { EisTradeInfoAlt } from './eis-trade-info-alt.interface';
import { ExternalFieldValueAlt } from './external-field-value-alt.interface';
import { FederalLawLimitAltEnum } from '../enums/federal-law-limit-alt.enum';
import { FillingApplicationMinimumDateCountdownEnum } from '../enums/filling-application-minimum-date-countdown.enum';
import { Invitation } from './invitation.interface';
import { InvitationMethodEnum } from '../enums/invitation-method.enum';
import { ProductDto2 } from './product-dto-2.interface';
import { SourcePlatformEnum } from '../enums/source-platform.enum';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { TradeDocument } from './trade-document.interface';
import { TradeLotSpecification } from './trade-lot-specification.interface';
import { TradeStateEnum } from '../enums/trade-state.enum';
import { VatRateStateEnum } from '../enums/vat-rate-state.enum';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface TradeDto2 {
  additionalInfo: string;
  additionalRequirements: AdditionalRequirementDto2[];
  businessFlowType: TradeBusinessFlowEnum;
  characteristicFileGuid: string;
  characteristicFromUi: boolean;
  characteristics: Characteristic[];
  clientTimeZoneMinutesOffset: number;
  conditionsOfPayment: string;
  contactInfo: CustomerContactInfoAlt;
  contractAmountInfo: string;
  creatorUserId: number;
  currencyCode: string;
  customerId: number;
  customerOrgFullName: string;
  customerOrganizationId: number;
  customerOrganizationInn: string;
  customerOrganizationKpp: string;
  customerWorkGroupNames: string[];
  dealConclusionTermInfo: string;
  dealExecutionDate: string;
  deliveryPlace: string;
  deliveryTerms: string;
  description: string;
  eisIntegrationData: EisIntegrationDataAlt;
  eisTradeInfo: EisTradeInfoAlt;
  externalFieldValues: ExternalFieldValueAlt[];
  externalId: string;
  externalSourcePlatformNumber: string;
  externalSystemId: number;
  federalLawLimit: FederalLawLimitAltEnum;
  fillingApplicationEndDate: string;
  fillingApplicationMinimumDateCountdown: FillingApplicationMinimumDateCountdownEnum;
  fillingApplicationsMinDays: number;
  hasUncompletedEisOutgoingSaga: boolean;
  id: number;
  initialPrice: number;
  initialPriceWithVat: number;
  initialPriceWithoutVat: number;
  invitationIsAllRegions: boolean;
  invitationMethod: InvitationMethodEnum;
  invitationRegions: string[];
  invitationTags: string[];
  invitations: Invitation[];
  invitedOrganizationIds: number[];
  isAutoCompleteDeal: boolean;
  isBasedOnPublicOffer: boolean;
  isContractInElectronicForm: boolean;
  isCustomerAcceptByOkeiOffers: boolean;
  isCustomerAcceptOnlyTop5Offers: boolean;
  isDifferenceProtocolSendOnce: boolean;
  isFederalLawsEnable: boolean;
  isImmediate: boolean;
  isImportPhaseout: boolean;
  isInitialPriceDefined: boolean;
  isInitialPriceReduction: boolean;
  isLotPriceEnteredWithVAT: boolean;
  isLotPriceWithVat: boolean;
  isManualEnterPriceForEachProduct: boolean;
  isModificationSentToOos: boolean;
  isOnlySmp: boolean;
  isParentContractNumberNotSpecified: boolean;
  isPositionalVatEnable: boolean;
  isPriceCorridorUsed: boolean;
  isRetradingEnabled: boolean;
  isRussianPurchaseObjectHasAdvantage: boolean;
  isSanctionedPurchase: boolean;
  isSendToEis: boolean;
  isSingleWinner: boolean;
  isUnitBidding: boolean;
  keepGuaranteeForAllParticipants: boolean;
  keepGuaranteeForParticipantsCount: number;
  kladrRegionCode: string;
  kladrRegionCodes: DictionaryItemAlt[];
  lastModificationDate: string;
  lotItemsSumPrice: number;
  maxDealPrice: number;
  maxDealPriceSumVat: number;
  maxDealPriceWithVat: number;
  maxDealPriceWithoutVat: number;
  modificationInfo: string;
  offerId: number;
  organizerId: number;
  parentContractNumber: string;
  parentNotTookPlaceTradeId: number;
  planId: number;
  planNumber: string;
  planPositionNumber: string;
  planStartingPrice: number;
  planStartingPriceWithoutVat: number;
  planedDealSignDate: string;
  products: ProductDto2[];
  rateVat: AvailableVatTypeEnum;
  rowVersion: number;
  selectOffersOnlyFromProposedBySuppliers: boolean;
  sourcePlatform: SourcePlatformEnum;
  specifications: TradeLotSpecification[];
  supplierWithSmallBusinessRequirements: boolean;
  tenantKey: number;
  tradeDocuments: TradeDocument[];
  tradeIdentificationCode: string;
  tradeLotIds: number[];
  tradeName: string;
  tradeState: TradeStateEnum;
  vatRateState: VatRateStateEnum;
  workGroupIds: number[];
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFzType: number;
}
