import { AdditionalRequirement } from './additional-requirement.interface';
import { CustomerContactInfoAlt } from './customer-contact-info-alt.interface';
import { DealStateEnum } from '../enums/deal-state.enum';
import { Document } from './document.interface';
import { M4DDealSignRequiredEnum } from '../enums/m-4-d-deal-sign-required.enum';
import { Product } from './product.interface';
import { SourcePlatformEnum } from '../enums/source-platform.enum';
import { StateOfIncreasingForFillingApplicationEndDateAltEnum } from '../enums/state-of-increasing-for-filling-application-end-date-alt.enum';
import { SuppliersListReportResult } from './suppliers-list-report-result.interface';
import { TradeBusinessFlowEnum } from '../enums/trade-business-flow.enum';
import { TradeGroupView } from './trade-group-view.interface';
import { TradeStateEnum } from '../enums/trade-state.enum';
import { ViewApplicationsForTrade } from './view-applications-for-trade.interface';
import { ZmoFinanceSourceEnum } from '../enums/zmo-finance-source.enum';

export interface TradeView {
  actualChildOrderId: number;
  actualChildTradeId: number;
  additionalInfo: string;
  additionalRequirements: AdditionalRequirement[];
  applicationSet: ViewApplicationsForTrade;
  autoInvitationVendors: boolean;
  canBeShownOnZmo: boolean;
  canCheckParticipant: boolean;
  canDownloadApplicationsData: boolean;
  canManageApplications: boolean;
  canPossibleCreateDealOutsideEShop: boolean;
  cancellationReason: string;
  concludeReviewApplication: boolean;
  conditionsOfPayment: string;
  contactInfo: CustomerContactInfoAlt;
  currentCustomerHasDealForThisTrade: boolean;
  currentParticipantHasDealForThisTrade: boolean;
  currentStageId: number;
  customerFullName: string;
  customerId: number;
  customerInn: string;
  customerPhysAddress: string;
  dealExecutionDate: string;
  dealState: DealStateEnum;
  defaultPriceForSignDealOutSide: number;
  deliveryKladrRegionCode: string;
  deliveryKladrRegionName: string;
  deliveryPlace: string;
  deliveryTerms: string;
  description: string;
  enableKtruCode: boolean;
  enableKtruSpecifications: boolean;
  enableMonetizationZmo: boolean;
  enablePositionCharacteristics: boolean;
  externalContractTemplateId: number;
  externalSourcePlatformNumber: string;
  externalSystemId: number;
  fillingApplicationEndDate: string;
  freeWinnerSelectionEnabled: boolean;
  hasDealSignedOutsideEShop: boolean;
  id: number;
  initialPrice: number;
  isCustomerAcceptOnlyManualOffers: boolean;
  isEisConcludeDealRequired: boolean;
  isHideParticipantPrice: boolean;
  isHideParticipantsApplications: boolean;
  isImmediate: boolean;
  isInitialPriceDefined: boolean;
  isLapsed: boolean;
  isOnlySmp: boolean;
  isOrderCreationFromExternalNotTookPlaceTradeAvailable: boolean;
  isParentContractNumberNotSpecified: boolean;
  isSendContractAllowed: boolean;
  isSendToNonPublicEis: boolean;
  isTradeForPartner: boolean;
  isTradeNeedConfirmCustomerTermsWhenOffer: boolean;
  isUnitBidding: boolean;
  isWaitingPeriodEnabled: boolean;
  lastModificationDate: string;
  lotAuctionId: number;
  lotId: number;
  lotItemsSumPrice: number;
  m4DDealSignRequired: M4DDealSignRequiredEnum;
  maxDealPrice: number;
  organizerId: number;
  organizerInn: string;
  organizerName: string;
  organizerPhysAddress: string;
  originTradeId: number;
  parentContractNumber: string;
  participantCanCreateApplication: boolean;
  paymentByBankCardEnable: boolean;
  planedDealSignDate: string;
  priceWithVat: boolean;
  products: Product[];
  prohibitPostingCustomerComissionProtocol: boolean;
  publicationDate: string;
  readOnly: boolean;
  redirectOn223Url: string;
  relatedOrderId: number;
  resultsDeliveryType: number;
  russianPurchaseAdvantageInfo: string;
  showProtocol: boolean;
  sourcePlatform: SourcePlatformEnum;
  stateOfIncreasing: StateOfIncreasingForFillingApplicationEndDateAltEnum;
  supplierWithSmallBusinessRequirements: boolean;
  supplierWithUniversalRequirements: boolean;
  suppliersListReportResult: SuppliersListReportResult;
  tenantId: number;
  tradeBusinessFlow: TradeBusinessFlowEnum;
  tradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz: boolean;
  tradeDocuments: Document[];
  tradeGroups: TradeGroupView[];
  tradeIdentificationCode: string;
  tradeName: string;
  tradeState: TradeStateEnum;
  tradeWaitingTime: number;
  zmoFinanceSource: ZmoFinanceSourceEnum;
  zmoFzType: number;
}
