/* tslint:disable */
/* eslint-disable */
import { ApiAdditionalRequirementDto } from '../models/api-additional-requirement-dto';
import { ApiCustomerContactInfoAltDto } from '../models/api-customer-contact-info';
import { ApiDealStateEnum } from '../models/api-deal-state-enum';
import { ApiDocumentDto } from '../models/api-document-dto';
import { ApiM4DDealSignRequiredEnum } from '../models/api-m-4-d-deal-sign-required-enum';
import { ApiProductDto } from '../models/api-product-dto';
import { ApiSourcePlatformEnum } from '../models/api-source-platform-enum';
import { ApiStateOfIncreasingForFillingApplicationEndDateAltEnum } from '../models/api-state-of-increasing-for-filling-application-end-date';
import { ApiSuppliersListReportResultDto } from '../models/api-suppliers-list-report-result-dto';
import { ApiTradeBusinessFlowEnum } from '../models/api-trade-business-flow-enum';
import { ApiTradeGroupViewDto } from '../models/api-trade-group-view-dto';
import { ApiTradeStateEnum } from '../models/api-trade-state-enum';
import { ApiViewApplicationsForTradeDto } from '../models/api-view-applications-for-trade-dto';
import { ApiZmoFinanceSourceEnum } from '../models/api-zmo-finance-source-enum';
export interface ApiTradeViewDto {
  ActualChildOrderId?: number | null;
  ActualChildTradeId?: number | null;
  AdditionalInfo?: string | null;
  AdditionalRequirements?: Array<ApiAdditionalRequirementDto> | null;
  ApplicationSet?: ApiViewApplicationsForTradeDto | null;
  AutoInvitationVendors?: boolean;
  CanBeShownOnZmo?: boolean;
  CanCheckParticipant?: boolean;
  CanDownloadApplicationsData?: boolean;
  CanManageApplications?: boolean;
  CanPossibleCreateDealOutsideEShop?: boolean;
  CancellationReason?: string | null;
  ConcludeReviewApplication?: boolean;
  ConditionsOfPayment?: string | null;
  ContactInfo?: ApiCustomerContactInfoAltDto | null;
  CurrentCustomerHasDealForThisTrade?: boolean;
  CurrentParticipantHasDealForThisTrade?: boolean;
  CurrentStageId?: number;
  CustomerFullName?: string | null;
  CustomerId?: number;
  CustomerInn?: string | null;
  CustomerPhysAddress?: string | null;
  DealExecutionDate?: string | null;
  DealState?: ApiDealStateEnum | null;
  DefaultPriceForSignDealOutSide?: number | null;
  DeliveryKladrRegionCode?: string | null;
  DeliveryKladrRegionName?: string | null;
  DeliveryPlace?: string | null;
  DeliveryTerms?: string | null;
  Description?: string | null;
  EnableKtruCode?: boolean;
  EnableKtruSpecifications?: boolean;
  EnableMonetizationZmo?: boolean;
  EnablePositionCharacteristics?: boolean;
  ExternalContractTemplateId?: number | null;
  ExternalSourcePlatformNumber?: string | null;
  ExternalSystemId?: number | null;
  FillingApplicationEndDate?: string | null;
  FreeWinnerSelectionEnabled?: boolean;
  HasDealSignedOutsideEShop?: boolean;
  Id?: number;
  InitialPrice?: number | null;
  IsCustomerAcceptOnlyManualOffers?: boolean;
  IsEisConcludeDealRequired?: boolean;
  IsHideParticipantPrice?: boolean;
  IsHideParticipantsApplications?: boolean;
  IsImmediate?: boolean;
  IsInitialPriceDefined?: boolean;
  IsLapsed?: boolean;
  IsOnlySmp?: boolean;
  IsOrderCreationFromExternalNotTookPlaceTradeAvailable?: boolean;
  IsParentContractNumberNotSpecified?: boolean | null;
  IsSendContractAllowed?: boolean;
  IsSendToNonPublicEis?: boolean;
  IsTradeForPartner?: boolean;
  IsTradeNeedConfirmCustomerTermsWhenOffer?: boolean;
  IsUnitBidding?: boolean;
  IsWaitingPeriodEnabled?: boolean;
  LastModificationDate?: string | null;
  LotAuctionId?: number | null;
  LotId?: number;
  LotItemsSumPrice?: number | null;
  M4DDealSignRequired?: ApiM4DDealSignRequiredEnum;
  MaxDealPrice?: number | null;
  OrganizerId?: number;
  OrganizerInn?: string | null;
  OrganizerName?: string | null;
  OrganizerPhysAddress?: string | null;
  OriginTradeId?: number | null;
  ParentContractNumber?: string | null;
  ParticipantCanCreateApplication?: boolean;
  PaymentByBankCardEnable?: boolean;
  PlanedDealSignDate?: string | null;
  PriceWithVat?: boolean;
  Products?: Array<ApiProductDto> | null;
  ProhibitPostingCustomerComissionProtocol?: boolean;
  PublicationDate?: string | null;
  ReadOnly?: boolean;
  RedirectOn223Url?: string | null;
  RelatedOrderId?: number | null;
  ResultsDeliveryType?: number | null;
  RussianPurchaseAdvantageInfo?: string | null;
  ShowProtocol?: boolean;
  SourcePlatform?: ApiSourcePlatformEnum;
  StateOfIncreasing?: ApiStateOfIncreasingForFillingApplicationEndDateAltEnum;
  SupplierWithSmallBusinessRequirements?: boolean;
  SupplierWithUniversalRequirements?: boolean;
  SuppliersListReportResult?: ApiSuppliersListReportResultDto | null;
  TenantId?: number;
  TradeBusinessFlow?: ApiTradeBusinessFlowEnum;
  TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz?: boolean;
  TradeDocuments?: Array<ApiDocumentDto> | null;
  TradeGroups?: Array<ApiTradeGroupViewDto> | null;
  TradeIdentificationCode?: string | null;
  TradeName?: string | null;
  TradeState?: ApiTradeStateEnum;
  TradeWaitingTime?: number;
  ZmoFinanceSource?: ApiZmoFinanceSourceEnum | null;
  ZmoFzType?: number | null;
}
