/* tslint:disable */
/* eslint-disable */
import { ApiB2BCategoryDto } from '../models/api-b-2-b-category-dto';
import { ApiCharacteristicDto } from '../models/api-characteristic-dto';
import { ApiCharacteristicValuesDto } from '../models/api-characteristic-values-dto';
import { ApiCountryDto } from '../models/api-country-dto';
import { ApiDeliveryRegionInfoDto } from '../models/api-delivery-region-info-dto';
import { ApiDisplayCharacteristicDto } from '../models/api-display-characteristic-dto';
import { ApiManufacturerCountryRegistryTypeEnum } from '../models/api-manufacturer-country-registry-type-enum';
import { ApiOfferCreatedMethodEnum } from '../models/api-offer-created-method-enum';
import { ApiOkpd2MarketDto } from '../models/api-okpd-2-market-dto';
import { ApiOrganizationCountryAltEnum } from '../models/api-organization-country';
import { ApiParticipantOfferActionsDto } from '../models/api-participant-offer-actions-dto';
import { ApiParticipantOfferDocumentDto } from '../models/api-participant-offer-document-dto';
import { ApiParticipantOfferSourceEnum } from '../models/api-participant-offer-source-enum';
import { ApiParticipantOfferSpecificFlagEnum } from '../models/api-participant-offer-specific-flag-enum';
import { ApiParticipantOfferStateEnum } from '../models/api-participant-offer-state-enum';
import { ApiParticipantOfferTypeEnum } from '../models/api-participant-offer-type-enum';
import { ApiPriceListStateEnum } from '../models/api-price-list-state-enum';
import { ApiPriceListTypeEnum } from '../models/api-price-list-type-enum';
import { ApiPriceRegionDetailDto } from '../models/api-price-region-detail-dto';
import { ApiRegionKladrDto } from '../models/api-region-kladr-dto';
import { ApiTagViewDto } from '../models/api-tag-view-dto';
import { ApiTruTypeEnum } from '../models/api-tru-type-enum';
import { ApiUsedClassificatorTypeEnum } from '../models/api-used-classificator-type-enum';
import { ApiVatRateStateEnum } from '../models/api-vat-rate-state-enum';
import { ApiYmlParamDto } from '../models/api-yml-param-dto';
export interface ApiMarketParticipantOfferInfoDto {
  Actions?: ApiParticipantOfferActionsDto | null;
  BarCode?: string | null;
  Category?: ApiB2BCategoryDto | null;
  /** @deprecated */CharacteristicValues?: Array<ApiCharacteristicValuesDto> | null;
  Characteristics?: Array<ApiCharacteristicDto> | null;
  ClassificatorCode?: string | null;
  ClassificatorDescription?: string | null;
  Country?: ApiCountryDto | null;
  CountryCode?: string | null;
  CountryOfOrigin?: string | null;
  CreatedMethod?: ApiOfferCreatedMethodEnum;
  CurrencyCode?: string | null;
  DeliveryCost?: number | null;
  DeliveryPlace?: string | null;
  DeliveryRegionInfos?: Array<ApiDeliveryRegionInfoDto> | null;
  DeliveryRegions?: string | null;
  DeliveryTerms?: string | null;
  DisplayCharacteristics?: Array<ApiDisplayCharacteristicDto> | null;
  DosageForm?: string | null;
  DosageMeasureUnits?: string | null;
  DrugDosage?: string | null;
  DuringDays?: number | null;
  ExclusiveToTradeId?: number | null;
  ExclusiveToTradeNumber?: string | null;
  ExternalSystemIdentifier?: string | null;
  ExternalSystemIdentifierNumeric?: number | null;
  Id?: number;
  IsFromGuarnteeSupplier?: boolean;
  IsOwner?: boolean;
  IsParticipatesInRequirementRequests?: boolean;
  IsPhysicalPerson?: boolean;
  IsPublicOffer?: boolean;
  KsrCode?: string | null;
  KsrName?: string | null;
  KsrUnit?: string | null;
  Manufacturer?: string | null;
  ManufacturerCountryRegistryNumber?: string | null;
  ManufacturerCountryRegistryType?: ApiManufacturerCountryRegistryTypeEnum | null;
  ManufacturerCountryScore?: number | null;
  MovingProLink?: string | null;
  OfferOwner?: boolean;
  OfferState?: ApiParticipantOfferStateEnum;
  OfferStateDescription?: string | null;
  OfferTerms?: string | null;
  OfferType?: ApiParticipantOfferTypeEnum;
  OfferTypeDescription?: string | null;
  OkeiCode?: string | null;
  OkeiDescription?: string | null;
  Okpd2Values?: Array<ApiOkpd2MarketDto> | null;
  Params?: Array<ApiYmlParamDto> | null;
  ParticipantCountry?: ApiOrganizationCountryAltEnum;
  ParticipantForeignId?: string | null;
  ParticipantGuid?: string;
  ParticipantId?: number;
  ParticipantInn?: string | null;
  ParticipantKpp?: string | null;
  ParticipantName?: string | null;
  ParticipantOfferDocuments?: Array<ApiParticipantOfferDocumentDto> | null;
  ParticipantOfferSource?: ApiParticipantOfferSourceEnum;
  ParticipantOfferSpecific?: ApiParticipantOfferSpecificFlagEnum | null;
  ParticipantSource?: number | null;
  PossibleDeliveryBySeller?: boolean;
  PossibleSelfDelivery?: boolean | null;
  PossibleSendByTransportCompany?: boolean;
  PriceListDeliveryRegionInfos?: Array<ApiDeliveryRegionInfoDto> | null;
  PriceListId?: number | null;
  PriceListState?: ApiPriceListStateEnum;
  PriceListType?: ApiPriceListTypeEnum;
  PriceRegionDetails?: Array<ApiPriceRegionDetailDto> | null;
  PrintFormFileName?: string | null;
  PrintFormGuid?: string | null;
  Producer?: string | null;
  ProductDescription?: string | null;
  ProductMNN?: string | null;
  ProductName?: string | null;
  PublishDate?: string | null;
  PublishDateStart?: string | null;
  RecipientOrganizationInn?: string | null;
  RecipientOrganizationKpp?: string | null;
  RecipientOrganizationName?: string | null;
  RegionalProductSignCanEdit?: boolean;
  RegionalProductSignChecked?: boolean;
  RegionalProductSignTenantId?: number | null;
  Regions?: Array<ApiRegionKladrDto> | null;
  RequestDateEnd?: string | null;
  RequestDateStart?: string | null;
  SelfDeliveryPlace?: string | null;
  SellerCode?: string | null;
  ShortOkeiName?: string | null;
  Signature?: string | null;
  Tags?: Array<ApiTagViewDto> | null;
  TruType?: ApiTruTypeEnum | null;
  UnitPrice?: number | null;
  UnitPriceInCurrency?: number | null;
  UsedClassificatorType?: ApiUsedClassificatorTypeEnum | null;
  UsedClassificatorTypeDescription?: string | null;
  VatRate?: number | null;
  VatRateDecimal?: number | null;
  VatRateDescription?: string | null;
  VatRateState?: ApiVatRateStateEnum;
  VendorCode?: string | null;
  WholesalePercentage?: number | null;
}
