/* tslint:disable */
/* eslint-disable */
import { ApiAdditionalRequirementDto2 } from '../models/api-additional-requirement-dto-2';
import { ApiApplicationParametersDto } from '../models/api-application-parameters-dto';
import { ApiApplicationStateEnum } from '../models/api-application-state-enum';
import { ApiAvailableVatTypeEnum } from '../models/api-available-vat-type-enum';
import { ApiDealSignerAltDto } from '../models/api-deal-signer';
import { ApiDealStateEnum } from '../models/api-deal-state-enum';
import { ApiDeliveryMethodAltEnum } from '../models/api-delivery-method';
import { ApiDictionaryItemAltDto } from '../models/api-dictionary-item';
import { ApiEisIntegrationDataAltDto } from '../models/api-eis-integration-data';
import { ApiEisTradeInfoAltDto } from '../models/api-eis-trade-info';
import { ApiFederalLawLimitAltEnum } from '../models/api-federal-law-limit';
import { ApiLotStateEnum } from '../models/api-lot-state-enum';
import { ApiM4DDealSignRequiredEnum } from '../models/api-m-4-d-deal-sign-required-enum';
import { ApiMarketDealStateEnum } from '../models/api-market-deal-state-enum';
import { ApiMarketEntityTypeAltEnum } from '../models/api-market-entity-type';
import { ApiMarketTradeDealAltDto } from '../models/api-market-trade-deal';
import { ApiMarketTradePersonAltDto } from '../models/api-market-trade-person';
import { ApiMarketTradeProductAltDto } from '../models/api-market-trade-product';
import { ApiMeetsRequirementsEnum } from '../models/api-meets-requirements-enum';
import { ApiMyTermsAltDto } from '../models/api-my-terms';
import { ApiOrderStateEnum } from '../models/api-order-state-enum';
import { ApiPriceCorridorDto } from '../models/api-price-corridor-dto';
import { ApiPurchaseMethodTypeEnum } from '../models/api-purchase-method-type-enum';
import { ApiRegulationInfoDto } from '../models/api-regulation-info-dto';
import { ApiRetradingTypeEnum } from '../models/api-retrading-type-enum';
import { ApiShortTenantSettingAltDto } from '../models/api-short-tenant-setting';
import { ApiTradeBusinessFlowEnum } from '../models/api-trade-business-flow-enum';
import { ApiTradeLotSpecificationDto } from '../models/api-trade-lot-specification-dto';
import { ApiTradeStateEnum } from '../models/api-trade-state-enum';
import { ApiTradeViewFormOptionsDto } from '../models/api-trade-view-form-options-dto';
import { ApiVatRateStateEnum } from '../models/api-vat-rate-state-enum';
import { ApiZmoFinanceSourceEnum } from '../models/api-zmo-finance-source-enum';
export interface ApiMarketTradeViewDto {
  AdditionalRequirements?: Array<ApiAdditionalRequirementDto2> | null;
  AllowApplicationReject?: boolean;
  ApplicationId?: number | null;
  ApplicationParameters?: ApiApplicationParametersDto | null;
  ApplicationState?: ApiApplicationStateEnum | null;
  BusinessFlowType?: ApiTradeBusinessFlowEnum;
  /** @deprecated */CanSuggestPaperFormSigning?: boolean;
  ChildTradeBusinessFlowType?: ApiTradeBusinessFlowEnum | null;
  ChildTradeHosts?: Array<string> | null;
  ChildTradeId?: number | null;
  ConditionsOfPayment?: string | null;
  ContactPerson?: ApiMarketTradePersonAltDto | null;
  ContractAmountInfo?: string | null;
  CurrencyCode?: string | null;
  CurrentStageId?: number;
  CustomerExternalOrganizationId?: string | null;
  CustomerFullName?: string | null;
  CustomerGuid?: string;
  CustomerId?: number;
  CustomerPhysAddress?: string | null;
  CustomerSource?: number | null;
  /** @deprecated */DealBelongToCurrentOrg?: boolean;
  DealConclusionTermInfo?: string | null;
  DealDirectionFlow?: number;
  DealExecutionDate?: string | null;
  /** @deprecated */DealId?: number | null;
  /** @deprecated */DealState?: ApiDealStateEnum | null;
  Deals?: Array<ApiMarketTradeDealAltDto> | null;
  DeliveryKladrRegionCode?: string | null;
  DeliveryKladrRegionCodes?: Array<ApiDictionaryItemAltDto> | null;
  DeliveryKladrRegionName?: string | null;
  DeliveryMethod?: ApiDeliveryMethodAltEnum;
  DeliveryTerms?: string | null;
  Description?: string | null;
  DisplayApproveBtn?: boolean;
  DisplayDealDontConcludeBtn?: boolean;
  EisIntegrationData?: ApiEisIntegrationDataAltDto | null;
  EisTradeInfo?: ApiEisTradeInfoAltDto | null;
  EnableKtruSpecifications?: boolean;
  EnableMonetizationMarket?: boolean;
  EnablePositionCharacteristics?: boolean;
  EntityType?: ApiMarketEntityTypeAltEnum;
  ExternalId?: string | null;
  ExternalSystemId?: number | null;
  FederalLawLimit?: ApiFederalLawLimitAltEnum | null;
  FillingApplicationEndDate?: string | null;
  /** @deprecated */HasDealFile?: boolean;
  HasManualParticipantOfferToTrade?: boolean | null;
  HasUncompletedEisOutgoingSaga?: boolean;
  Hosts?: Array<string> | null;
  Id?: number;
  InitialPriceWithVat?: number | null;
  InitialPriceWithoutVat?: number | null;
  InitialTenantSetting?: ApiShortTenantSettingAltDto | null;
  IsApprovalRequestExists?: boolean;
  IsAutoCreateDealAfterReviewApplications?: boolean;
  IsAvailableSelectOnlyOneOfferForItem?: boolean;
  IsBy223Fz?: boolean;
  IsBy44Fz?: boolean;
  /** @deprecated */IsContractInElectronicForm?: boolean | null;
  /** @deprecated */IsCustomPrice?: boolean | null;
  IsCustomer?: boolean;
  IsCustomerAcceptByOkeiOffers?: boolean;
  IsCustomerAcceptOnlyManualOffers?: boolean | null;
  /** @deprecated */IsDealSigningExpired?: boolean;
  IsEditable?: boolean;
  IsEisConcludeDealRequired?: boolean;
  IsEisTradeAccelerated?: boolean;
  IsFederalLawsEnable?: boolean;
  IsHiddenContract?: boolean;
  IsImmediate?: boolean;
  IsImportPhaseout?: boolean | null;
  IsInEisWasChanged?: boolean;
  IsInitialPriceDefined?: boolean;
  IsInitialPriceReduction?: boolean;
  IsLapsed?: boolean;
  IsLotPriceEnteredWithVAT?: boolean;
  IsLotPriceWithVat?: boolean;
  IsModificationSentToOos?: boolean;
  IsOnlySmp?: boolean;
  IsOrganizer?: boolean;
  IsParentContractNumberNotSpecified?: boolean | null;
  IsPositionalVatEnable?: boolean;
  IsPrivate?: boolean;
  IsRetradingEnabled?: boolean;
  IsRussianPurchaseObjectHasAdvantage?: boolean;
  IsSanctionedPurchase?: boolean | null;
  IsSendToEis?: boolean;
  IsSingleWinner?: boolean | null;
  IsSmallBusinessEntity?: boolean;
  IsSortApplicationsByPriceWithoutVat?: boolean;
  IsTradeNeedConfirmCustomerTermsWhenOffer?: boolean;
  IsUnitBidding?: boolean;
  ItemsCount?: number;
  LotAuctionId?: number | null;
  LotId?: number;
  LotItemsSumPrice?: number | null;
  M4DDealSignRequired?: ApiM4DDealSignRequiredEnum;
  MarketState?: ApiMarketDealStateEnum;
  MarketStateDescription?: string | null;
  MaxDealPriceWithVat?: number | null;
  MaxDealPriceWithoutVat?: number | null;
  MeetsRequirements?: ApiMeetsRequirementsEnum | null;
  MovingProLink?: string | null;
  NeedBlockMoney?: boolean;
  OfferId?: number | null;
  /** @deprecated */OfferTerms?: ApiMyTermsAltDto | null;
  OnlyOneRetradingBidAllowed?: boolean;
  OrderState?: ApiOrderStateEnum;
  OrganizerExternalOrganizationId?: string | null;
  OrganizerFullName?: string | null;
  OrganizerGuid?: string;
  OrganizerId?: number;
  OrganizerSource?: number | null;
  Original223TradeLotState?: ApiLotStateEnum;
  ParentContractNumber?: string | null;
  ParentNotTookPlaceTradeBusinessFlowType?: ApiTradeBusinessFlowEnum | null;
  ParentNotTookPlaceTradeHosts?: Array<string> | null;
  ParentNotTookPlaceTradeId?: number | null;
  ParticipantExternalOrganizationId?: string | null;
  /** @deprecated */ParticipantFullName?: string | null;
  ParticipantGuid?: string;
  ParticipantId?: number;
  ParticipantSource?: number | null;
  PictureGuids?: Array<string> | null;
  PlanNumber?: string | null;
  PlanPositionNumber?: string | null;
  PlanedDealSignDate?: string | null;
  PossibleSelfDelivery?: boolean | null;
  PossibleSendByTransportCompany?: boolean | null;
  Price?: number;
  PriceCorridor?: ApiPriceCorridorDto | null;
  PriceWithVat?: boolean | null;
  Products?: Array<ApiMarketTradeProductAltDto> | null;
  ProhibitPostingCustomerComissionProtocol?: boolean | null;
  ProtocolReadyToPublish?: boolean;
  PublicationDate?: string | null;
  PurchaseMethodType?: ApiPurchaseMethodTypeEnum;
  RateVat?: ApiAvailableVatTypeEnum;
  RegulationInfo?: ApiRegulationInfoDto | null;
  RequiredSupplierRegistration?: boolean;
  RequirementsInfo?: string | null;
  RetradingBidLeftCount?: number | null;
  RetradingEndDate?: string | null;
  RetradingStartDate?: string | null;
  RetradingType?: ApiRetradingTypeEnum | null;
  RussianPurchaseAdvantageInfo?: string | null;
  ShowProtocol?: boolean;
  ShowProtocolDocument?: boolean;
  Signer?: ApiDealSignerAltDto | null;
  Specifications?: Array<ApiTradeLotSpecificationDto> | null;
  SupplierWithSmallBusinessRequirements?: boolean;
  SupplierWithUniversalRequirements?: boolean;
  Tags?: Array<string> | null;
  TenantId?: number;
  TradeName?: string | null;
  TradeNumber?: string | null;
  TradeState?: ApiTradeStateEnum;
  TradeSum?: number | null;
  TradeViewFormOptions?: ApiTradeViewFormOptionsDto | null;
  /** @deprecated */VatRate?: number | null;
  /** @deprecated */VatRateDescription?: string | null;
  /** @deprecated */VatRateState?: ApiVatRateStateEnum;
  /** @deprecated */WinnerTradeLotApplicationId?: number | null;
  WorkGroupIds?: Array<number> | null;
  ZmoFinanceSource?: ApiZmoFinanceSourceEnum | null;
  ZmoFinanceSourceDescription?: string | null;
  ZmoFzType?: number | null;
  ZmoFzTypeDescription?: string | null;
  ZmoFzTypeHint?: string | null;
  ZmoFzTypeName?: string | null;
}
