import { ApiDiscussionItemTypeEnum } from '../../../swagger/models/api-discussion-item-type-enum';
import { DiscussionItemTypeEnum } from '../../enums/discussion-item-type.enum';

export function adaptDiscussionItemTypeEnumToUI(source?: ApiDiscussionItemTypeEnum | null): DiscussionItemTypeEnum {
  switch (source) {
    case ApiDiscussionItemTypeEnum.Deal:
      return DiscussionItemTypeEnum.Deal;
    case ApiDiscussionItemTypeEnum.Text:
      return DiscussionItemTypeEnum.Text;
    case ApiDiscussionItemTypeEnum.Contract:
      return DiscussionItemTypeEnum.Contract;
    case ApiDiscussionItemTypeEnum.TextWithFiles:
      return DiscussionItemTypeEnum.TextWithFiles;
    case ApiDiscussionItemTypeEnum.DealSystemSuccessMessage:
      return DiscussionItemTypeEnum.DealSystemSuccessMessage;
    case ApiDiscussionItemTypeEnum.ContractSystemSuccessMessage:
      return DiscussionItemTypeEnum.ContractSystemSuccessMessage;
    case ApiDiscussionItemTypeEnum.Application:
      return DiscussionItemTypeEnum.Application;
    case ApiDiscussionItemTypeEnum.EdsDealSignedBySender:
      return DiscussionItemTypeEnum.EdsDealSignedBySender;
    case ApiDiscussionItemTypeEnum.EdsDealSignedByRecipient:
      return DiscussionItemTypeEnum.EdsDealSignedByRecipient;
    case ApiDiscussionItemTypeEnum.ApplicationApproveMessage:
      return DiscussionItemTypeEnum.ApplicationApproveMessage;
    case ApiDiscussionItemTypeEnum.ApplicationRevoke:
      return DiscussionItemTypeEnum.ApplicationRevoke;
    case ApiDiscussionItemTypeEnum.ApplicationRetradingUpdateMessage:
      return DiscussionItemTypeEnum.ApplicationRetradingUpdateMessage;
    case ApiDiscussionItemTypeEnum.RejectDealByCustomer:
      return DiscussionItemTypeEnum.RejectDealByCustomer;
    case ApiDiscussionItemTypeEnum.CustomerDealCommentSystemMessage:
      return DiscussionItemTypeEnum.CustomerDealCommentSystemMessage;
    case ApiDiscussionItemTypeEnum.DealUpdatePrice:
      return DiscussionItemTypeEnum.DealUpdatePrice;
    case ApiDiscussionItemTypeEnum.MmoCreateDealSystemMessage:
      return DiscussionItemTypeEnum.MmoCreateDealSystemMessage;
    case ApiDiscussionItemTypeEnum.MmoParticipantMissedSigningTime:
      return DiscussionItemTypeEnum.MmoParticipantMissedSigningTime;
    case ApiDiscussionItemTypeEnum.MmoTradeFromDealSigningToDealNotSignedState:
      return DiscussionItemTypeEnum.MmoTradeFromDealSigningToDealNotSignedState;
    case ApiDiscussionItemTypeEnum.MmoTradeFromDealNotSignedToFillingApplicationsState:
      return DiscussionItemTypeEnum.MmoTradeFromDealNotSignedToFillingApplicationsState;
    case ApiDiscussionItemTypeEnum.DealSigningExpiredSystemMessage:
      return DiscussionItemTypeEnum.DealSigningExpiredSystemMessage;
    case ApiDiscussionItemTypeEnum.MmoDealOrAppExpiredSystemMessage:
      return DiscussionItemTypeEnum.MmoDealOrAppExpiredSystemMessage;
    case ApiDiscussionItemTypeEnum.ParticipantSuggestedToSignPaperDealSystemMessage:
      return DiscussionItemTypeEnum.ParticipantSuggestedToSignPaperDealSystemMessage;
    case ApiDiscussionItemTypeEnum.CustomerRefusedSigningPaperDealSystemMessage:
      return DiscussionItemTypeEnum.CustomerRefusedSigningPaperDealSystemMessage;
    case ApiDiscussionItemTypeEnum.CustomerAcceptedSigningPaperDealSystemMessage:
      return DiscussionItemTypeEnum.CustomerAcceptedSigningPaperDealSystemMessage;
    case ApiDiscussionItemTypeEnum.ParticipantSentDifferenceProtocolMessage:
      return DiscussionItemTypeEnum.ParticipantSentDifferenceProtocolMessage;
    case ApiDiscussionItemTypeEnum.CustomerSentContactInformationWithOrderProposing:
      return DiscussionItemTypeEnum.CustomerSentContactInformationWithOrderProposing;
    case ApiDiscussionItemTypeEnum.AdditionalAgreementSentMessage:
      return DiscussionItemTypeEnum.AdditionalAgreementSentMessage;
    case ApiDiscussionItemTypeEnum.AdditionalAgreementSignedMessage:
      return DiscussionItemTypeEnum.AdditionalAgreementSignedMessage;
    case ApiDiscussionItemTypeEnum.AdditionalAgreementRejectedMessage:
      return DiscussionItemTypeEnum.AdditionalAgreementRejectedMessage;
    case ApiDiscussionItemTypeEnum.ApplicationWithDeclaration:
      return DiscussionItemTypeEnum.ApplicationWithDeclaration;
    case ApiDiscussionItemTypeEnum.DealWithManyPositions:
      return DiscussionItemTypeEnum.DealWithManyPositions;
    case ApiDiscussionItemTypeEnum.PreliminaryOfferSentMessage:
      return DiscussionItemTypeEnum.PreliminaryOfferSentMessage;
    case ApiDiscussionItemTypeEnum.PreliminaryOfferSignDealAfterMoneyBlock:
      return DiscussionItemTypeEnum.PreliminaryOfferSignDealAfterMoneyBlock;
    case ApiDiscussionItemTypeEnum.DealCreatedFromCart:
      return DiscussionItemTypeEnum.DealCreatedFromCart;
    case ApiDiscussionItemTypeEnum.DealCreatedZep:
      return DiscussionItemTypeEnum.DealCreatedZep;
    case ApiDiscussionItemTypeEnum.DealRejectedBySupplier:
      return DiscussionItemTypeEnum.DealRejectedBySupplier;
    case ApiDiscussionItemTypeEnum.DealRejectedBySupplierZepToZc:
      return DiscussionItemTypeEnum.DealRejectedBySupplierZepToZc;
    case ApiDiscussionItemTypeEnum.DealConditionsChangedBySupplier:
      return DiscussionItemTypeEnum.DealConditionsChangedBySupplier;
    case ApiDiscussionItemTypeEnum.DealConditionsChangedByCustomer:
      return DiscussionItemTypeEnum.DealConditionsChangedByCustomer;
    case ApiDiscussionItemTypeEnum.DealAcceptedBySupplier:
      return DiscussionItemTypeEnum.DealAcceptedBySupplier;
    case ApiDiscussionItemTypeEnum.DealAcceptedBySupplierAsNeededToCustomer:
      return DiscussionItemTypeEnum.DealAcceptedBySupplierAsNeededToCustomer;
    case ApiDiscussionItemTypeEnum.ContractFileSentBySupplier:
      return DiscussionItemTypeEnum.ContractFileSentBySupplier;
    case ApiDiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomer:
      return DiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomer;
    case ApiDiscussionItemTypeEnum.ContractSigningByCustomerIsExpired:
      return DiscussionItemTypeEnum.ContractSigningByCustomerIsExpired;
    case ApiDiscussionItemTypeEnum.ContractSentByCustomerForRework:
      return DiscussionItemTypeEnum.ContractSentByCustomerForRework;
    case ApiDiscussionItemTypeEnum.ContractSentBySupplierForRework:
      return DiscussionItemTypeEnum.ContractSentBySupplierForRework;
    case ApiDiscussionItemTypeEnum.ContractSignedByCustomer:
      return DiscussionItemTypeEnum.ContractSignedByCustomer;
    case ApiDiscussionItemTypeEnum.ContractSignedBySupplier:
      return DiscussionItemTypeEnum.ContractSignedBySupplier;
    case ApiDiscussionItemTypeEnum.ApplicationRejectedSystemMessage:
      return DiscussionItemTypeEnum.ApplicationRejectedSystemMessage;
    case ApiDiscussionItemTypeEnum.PublishCustomerComissionProtocol:
      return DiscussionItemTypeEnum.PublishCustomerComissionProtocol;
    case ApiDiscussionItemTypeEnum.PositionalComparisonDealCreated:
      return DiscussionItemTypeEnum.PositionalComparisonDealCreated;
    case ApiDiscussionItemTypeEnum.PaperDealAutoCompleted:
      return DiscussionItemTypeEnum.PaperDealAutoCompleted;
    case ApiDiscussionItemTypeEnum.SingleSupplierSentPaperDealToCustomer:
      return DiscussionItemTypeEnum.SingleSupplierSentPaperDealToCustomer;
    case ApiDiscussionItemTypeEnum.CustomerSentPaperDealToSingleSupplier:
      return DiscussionItemTypeEnum.CustomerSentPaperDealToSingleSupplier;
    case ApiDiscussionItemTypeEnum.CustomerSentParticipantOfferToRepeatReviewing:
      return DiscussionItemTypeEnum.CustomerSentParticipantOfferToRepeatReviewing;
    case ApiDiscussionItemTypeEnum.PublishCustomerComissionProtocolToEis:
      return DiscussionItemTypeEnum.PublishCustomerComissionProtocolToEis;
    case ApiDiscussionItemTypeEnum.DealExecuted:
      return DiscussionItemTypeEnum.DealExecuted;
    case ApiDiscussionItemTypeEnum.DealTerminated:
      return DiscussionItemTypeEnum.DealTerminated;
    case ApiDiscussionItemTypeEnum.SelectedOtherSupplier:
      return DiscussionItemTypeEnum.SelectedOtherSupplier;
    case ApiDiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomerZmo:
      return DiscussionItemTypeEnum.ContractFileSentBySupplierAsNeededToCustomerZmo;
    case ApiDiscussionItemTypeEnum.ApprovedDealRejectedBySupplier:
      return DiscussionItemTypeEnum.ApprovedDealRejectedBySupplier;
    case ApiDiscussionItemTypeEnum.ReturnContractToFormingSystemMessage:
      return DiscussionItemTypeEnum.ReturnContractToFormingSystemMessage;
    case ApiDiscussionItemTypeEnum.ApplicationClarificationRequest:
      return DiscussionItemTypeEnum.ApplicationClarificationRequest;
    case ApiDiscussionItemTypeEnum.ApplicationClarificationResponse:
      return DiscussionItemTypeEnum.ApplicationClarificationResponse;
    case ApiDiscussionItemTypeEnum.AdditionalAgreementSignedByParticipantMessage:
      return DiscussionItemTypeEnum.AdditionalAgreementSignedByParticipantMessage;
    case ApiDiscussionItemTypeEnum.QuotationSessionFinalProposalConfirmed:
      return DiscussionItemTypeEnum.QuotationSessionFinalProposalConfirmed;
    case ApiDiscussionItemTypeEnum.PreliminaryOfferReturnTradeToFillingApps:
      return DiscussionItemTypeEnum.PreliminaryOfferReturnTradeToFillingApps;
    case ApiDiscussionItemTypeEnum.DealAgreementChangedBySupplier:
      return DiscussionItemTypeEnum.DealAgreementChangedBySupplier;
    case ApiDiscussionItemTypeEnum.DealAgreementChangedByCustomer:
      return DiscussionItemTypeEnum.DealAgreementChangedByCustomer;
    case ApiDiscussionItemTypeEnum.ShipmentPointEntered:
      return DiscussionItemTypeEnum.ShipmentPointEntered;
    default:
      throw new Error(`Enum value is not defined: ApiDiscussionItemTypeEnum=${String(source)}`);
  }
}
