import { ApiMarketTradeViewDto } from '../../../swagger/models/api-market-trade-view-dto';
import { MarketTradeView } from '../../models/market-trade-view.interface';
import { adaptAdditionalRequirementDto2ToUI } from './additional-requirement-dto-2.adapter';
import { adaptApplicationParametersToUI } from './application-parameters.adapter';
import { adaptApplicationStateEnumToUI } from './application-state-enum.adapter';
import { adaptAvailableVatTypeEnumToUI } from './available-vat-type-enum.adapter';
import { adaptDealSignerAltToUI } from './deal-signer-alt.adapter';
import { adaptDealStateEnumToUI } from './deal-state-enum.adapter';
import { adaptDeliveryMethodAltEnumToUI } from './delivery-method-alt-enum.adapter';
import { adaptDictionaryItemAltToUI } from './dictionary-item-alt.adapter';
import { adaptEisIntegrationDataAltToUI } from './eis-integration-data-alt.adapter';
import { adaptEisTradeInfoAltToUI } from './eis-trade-info-alt.adapter';
import { adaptFederalLawLimitAltEnumToUI } from './federal-law-limit-alt-enum.adapter';
import { adaptLotStateEnumToUI } from './lot-state-enum.adapter';
import { adaptM4DDealSignRequiredEnumToUI } from './m-4-d-deal-sign-required-enum.adapter';
import { adaptMarketDealStateEnumToUI } from './market-deal-state-enum.adapter';
import { adaptMarketEntityTypeAltEnumToUI } from './market-entity-type-alt-enum.adapter';
import { adaptMarketTradeDealAltToUI } from './market-trade-deal-alt.adapter';
import { adaptMarketTradePersonAltToUI } from './market-trade-person-alt.adapter';
import { adaptMarketTradeProductAltToUI } from './market-trade-product-alt.adapter';
import { adaptMeetsRequirementsEnumToUI } from './meets-requirements-enum.adapter';
import { adaptMyTermsAltToUI } from './my-terms-alt.adapter';
import { adaptOrderStateEnumToUI } from './order-state-enum.adapter';
import { adaptPriceCorridorToUI } from './price-corridor.adapter';
import { adaptPurchaseMethodTypeEnumToUI } from './purchase-method-type-enum.adapter';
import { adaptRegulationInfoToUI } from './regulation-info.adapter';
import { adaptRetradingTypeEnumToUI } from './retrading-type-enum.adapter';
import { adaptShortTenantSettingAltToUI } from './short-tenant-setting-alt.adapter';
import { adaptTradeBusinessFlowEnumToUI } from './trade-business-flow-enum.adapter';
import { adaptTradeLotSpecificationToUI } from './trade-lot-specification.adapter';
import { adaptTradeStateEnumToUI } from './trade-state-enum.adapter';
import { adaptTradeViewFormOptionsToUI } from './trade-view-form-options.adapter';
import { adaptVatRateStateEnumToUI } from './vat-rate-state-enum.adapter';
import { adaptZmoFinanceSourceEnumToUI } from './zmo-finance-source-enum.adapter';

export function adaptMarketTradeViewToUI(source?: ApiMarketTradeViewDto | null): MarketTradeView {
  return {
    additionalRequirements: (source?.AdditionalRequirements ?? []).map((item) => adaptAdditionalRequirementDto2ToUI(item)),
    allowApplicationReject: source?.AllowApplicationReject ?? false,
    applicationId: source?.ApplicationId ?? 0,
    applicationParameters: adaptApplicationParametersToUI(source?.ApplicationParameters),
    applicationState: adaptApplicationStateEnumToUI(source?.ApplicationState),
    businessFlowType: adaptTradeBusinessFlowEnumToUI(source?.BusinessFlowType),
    canSuggestPaperFormSigning: source?.CanSuggestPaperFormSigning ?? false,
    childTradeBusinessFlowType: adaptTradeBusinessFlowEnumToUI(source?.ChildTradeBusinessFlowType),
    childTradeHosts: source?.ChildTradeHosts ?? [],
    childTradeId: source?.ChildTradeId ?? 0,
    conditionsOfPayment: source?.ConditionsOfPayment ?? '',
    contactPerson: adaptMarketTradePersonAltToUI(source?.ContactPerson),
    contractAmountInfo: source?.ContractAmountInfo ?? '',
    currencyCode: source?.CurrencyCode ?? '',
    currentStageId: source?.CurrentStageId ?? 0,
    customerExternalOrganizationId: source?.CustomerExternalOrganizationId ?? '',
    customerFullName: source?.CustomerFullName ?? '',
    customerGuid: source?.CustomerGuid ?? '',
    customerId: source?.CustomerId ?? 0,
    customerPhysAddress: source?.CustomerPhysAddress ?? '',
    customerSource: source?.CustomerSource ?? 0,
    dealBelongToCurrentOrg: source?.DealBelongToCurrentOrg ?? false,
    dealConclusionTermInfo: source?.DealConclusionTermInfo ?? '',
    dealDirectionFlow: source?.DealDirectionFlow ?? 0,
    dealExecutionDate: source?.DealExecutionDate ?? '',
    dealId: source?.DealId ?? 0,
    dealState: adaptDealStateEnumToUI(source?.DealState),
    deals: (source?.Deals ?? []).map((item) => adaptMarketTradeDealAltToUI(item)),
    deliveryKladrRegionCode: source?.DeliveryKladrRegionCode ?? '',
    deliveryKladrRegionCodes: (source?.DeliveryKladrRegionCodes ?? []).map((item) => adaptDictionaryItemAltToUI(item)),
    deliveryKladrRegionName: source?.DeliveryKladrRegionName ?? '',
    deliveryMethod: adaptDeliveryMethodAltEnumToUI(source?.DeliveryMethod),
    deliveryTerms: source?.DeliveryTerms ?? '',
    description: source?.Description ?? '',
    displayApproveBtn: source?.DisplayApproveBtn ?? false,
    displayDealDontConcludeBtn: source?.DisplayDealDontConcludeBtn ?? false,
    eisIntegrationData: adaptEisIntegrationDataAltToUI(source?.EisIntegrationData),
    eisTradeInfo: adaptEisTradeInfoAltToUI(source?.EisTradeInfo),
    enableKtruSpecifications: source?.EnableKtruSpecifications ?? false,
    enableMonetizationMarket: source?.EnableMonetizationMarket ?? false,
    enablePositionCharacteristics: source?.EnablePositionCharacteristics ?? false,
    entityType: adaptMarketEntityTypeAltEnumToUI(source?.EntityType),
    externalId: source?.ExternalId ?? '',
    externalSystemId: source?.ExternalSystemId ?? 0,
    federalLawLimit: adaptFederalLawLimitAltEnumToUI(source?.FederalLawLimit),
    fillingApplicationEndDate: source?.FillingApplicationEndDate ?? '',
    hasDealFile: source?.HasDealFile ?? false,
    hasManualParticipantOfferToTrade: source?.HasManualParticipantOfferToTrade ?? false,
    hasUncompletedEisOutgoingSaga: source?.HasUncompletedEisOutgoingSaga ?? false,
    hosts: source?.Hosts ?? [],
    id: source?.Id ?? 0,
    initialPriceWithVat: source?.InitialPriceWithVat ?? 0,
    initialPriceWithoutVat: source?.InitialPriceWithoutVat ?? 0,
    initialTenantSetting: adaptShortTenantSettingAltToUI(source?.InitialTenantSetting),
    isApprovalRequestExists: source?.IsApprovalRequestExists ?? false,
    isAutoCreateDealAfterReviewApplications: source?.IsAutoCreateDealAfterReviewApplications ?? false,
    isAvailableSelectOnlyOneOfferForItem: source?.IsAvailableSelectOnlyOneOfferForItem ?? false,
    isBy223Fz: source?.IsBy223Fz ?? false,
    isBy44Fz: source?.IsBy44Fz ?? false,
    isContractInElectronicForm: source?.IsContractInElectronicForm ?? false,
    isCustomPrice: source?.IsCustomPrice ?? false,
    isCustomer: source?.IsCustomer ?? false,
    isCustomerAcceptByOkeiOffers: source?.IsCustomerAcceptByOkeiOffers ?? false,
    isCustomerAcceptOnlyManualOffers: source?.IsCustomerAcceptOnlyManualOffers ?? false,
    isDealSigningExpired: source?.IsDealSigningExpired ?? false,
    isEditable: source?.IsEditable ?? false,
    isEisConcludeDealRequired: source?.IsEisConcludeDealRequired ?? false,
    isEisTradeAccelerated: source?.IsEisTradeAccelerated ?? false,
    isFederalLawsEnable: source?.IsFederalLawsEnable ?? false,
    isHiddenContract: source?.IsHiddenContract ?? false,
    isImmediate: source?.IsImmediate ?? false,
    isImportPhaseout: source?.IsImportPhaseout ?? false,
    isInEisWasChanged: source?.IsInEisWasChanged ?? false,
    isInitialPriceDefined: source?.IsInitialPriceDefined ?? false,
    isInitialPriceReduction: source?.IsInitialPriceReduction ?? false,
    isLapsed: source?.IsLapsed ?? false,
    isLotPriceEnteredWithVAT: source?.IsLotPriceEnteredWithVAT ?? false,
    isLotPriceWithVat: source?.IsLotPriceWithVat ?? false,
    isModificationSentToOos: source?.IsModificationSentToOos ?? false,
    isOnlySmp: source?.IsOnlySmp ?? false,
    isOrganizer: source?.IsOrganizer ?? false,
    isParentContractNumberNotSpecified: source?.IsParentContractNumberNotSpecified ?? false,
    isPositionalVatEnable: source?.IsPositionalVatEnable ?? false,
    isPrivate: source?.IsPrivate ?? false,
    isRetradingEnabled: source?.IsRetradingEnabled ?? false,
    isRussianPurchaseObjectHasAdvantage: source?.IsRussianPurchaseObjectHasAdvantage ?? false,
    isSanctionedPurchase: source?.IsSanctionedPurchase ?? false,
    isSendToEis: source?.IsSendToEis ?? false,
    isSingleWinner: source?.IsSingleWinner ?? false,
    isSmallBusinessEntity: source?.IsSmallBusinessEntity ?? false,
    isSortApplicationsByPriceWithoutVat: source?.IsSortApplicationsByPriceWithoutVat ?? false,
    isTradeNeedConfirmCustomerTermsWhenOffer: source?.IsTradeNeedConfirmCustomerTermsWhenOffer ?? false,
    isUnitBidding: source?.IsUnitBidding ?? false,
    itemsCount: source?.ItemsCount ?? 0,
    lotAuctionId: source?.LotAuctionId ?? 0,
    lotId: source?.LotId ?? 0,
    lotItemsSumPrice: source?.LotItemsSumPrice ?? 0,
    m4DDealSignRequired: adaptM4DDealSignRequiredEnumToUI(source?.M4DDealSignRequired),
    marketState: adaptMarketDealStateEnumToUI(source?.MarketState),
    marketStateDescription: source?.MarketStateDescription ?? '',
    maxDealPriceWithVat: source?.MaxDealPriceWithVat ?? 0,
    maxDealPriceWithoutVat: source?.MaxDealPriceWithoutVat ?? 0,
    meetsRequirements: adaptMeetsRequirementsEnumToUI(source?.MeetsRequirements),
    movingProLink: source?.MovingProLink ?? '',
    needBlockMoney: source?.NeedBlockMoney ?? false,
    offerId: source?.OfferId ?? 0,
    offerTerms: adaptMyTermsAltToUI(source?.OfferTerms),
    onlyOneRetradingBidAllowed: source?.OnlyOneRetradingBidAllowed ?? false,
    orderState: adaptOrderStateEnumToUI(source?.OrderState),
    organizerExternalOrganizationId: source?.OrganizerExternalOrganizationId ?? '',
    organizerFullName: source?.OrganizerFullName ?? '',
    organizerGuid: source?.OrganizerGuid ?? '',
    organizerId: source?.OrganizerId ?? 0,
    organizerSource: source?.OrganizerSource ?? 0,
    original223TradeLotState: adaptLotStateEnumToUI(source?.Original223TradeLotState),
    parentContractNumber: source?.ParentContractNumber ?? '',
    parentNotTookPlaceTradeBusinessFlowType: adaptTradeBusinessFlowEnumToUI(source?.ParentNotTookPlaceTradeBusinessFlowType),
    parentNotTookPlaceTradeHosts: source?.ParentNotTookPlaceTradeHosts ?? [],
    parentNotTookPlaceTradeId: source?.ParentNotTookPlaceTradeId ?? 0,
    participantExternalOrganizationId: source?.ParticipantExternalOrganizationId ?? '',
    participantFullName: source?.ParticipantFullName ?? '',
    participantGuid: source?.ParticipantGuid ?? '',
    participantId: source?.ParticipantId ?? 0,
    participantSource: source?.ParticipantSource ?? 0,
    pictureGuids: source?.PictureGuids ?? [],
    planNumber: source?.PlanNumber ?? '',
    planPositionNumber: source?.PlanPositionNumber ?? '',
    planedDealSignDate: source?.PlanedDealSignDate ?? '',
    possibleSelfDelivery: source?.PossibleSelfDelivery ?? false,
    possibleSendByTransportCompany: source?.PossibleSendByTransportCompany ?? false,
    price: source?.Price ?? 0,
    priceCorridor: adaptPriceCorridorToUI(source?.PriceCorridor),
    priceWithVat: source?.PriceWithVat ?? false,
    products: (source?.Products ?? []).map((item) => adaptMarketTradeProductAltToUI(item)),
    prohibitPostingCustomerComissionProtocol: source?.ProhibitPostingCustomerComissionProtocol ?? false,
    protocolReadyToPublish: source?.ProtocolReadyToPublish ?? false,
    publicationDate: source?.PublicationDate ?? '',
    purchaseMethodType: adaptPurchaseMethodTypeEnumToUI(source?.PurchaseMethodType),
    rateVat: adaptAvailableVatTypeEnumToUI(source?.RateVat),
    regulationInfo: adaptRegulationInfoToUI(source?.RegulationInfo),
    requiredSupplierRegistration: source?.RequiredSupplierRegistration ?? false,
    requirementsInfo: source?.RequirementsInfo ?? '',
    retradingBidLeftCount: source?.RetradingBidLeftCount ?? 0,
    retradingEndDate: source?.RetradingEndDate ?? '',
    retradingStartDate: source?.RetradingStartDate ?? '',
    retradingType: adaptRetradingTypeEnumToUI(source?.RetradingType),
    russianPurchaseAdvantageInfo: source?.RussianPurchaseAdvantageInfo ?? '',
    showProtocol: source?.ShowProtocol ?? false,
    showProtocolDocument: source?.ShowProtocolDocument ?? false,
    signer: adaptDealSignerAltToUI(source?.Signer),
    specifications: (source?.Specifications ?? []).map((item) => adaptTradeLotSpecificationToUI(item)),
    supplierWithSmallBusinessRequirements: source?.SupplierWithSmallBusinessRequirements ?? false,
    supplierWithUniversalRequirements: source?.SupplierWithUniversalRequirements ?? false,
    tags: source?.Tags ?? [],
    tenantId: source?.TenantId ?? 0,
    tradeName: source?.TradeName ?? '',
    tradeNumber: source?.TradeNumber ?? '',
    tradeState: adaptTradeStateEnumToUI(source?.TradeState),
    tradeSum: source?.TradeSum ?? 0,
    tradeViewFormOptions: adaptTradeViewFormOptionsToUI(source?.TradeViewFormOptions),
    vatRate: source?.VatRate ?? 0,
    vatRateDescription: source?.VatRateDescription ?? '',
    vatRateState: adaptVatRateStateEnumToUI(source?.VatRateState),
    winnerTradeLotApplicationId: source?.WinnerTradeLotApplicationId ?? 0,
    workGroupIds: source?.WorkGroupIds ?? [],
    zmoFinanceSource: adaptZmoFinanceSourceEnumToUI(source?.ZmoFinanceSource),
    zmoFinanceSourceDescription: source?.ZmoFinanceSourceDescription ?? '',
    zmoFzType: source?.ZmoFzType ?? 0,
    zmoFzTypeDescription: source?.ZmoFzTypeDescription ?? '',
    zmoFzTypeHint: source?.ZmoFzTypeHint ?? '',
    zmoFzTypeName: source?.ZmoFzTypeName ?? '',
  };
}
