import { ApiOrgSettingNameEnum } from '../../../swagger/models/api-org-setting-name-enum';
import { OrgSettingNameEnum } from '../../enums/org-setting-name.enum';

export function adaptOrgSettingNameEnumToUI(source?: ApiOrgSettingNameEnum | null): OrgSettingNameEnum {
  switch (source) {
    case ApiOrgSettingNameEnum.None:
      return OrgSettingNameEnum.None;
    case ApiOrgSettingNameEnum.MaxNmz:
      return OrgSettingNameEnum.MaxNmz;
    case ApiOrgSettingNameEnum.IsChatEnable:
      return OrgSettingNameEnum.IsChatEnable;
    case ApiOrgSettingNameEnum.DealDirectionFlow:
      return OrgSettingNameEnum.DealDirectionFlow;
    case ApiOrgSettingNameEnum.IsDocumentAttachRequired:
      return OrgSettingNameEnum.IsDocumentAttachRequired;
    case ApiOrgSettingNameEnum.MaxApplicationAmount:
      return OrgSettingNameEnum.MaxApplicationAmount;
    case ApiOrgSettingNameEnum.EnableRaiseApplicationPriceMoreThanTradePrice:
      return OrgSettingNameEnum.EnableRaiseApplicationPriceMoreThanTradePrice;
    case ApiOrgSettingNameEnum.EnableShowingOtherApplicationsInTrade:
      return OrgSettingNameEnum.EnableShowingOtherApplicationsInTrade;
    case ApiOrgSettingNameEnum.EnableApplicationsDenyPriceRaise:
      return OrgSettingNameEnum.EnableApplicationsDenyPriceRaise;
    case ApiOrgSettingNameEnum.CreateApplicationLogoRelativePath:
      return OrgSettingNameEnum.CreateApplicationLogoRelativePath;
    case ApiOrgSettingNameEnum.CreateApplicationText:
      return OrgSettingNameEnum.CreateApplicationText;
    case ApiOrgSettingNameEnum.ConfigSettingObject:
      return OrgSettingNameEnum.ConfigSettingObject;
    case ApiOrgSettingNameEnum.IsDealNumberAutoGenerationEnabled:
      return OrgSettingNameEnum.IsDealNumberAutoGenerationEnabled;
    case ApiOrgSettingNameEnum.EnableMonetizationZmo:
      return OrgSettingNameEnum.EnableMonetizationZmo;
    case ApiOrgSettingNameEnum.EnableMonetizationMarket:
      return OrgSettingNameEnum.EnableMonetizationMarket;
    case ApiOrgSettingNameEnum.ExcludedBftFromTenantSearch:
      return OrgSettingNameEnum.ExcludedBftFromTenantSearch;
    case ApiOrgSettingNameEnum.ProhibitionShowOutsideTenant:
      return OrgSettingNameEnum.ProhibitionShowOutsideTenant;
    case ApiOrgSettingNameEnum.RedirectTradeUrl:
      return OrgSettingNameEnum.RedirectTradeUrl;
    case ApiOrgSettingNameEnum.TradePlanTemplateLoadMode:
      return OrgSettingNameEnum.TradePlanTemplateLoadMode;
    case ApiOrgSettingNameEnum.AutoProtocolWinnerDescription:
      return OrgSettingNameEnum.AutoProtocolWinnerDescription;
    case ApiOrgSettingNameEnum.AlwaysShowCustomerConsiderationProtocol:
      return OrgSettingNameEnum.AlwaysShowCustomerConsiderationProtocol;
    case ApiOrgSettingNameEnum.DenyTradePriceRaise:
      return OrgSettingNameEnum.DenyTradePriceRaise;
    case ApiOrgSettingNameEnum.AllowInitialPriceNotDefined:
      return OrgSettingNameEnum.AllowInitialPriceNotDefined;
    case ApiOrgSettingNameEnum.EnableZeroTariff:
      return OrgSettingNameEnum.EnableZeroTariff;
    case ApiOrgSettingNameEnum.ZeroTariffDateFrom:
      return OrgSettingNameEnum.ZeroTariffDateFrom;
    case ApiOrgSettingNameEnum.ZeroTariffDateTo:
      return OrgSettingNameEnum.ZeroTariffDateTo;
    case ApiOrgSettingNameEnum.AutoProtocolFileName:
      return OrgSettingNameEnum.AutoProtocolFileName;
    case ApiOrgSettingNameEnum.AllowPaperDealForm:
      return OrgSettingNameEnum.AllowPaperDealForm;
    case ApiOrgSettingNameEnum.ExtendedBudgetForFinancingSource:
      return OrgSettingNameEnum.ExtendedBudgetForFinancingSource;
    case ApiOrgSettingNameEnum.ShowMarketPriceLists:
      return OrgSettingNameEnum.ShowMarketPriceLists;
    case ApiOrgSettingNameEnum.RequiredTradeDocumentType:
      return OrgSettingNameEnum.RequiredTradeDocumentType;
    case ApiOrgSettingNameEnum.RequiredTradeLotApplicationDocumentType:
      return OrgSettingNameEnum.RequiredTradeLotApplicationDocumentType;
    case ApiOrgSettingNameEnum.AvailableTenant:
      return OrgSettingNameEnum.AvailableTenant;
    case ApiOrgSettingNameEnum.AvailableRegion:
      return OrgSettingNameEnum.AvailableRegion;
    case ApiOrgSettingNameEnum.ShowTradeContactInfoAndDocuments:
      return OrgSettingNameEnum.ShowTradeContactInfoAndDocuments;
    case ApiOrgSettingNameEnum.ShowBankingDetailsOnCreateApplicationForm:
      return OrgSettingNameEnum.ShowBankingDetailsOnCreateApplicationForm;
    case ApiOrgSettingNameEnum.DaysForNoticeBeforeArchive:
      return OrgSettingNameEnum.DaysForNoticeBeforeArchive;
    case ApiOrgSettingNameEnum.TariffServiceId:
      return OrgSettingNameEnum.TariffServiceId;
    case ApiOrgSettingNameEnum.IsRevokeDealAllowedForNonWinnerSupplier:
      return OrgSettingNameEnum.IsRevokeDealAllowedForNonWinnerSupplier;
    case ApiOrgSettingNameEnum.EnableTradeProtocolForCompletedDeals:
      return OrgSettingNameEnum.EnableTradeProtocolForCompletedDeals;
    case ApiOrgSettingNameEnum.EnableTradeProtocolForCanceledDeals:
      return OrgSettingNameEnum.EnableTradeProtocolForCanceledDeals;
    case ApiOrgSettingNameEnum.IsMonopolist:
      return OrgSettingNameEnum.IsMonopolist;
    case ApiOrgSettingNameEnum.NewDealSignFlowForBft:
      return OrgSettingNameEnum.NewDealSignFlowForBft;
    case ApiOrgSettingNameEnum.EnableDealRejectionReasonsList:
      return OrgSettingNameEnum.EnableDealRejectionReasonsList;
    case ApiOrgSettingNameEnum.IsFinanceSourceDisplayed:
      return OrgSettingNameEnum.IsFinanceSourceDisplayed;
    case ApiOrgSettingNameEnum.ShowTradeCustomerOnTradesGrid:
      return OrgSettingNameEnum.ShowTradeCustomerOnTradesGrid;
    case ApiOrgSettingNameEnum.IsCommercialOffersAvailable:
      return OrgSettingNameEnum.IsCommercialOffersAvailable;
    case ApiOrgSettingNameEnum.AllowToCreateAdditionalAgreement:
      return OrgSettingNameEnum.AllowToCreateAdditionalAgreement;
    case ApiOrgSettingNameEnum.CreateApplicationFromMarket:
      return OrgSettingNameEnum.CreateApplicationFromMarket;
    case ApiOrgSettingNameEnum.SendNotificationsAboutTradesOnlyToMarket:
      return OrgSettingNameEnum.SendNotificationsAboutTradesOnlyToMarket;
    case ApiOrgSettingNameEnum.ShowEventLogs:
      return OrgSettingNameEnum.ShowEventLogs;
    case ApiOrgSettingNameEnum.OrganizationsForSyncExternalRoles:
      return OrgSettingNameEnum.OrganizationsForSyncExternalRoles;
    case ApiOrgSettingNameEnum.TenantCssThemeName:
      return OrgSettingNameEnum.TenantCssThemeName;
    case ApiOrgSettingNameEnum.CanSendTradeToEIS:
      return OrgSettingNameEnum.CanSendTradeToEIS;
    case ApiOrgSettingNameEnum.ShowIsImportPhaseout:
      return OrgSettingNameEnum.ShowIsImportPhaseout;
    case ApiOrgSettingNameEnum.CanMakePurchasesPP2323OnTheAmendmentPP1352:
      return OrgSettingNameEnum.CanMakePurchasesPP2323OnTheAmendmentPP1352;
    case ApiOrgSettingNameEnum.IsOfferModerationEnable:
      return OrgSettingNameEnum.IsOfferModerationEnable;
    case ApiOrgSettingNameEnum.IsCartEnable:
      return OrgSettingNameEnum.IsCartEnable;
    case ApiOrgSettingNameEnum.IsChangeSingleSupplierTradeToPriceRequest:
      return OrgSettingNameEnum.IsChangeSingleSupplierTradeToPriceRequest;
    case ApiOrgSettingNameEnum.IsPassportAuthEnable:
      return OrgSettingNameEnum.IsPassportAuthEnable;
    case ApiOrgSettingNameEnum.IsManagersNotificationsEnabled:
      return OrgSettingNameEnum.IsManagersNotificationsEnabled;
    case ApiOrgSettingNameEnum.AllowTradeUpdate:
      return OrgSettingNameEnum.AllowTradeUpdate;
    case ApiOrgSettingNameEnum.AllowTradeCancel:
      return OrgSettingNameEnum.AllowTradeCancel;
    case ApiOrgSettingNameEnum.ParticipantOfferSourceVisibilitySettings:
      return OrgSettingNameEnum.ParticipantOfferSourceVisibilitySettings;
    case ApiOrgSettingNameEnum.ParticipantLoginRedirectTenant:
      return OrgSettingNameEnum.ParticipantLoginRedirectTenant;
    case ApiOrgSettingNameEnum.Is223AuthEnabled:
      return OrgSettingNameEnum.Is223AuthEnabled;
    case ApiOrgSettingNameEnum.IsMoAuthEnabled:
      return OrgSettingNameEnum.IsMoAuthEnabled;
    case ApiOrgSettingNameEnum.IsTableEditingModeEnabled:
      return OrgSettingNameEnum.IsTableEditingModeEnabled;
    case ApiOrgSettingNameEnum.IsZeroSingleSupplierTradeEnabled:
      return OrgSettingNameEnum.IsZeroSingleSupplierTradeEnabled;
    case ApiOrgSettingNameEnum.IsOfferContentComplaintsEnabled:
      return OrgSettingNameEnum.IsOfferContentComplaintsEnabled;
    case ApiOrgSettingNameEnum.IsImportSubstitutionRegistryEnabled:
      return OrgSettingNameEnum.IsImportSubstitutionRegistryEnabled;
    case ApiOrgSettingNameEnum.IsCatalogEnabled:
      return OrgSettingNameEnum.IsCatalogEnabled;
    case ApiOrgSettingNameEnum.IsCatalogSideFilterEnabled:
      return OrgSettingNameEnum.IsCatalogSideFilterEnabled;
    case ApiOrgSettingNameEnum.IsCatalogMenuSectionEnabled:
      return OrgSettingNameEnum.IsCatalogMenuSectionEnabled;
    case ApiOrgSettingNameEnum.IsOfferManualEditingEnabled:
      return OrgSettingNameEnum.IsOfferManualEditingEnabled;
    case ApiOrgSettingNameEnum.IsStoriesEnabled:
      return OrgSettingNameEnum.IsStoriesEnabled;
    case ApiOrgSettingNameEnum.OrdersSideFilterStructure:
      return OrgSettingNameEnum.OrdersSideFilterStructure;
    case ApiOrgSettingNameEnum.PriceListsSideFilterStructure:
      return OrgSettingNameEnum.PriceListsSideFilterStructure;
    case ApiOrgSettingNameEnum.HideProtocolForTradeWithSentToEis:
      return OrgSettingNameEnum.HideProtocolForTradeWithSentToEis;
    case ApiOrgSettingNameEnum.ShowProtocolForTradeWithApplicationEndDateWithoutSentToEis:
      return OrgSettingNameEnum.ShowProtocolForTradeWithApplicationEndDateWithoutSentToEis;
    case ApiOrgSettingNameEnum.ShowProtocolForTradeWithoutApplicationEndDateWithoutSentToEis:
      return OrgSettingNameEnum.ShowProtocolForTradeWithoutApplicationEndDateWithoutSentToEis;
    case ApiOrgSettingNameEnum.IsManufacturerEnabled:
      return OrgSettingNameEnum.IsManufacturerEnabled;
    case ApiOrgSettingNameEnum.AutomaticallyDetermineTradePurchaseMethodForEis:
      return OrgSettingNameEnum.AutomaticallyDetermineTradePurchaseMethodForEis;
    case ApiOrgSettingNameEnum.ShowFilterByGuaranteedSuppliers:
      return OrgSettingNameEnum.ShowFilterByGuaranteedSuppliers;
    case ApiOrgSettingNameEnum.IsTradeIdentificationCodeRequired:
      return OrgSettingNameEnum.IsTradeIdentificationCodeRequired;
    case ApiOrgSettingNameEnum.FillingApplicationsMinTimeForImmediateTrades:
      return OrgSettingNameEnum.FillingApplicationsMinTimeForImmediateTrades;
    case ApiOrgSettingNameEnum.EnableDealRejectReasonComment:
      return OrgSettingNameEnum.EnableDealRejectReasonComment;
    case ApiOrgSettingNameEnum.HidedSection:
      return OrgSettingNameEnum.HidedSection;
    case ApiOrgSettingNameEnum.SupplierHiddenSections:
      return OrgSettingNameEnum.SupplierHiddenSections;
    case ApiOrgSettingNameEnum.IsDealSeparateAttachement:
      return OrgSettingNameEnum.IsDealSeparateAttachement;
    case ApiOrgSettingNameEnum.AllowWorkGroups:
      return OrgSettingNameEnum.AllowWorkGroups;
    case ApiOrgSettingNameEnum.EnablePositionCharacteristics:
      return OrgSettingNameEnum.EnablePositionCharacteristics;
    case ApiOrgSettingNameEnum.IsCustomerIsSubjectToSanctions:
      return OrgSettingNameEnum.IsCustomerIsSubjectToSanctions;
    case ApiOrgSettingNameEnum.ProhibitPostingCustomerComissionProtocol:
      return OrgSettingNameEnum.ProhibitPostingCustomerComissionProtocol;
    case ApiOrgSettingNameEnum.AvailableOfferTenant:
      return OrgSettingNameEnum.AvailableOfferTenant;
    case ApiOrgSettingNameEnum.HomeRegion:
      return OrgSettingNameEnum.HomeRegion;
    case ApiOrgSettingNameEnum.ShowOnlyHomeRegion:
      return OrgSettingNameEnum.ShowOnlyHomeRegion;
    case ApiOrgSettingNameEnum.ParticipantOfferRedirectTenant:
      return OrgSettingNameEnum.ParticipantOfferRedirectTenant;
    case ApiOrgSettingNameEnum.DealNegotiation:
      return OrgSettingNameEnum.DealNegotiation;
    case ApiOrgSettingNameEnum.IsPositionalComparisonEnable:
      return OrgSettingNameEnum.IsPositionalComparisonEnable;
    case ApiOrgSettingNameEnum.IsCustomerAcceptOnlyManualOffers:
      return OrgSettingNameEnum.IsCustomerAcceptOnlyManualOffers;
    case ApiOrgSettingNameEnum.IsTradeNeedConfirmCustomerTermsWhenOffer:
      return OrgSettingNameEnum.IsTradeNeedConfirmCustomerTermsWhenOffer;
    case ApiOrgSettingNameEnum.HideApplicationDataOpenPartMode:
      return OrgSettingNameEnum.HideApplicationDataOpenPartMode;
    case ApiOrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForOpenPart:
      return OrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForOpenPart;
    case ApiOrgSettingNameEnum.HiddenApplicationParameterOpenPart:
      return OrgSettingNameEnum.HiddenApplicationParameterOpenPart;
    case ApiOrgSettingNameEnum.HideApplicationDataForParticipantMode:
      return OrgSettingNameEnum.HideApplicationDataForParticipantMode;
    case ApiOrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForParticipant:
      return OrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForParticipant;
    case ApiOrgSettingNameEnum.HiddenApplicationParameterForParticipant:
      return OrgSettingNameEnum.HiddenApplicationParameterForParticipant;
    case ApiOrgSettingNameEnum.HideApplicationDataForCustomerMode:
      return OrgSettingNameEnum.HideApplicationDataForCustomerMode;
    case ApiOrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForCustomer:
      return OrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForCustomer;
    case ApiOrgSettingNameEnum.HiddenApplicationParameterForCustomer:
      return OrgSettingNameEnum.HiddenApplicationParameterForCustomer;
    case ApiOrgSettingNameEnum.RegionalProductSignTitle:
      return OrgSettingNameEnum.RegionalProductSignTitle;
    case ApiOrgSettingNameEnum.RegionalProductSignFileGuid:
      return OrgSettingNameEnum.RegionalProductSignFileGuid;
    case ApiOrgSettingNameEnum.RegionalProductSignAvailabilityType:
      return OrgSettingNameEnum.RegionalProductSignAvailabilityType;
    case ApiOrgSettingNameEnum.IsOosNonPublic:
      return OrgSettingNameEnum.IsOosNonPublic;
    case ApiOrgSettingNameEnum.IsSendDifferencesProtocolOnlyOneTimes:
      return OrgSettingNameEnum.IsSendDifferencesProtocolOnlyOneTimes;
    case ApiOrgSettingNameEnum.IsPublishTradeOnGlobalMarketAfterProlongation:
      return OrgSettingNameEnum.IsPublishTradeOnGlobalMarketAfterProlongation;
    case ApiOrgSettingNameEnum.IsGufsin:
      return OrgSettingNameEnum.IsGufsin;
    case ApiOrgSettingNameEnum.WrongContractExecutionListUrl:
      return OrgSettingNameEnum.WrongContractExecutionListUrl;
    case ApiOrgSettingNameEnum.WrongContractExecutionInsertUrl:
      return OrgSettingNameEnum.WrongContractExecutionInsertUrl;
    case ApiOrgSettingNameEnum.IsAvailableSelectOnlyOneOfferForItem:
      return OrgSettingNameEnum.IsAvailableSelectOnlyOneOfferForItem;
    case ApiOrgSettingNameEnum.IsSingleWinnerRequired:
      return OrgSettingNameEnum.IsSingleWinnerRequired;
    case ApiOrgSettingNameEnum.IsAutoCreateDealAfterReviewApplications:
      return OrgSettingNameEnum.IsAutoCreateDealAfterReviewApplications;
    case ApiOrgSettingNameEnum.IsSortApplicationsByPriceWithoutVat:
      return OrgSettingNameEnum.IsSortApplicationsByPriceWithoutVat;
    case ApiOrgSettingNameEnum.KeepGuaranteeForParticipantsCount:
      return OrgSettingNameEnum.KeepGuaranteeForParticipantsCount;
    case ApiOrgSettingNameEnum.IsWorkWithDealsOn223:
      return OrgSettingNameEnum.IsWorkWithDealsOn223;
    case ApiOrgSettingNameEnum.IsSalesTechAuthEnable:
      return OrgSettingNameEnum.IsSalesTechAuthEnable;
    case ApiOrgSettingNameEnum.GeneratePriceJustificationFile:
      return OrgSettingNameEnum.GeneratePriceJustificationFile;
    case ApiOrgSettingNameEnum.IsPositionCharacteristicsEditable:
      return OrgSettingNameEnum.IsPositionCharacteristicsEditable;
    case ApiOrgSettingNameEnum.EnableKtruSpecifications:
      return OrgSettingNameEnum.EnableKtruSpecifications;
    case ApiOrgSettingNameEnum.RegionalProductSignText:
      return OrgSettingNameEnum.RegionalProductSignText;
    case ApiOrgSettingNameEnum.IsContractTemplatePassingEnabled:
      return OrgSettingNameEnum.IsContractTemplatePassingEnabled;
    case ApiOrgSettingNameEnum.AllowPartnerAsCustomer:
      return OrgSettingNameEnum.AllowPartnerAsCustomer;
    case ApiOrgSettingNameEnum.TradeCreateRedirectTenant:
      return OrgSettingNameEnum.TradeCreateRedirectTenant;
    case ApiOrgSettingNameEnum.AllowEditPublishedTrade:
      return OrgSettingNameEnum.AllowEditPublishedTrade;
    case ApiOrgSettingNameEnum.AllowSpeedUpTrade:
      return OrgSettingNameEnum.AllowSpeedUpTrade;
    case ApiOrgSettingNameEnum.FederalLawLimit:
      return OrgSettingNameEnum.FederalLawLimit;
    case ApiOrgSettingNameEnum.AllowApplicationReject:
      return OrgSettingNameEnum.AllowApplicationReject;
    case ApiOrgSettingNameEnum.IsSendCartToExternalSystemsEnabled:
      return OrgSettingNameEnum.IsSendCartToExternalSystemsEnabled;
    case ApiOrgSettingNameEnum.IsPositionalVatEnable:
      return OrgSettingNameEnum.IsPositionalVatEnable;
    case ApiOrgSettingNameEnum.AllowDeliveryPlaceAndTermsNotDefined:
      return OrgSettingNameEnum.AllowDeliveryPlaceAndTermsNotDefined;
    case ApiOrgSettingNameEnum.DefaultPriceListName:
      return OrgSettingNameEnum.DefaultPriceListName;
    case ApiOrgSettingNameEnum.AllowPublishApplicationWithoutFullName:
      return OrgSettingNameEnum.AllowPublishApplicationWithoutFullName;
    case ApiOrgSettingNameEnum.IsStarMorphSearchEnabled:
      return OrgSettingNameEnum.IsStarMorphSearchEnabled;
    case ApiOrgSettingNameEnum.IsStarOfferMorphSearchEnabled:
      return OrgSettingNameEnum.IsStarOfferMorphSearchEnabled;
    case ApiOrgSettingNameEnum.AvailableTenantSell:
      return OrgSettingNameEnum.AvailableTenantSell;
    case ApiOrgSettingNameEnum.IsImportPositionsFromExcelEnabled:
      return OrgSettingNameEnum.IsImportPositionsFromExcelEnabled;
    case ApiOrgSettingNameEnum.ImportExcelTemplateType:
      return OrgSettingNameEnum.ImportExcelTemplateType;
    case ApiOrgSettingNameEnum.EnableExternalDealMarket:
      return OrgSettingNameEnum.EnableExternalDealMarket;
    case ApiOrgSettingNameEnum.AutoProtocolShowSettings:
      return OrgSettingNameEnum.AutoProtocolShowSettings;
    case ApiOrgSettingNameEnum.IsReportsByWorkGroupEnabled:
      return OrgSettingNameEnum.IsReportsByWorkGroupEnabled;
    case ApiOrgSettingNameEnum.UseTradeTenantHostToGenerateNotificationLinks:
      return OrgSettingNameEnum.UseTradeTenantHostToGenerateNotificationLinks;
    case ApiOrgSettingNameEnum.IsLotItemOKPD2Required:
      return OrgSettingNameEnum.IsLotItemOKPD2Required;
    case ApiOrgSettingNameEnum.CustomProtocolShowSettings:
      return OrgSettingNameEnum.CustomProtocolShowSettings;
    case ApiOrgSettingNameEnum.MessengerEtp:
      return OrgSettingNameEnum.MessengerEtp;
    case ApiOrgSettingNameEnum.IsLandingSwitchEnabled:
      return OrgSettingNameEnum.IsLandingSwitchEnabled;
    case ApiOrgSettingNameEnum.LandingBannerForCustomerLargeText:
      return OrgSettingNameEnum.LandingBannerForCustomerLargeText;
    case ApiOrgSettingNameEnum.LandingBannerForCustomerSmallText:
      return OrgSettingNameEnum.LandingBannerForCustomerSmallText;
    case ApiOrgSettingNameEnum.LandingBannerForSupplierLargeText:
      return OrgSettingNameEnum.LandingBannerForSupplierLargeText;
    case ApiOrgSettingNameEnum.LandingBannerForSupplierSmallText:
      return OrgSettingNameEnum.LandingBannerForSupplierSmallText;
    case ApiOrgSettingNameEnum.LandingSchemeColorName:
      return OrgSettingNameEnum.LandingSchemeColorName;
    case ApiOrgSettingNameEnum.LandingYandexMetrikaCode:
      return OrgSettingNameEnum.LandingYandexMetrikaCode;
    case ApiOrgSettingNameEnum.TenantAdminHost:
      return OrgSettingNameEnum.TenantAdminHost;
    case ApiOrgSettingNameEnum.FillingApplicationsMinDays:
      return OrgSettingNameEnum.FillingApplicationsMinDays;
    case ApiOrgSettingNameEnum.RequiredDeclaration44Fz:
      return OrgSettingNameEnum.RequiredDeclaration44Fz;
    case ApiOrgSettingNameEnum.FormCreateTradeTemplateSettings:
      return OrgSettingNameEnum.FormCreateTradeTemplateSettings;
    case ApiOrgSettingNameEnum.CustomerRegulationFileGuid:
      return OrgSettingNameEnum.CustomerRegulationFileGuid;
    case ApiOrgSettingNameEnum.IsCustomerRegulationFileDisplayed:
      return OrgSettingNameEnum.IsCustomerRegulationFileDisplayed;
    case ApiOrgSettingNameEnum.SupplierDealSigningWorkingDays:
      return OrgSettingNameEnum.SupplierDealSigningWorkingDays;
    case ApiOrgSettingNameEnum.FormCreateOrderTemplateSettings:
      return OrgSettingNameEnum.FormCreateOrderTemplateSettings;
    case ApiOrgSettingNameEnum.CemIntegrationEnabled:
      return OrgSettingNameEnum.CemIntegrationEnabled;
    case ApiOrgSettingNameEnum.TradeViewFormTemplateSettings:
      return OrgSettingNameEnum.TradeViewFormTemplateSettings;
    case ApiOrgSettingNameEnum.InstructionFileGuid:
      return OrgSettingNameEnum.InstructionFileGuid;
    case ApiOrgSettingNameEnum.AllowTradeCreate:
      return OrgSettingNameEnum.AllowTradeCreate;
    case ApiOrgSettingNameEnum.IsQuotationSessionsEnabled:
      return OrgSettingNameEnum.IsQuotationSessionsEnabled;
    case ApiOrgSettingNameEnum.AllowSendToMovingPro:
      return OrgSettingNameEnum.AllowSendToMovingPro;
    case ApiOrgSettingNameEnum.MessageTemplatePostfix:
      return OrgSettingNameEnum.MessageTemplatePostfix;
    case ApiOrgSettingNameEnum.IsPriceCorridorEnabled:
      return OrgSettingNameEnum.IsPriceCorridorEnabled;
    case ApiOrgSettingNameEnum.PriceCorridorViolationEmail:
      return OrgSettingNameEnum.PriceCorridorViolationEmail;
    case ApiOrgSettingNameEnum.PriceCorridorViolationTemplateUri:
      return OrgSettingNameEnum.PriceCorridorViolationTemplateUri;
    case ApiOrgSettingNameEnum.StatisticsAndAnalyticsReportId:
      return OrgSettingNameEnum.StatisticsAndAnalyticsReportId;
    case ApiOrgSettingNameEnum.MainMenuCustomItems:
      return OrgSettingNameEnum.MainMenuCustomItems;
    case ApiOrgSettingNameEnum.OpenPartShopListParameters:
      return OrgSettingNameEnum.OpenPartShopListParameters;
    case ApiOrgSettingNameEnum.ReportRegistryTenantIds:
      return OrgSettingNameEnum.ReportRegistryTenantIds;
    case ApiOrgSettingNameEnum.ReportRegistryRegions:
      return OrgSettingNameEnum.ReportRegistryRegions;
    case ApiOrgSettingNameEnum.AllowOrderCreate:
      return OrgSettingNameEnum.AllowOrderCreate;
    case ApiOrgSettingNameEnum.InformSupplierBeforeApplicationData:
      return OrgSettingNameEnum.InformSupplierBeforeApplicationData;
    case ApiOrgSettingNameEnum.InformSupplierBeforeApplication:
      return OrgSettingNameEnum.InformSupplierBeforeApplication;
    case ApiOrgSettingNameEnum.SupplierDealDirectionFlow:
      return OrgSettingNameEnum.SupplierDealDirectionFlow;
    case ApiOrgSettingNameEnum.SendCartToExternalSystemKey:
      return OrgSettingNameEnum.SendCartToExternalSystemKey;
    case ApiOrgSettingNameEnum.ShowTradeCustomerInfo:
      return OrgSettingNameEnum.ShowTradeCustomerInfo;
    case ApiOrgSettingNameEnum.WorkDaysToAddReester:
      return OrgSettingNameEnum.WorkDaysToAddReester;
    case ApiOrgSettingNameEnum.HeaderHtml:
      return OrgSettingNameEnum.HeaderHtml;
    case ApiOrgSettingNameEnum.FillingApplicationMinimumDateCountdown:
      return OrgSettingNameEnum.FillingApplicationMinimumDateCountdown;
    case ApiOrgSettingNameEnum.CreateSingleSupplierTradeOnNotTookPlaceTrade:
      return OrgSettingNameEnum.CreateSingleSupplierTradeOnNotTookPlaceTrade;
    case ApiOrgSettingNameEnum.CanLinkNotTookPlaceTrade:
      return OrgSettingNameEnum.CanLinkNotTookPlaceTrade;
    case ApiOrgSettingNameEnum.AllowSendContractOnEtp:
      return OrgSettingNameEnum.AllowSendContractOnEtp;
    case ApiOrgSettingNameEnum.M4DDealSignRequired:
      return OrgSettingNameEnum.M4DDealSignRequired;
    case ApiOrgSettingNameEnum.AlwaysSendInvitationsForVendors:
      return OrgSettingNameEnum.AlwaysSendInvitationsForVendors;
    case ApiOrgSettingNameEnum.IsNeedEds:
      return OrgSettingNameEnum.IsNeedEds;
    case ApiOrgSettingNameEnum.ShowAppReviewDoc:
      return OrgSettingNameEnum.ShowAppReviewDoc;
    case ApiOrgSettingNameEnum.TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz:
      return OrgSettingNameEnum.TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz;
    case ApiOrgSettingNameEnum.ProlongateTradeOnceIfApplicationTermIsOverAndNoApplicationsWereSubmitted:
      return OrgSettingNameEnum.ProlongateTradeOnceIfApplicationTermIsOverAndNoApplicationsWereSubmitted;
    case ApiOrgSettingNameEnum.RetradingDuration:
      return OrgSettingNameEnum.RetradingDuration;
    case ApiOrgSettingNameEnum.FormCreateExternalDealTemplateSettings:
      return OrgSettingNameEnum.FormCreateExternalDealTemplateSettings;
    case ApiOrgSettingNameEnum.ShowHomeRegionInfoMessage:
      return OrgSettingNameEnum.ShowHomeRegionInfoMessage;
    case ApiOrgSettingNameEnum.MonetizationMarketWithoutNmz:
      return OrgSettingNameEnum.MonetizationMarketWithoutNmz;
    case ApiOrgSettingNameEnum.AutoProlongationSettings:
      return OrgSettingNameEnum.AutoProlongationSettings;
    case ApiOrgSettingNameEnum.IsTelegramEnabled:
      return OrgSettingNameEnum.IsTelegramEnabled;
    case ApiOrgSettingNameEnum.IsClarificationRequestsEnabled:
      return OrgSettingNameEnum.IsClarificationRequestsEnabled;
    case ApiOrgSettingNameEnum.IsDealAgreementEnabled:
      return OrgSettingNameEnum.IsDealAgreementEnabled;
    case ApiOrgSettingNameEnum.СommercialOfferOwnerGuid:
      return OrgSettingNameEnum.СommercialOfferOwnerGuid;
    case ApiOrgSettingNameEnum.LandingMetaDescriptionContent:
      return OrgSettingNameEnum.LandingMetaDescriptionContent;
    case ApiOrgSettingNameEnum.EnableRaiseDealPriceMoreThanApplicationPrice:
      return OrgSettingNameEnum.EnableRaiseDealPriceMoreThanApplicationPrice;
    case ApiOrgSettingNameEnum.IsEisConcludeDealRequired:
      return OrgSettingNameEnum.IsEisConcludeDealRequired;
    case ApiOrgSettingNameEnum.FormCreateApplicationTemplateSettings:
      return OrgSettingNameEnum.FormCreateApplicationTemplateSettings;
    case ApiOrgSettingNameEnum.IsDetailedMetricsEnabled:
      return OrgSettingNameEnum.IsDetailedMetricsEnabled;
    case ApiOrgSettingNameEnum.AllowFinishReviewApplications:
      return OrgSettingNameEnum.AllowFinishReviewApplications;
    case ApiOrgSettingNameEnum.AllowSendContract:
      return OrgSettingNameEnum.AllowSendContract;
    case ApiOrgSettingNameEnum.DenyEditHideApplicationSettings:
      return OrgSettingNameEnum.DenyEditHideApplicationSettings;
    case ApiOrgSettingNameEnum.IsMyPriceListsEnabled:
      return OrgSettingNameEnum.IsMyPriceListsEnabled;
    case ApiOrgSettingNameEnum.MessageKind:
      return OrgSettingNameEnum.MessageKind;
    case ApiOrgSettingNameEnum.BusinessOperatorId:
      return OrgSettingNameEnum.BusinessOperatorId;
    case ApiOrgSettingNameEnum.IsRevokeDealAllowedForWinnerSupplier:
      return OrgSettingNameEnum.IsRevokeDealAllowedForWinnerSupplier;
    case ApiOrgSettingNameEnum.FormCreatePriceListTemplateSettings:
      return OrgSettingNameEnum.FormCreatePriceListTemplateSettings;
    case ApiOrgSettingNameEnum.CommercialOfferFromOpenPartIsEnabled:
      return OrgSettingNameEnum.CommercialOfferFromOpenPartIsEnabled;
    case ApiOrgSettingNameEnum.OrderAcceptFormTemplateSettings:
      return OrgSettingNameEnum.OrderAcceptFormTemplateSettings;
    case ApiOrgSettingNameEnum.SignatureStampFormat:
      return OrgSettingNameEnum.SignatureStampFormat;
    case ApiOrgSettingNameEnum.IsImportOffersFromYMLEnabled:
      return OrgSettingNameEnum.IsImportOffersFromYMLEnabled;
    case ApiOrgSettingNameEnum.CanSendDealToEIS:
      return OrgSettingNameEnum.CanSendDealToEIS;
    case ApiOrgSettingNameEnum.AllowUserManagement:
      return OrgSettingNameEnum.AllowUserManagement;
    case ApiOrgSettingNameEnum.IsStarOkServiceEnabled:
      return OrgSettingNameEnum.IsStarOkServiceEnabled;
    case ApiOrgSettingNameEnum.CanLinkNotTookPlaceTradeOnce:
      return OrgSettingNameEnum.CanLinkNotTookPlaceTradeOnce;
    case ApiOrgSettingNameEnum.IsDealsOutOfEtpEnabled:
      return OrgSettingNameEnum.IsDealsOutOfEtpEnabled;
    default:
      throw new Error(`Enum value is not defined: ApiOrgSettingNameEnum=${String(source)}`);
  }
}
