import { ApiTradeViewDto } from '../../../swagger/models/api-trade-view-dto';
import { TradeView } from '../../models/trade-view.interface';
import { adaptAdditionalRequirementToUI } from './additional-requirement.adapter';
import { adaptCustomerContactInfoAltToUI } from './customer-contact-info-alt.adapter';
import { adaptDealStateEnumToUI } from './deal-state-enum.adapter';
import { adaptDocumentToUI } from './document.adapter';
import { adaptM4DDealSignRequiredEnumToUI } from './m-4-d-deal-sign-required-enum.adapter';
import { adaptProductToUI } from './product.adapter';
import { adaptSourcePlatformEnumToUI } from './source-platform-enum.adapter';
import { adaptStateOfIncreasingForFillingApplicationEndDateAltEnumToUI } from './state-of-increasing-for-filling-application-end-date-alt-enum.adapter';
import { adaptSuppliersListReportResultToUI } from './suppliers-list-report-result.adapter';
import { adaptTradeBusinessFlowEnumToUI } from './trade-business-flow-enum.adapter';
import { adaptTradeGroupViewToUI } from './trade-group-view.adapter';
import { adaptTradeStateEnumToUI } from './trade-state-enum.adapter';
import { adaptViewApplicationsForTradeToUI } from './view-applications-for-trade.adapter';
import { adaptZmoFinanceSourceEnumToUI } from './zmo-finance-source-enum.adapter';

export function adaptTradeViewToUI(source?: ApiTradeViewDto | null): TradeView {
  return {
    actualChildOrderId: source?.ActualChildOrderId ?? 0,
    actualChildTradeId: source?.ActualChildTradeId ?? 0,
    additionalInfo: source?.AdditionalInfo ?? '',
    additionalRequirements: (source?.AdditionalRequirements ?? []).map((item) => adaptAdditionalRequirementToUI(item)),
    applicationSet: adaptViewApplicationsForTradeToUI(source?.ApplicationSet),
    autoInvitationVendors: source?.AutoInvitationVendors ?? false,
    canBeShownOnZmo: source?.CanBeShownOnZmo ?? false,
    canCheckParticipant: source?.CanCheckParticipant ?? false,
    canDownloadApplicationsData: source?.CanDownloadApplicationsData ?? false,
    canManageApplications: source?.CanManageApplications ?? false,
    canPossibleCreateDealOutsideEShop: source?.CanPossibleCreateDealOutsideEShop ?? false,
    cancellationReason: source?.CancellationReason ?? '',
    concludeReviewApplication: source?.ConcludeReviewApplication ?? false,
    conditionsOfPayment: source?.ConditionsOfPayment ?? '',
    contactInfo: adaptCustomerContactInfoAltToUI(source?.ContactInfo),
    currentCustomerHasDealForThisTrade: source?.CurrentCustomerHasDealForThisTrade ?? false,
    currentParticipantHasDealForThisTrade: source?.CurrentParticipantHasDealForThisTrade ?? false,
    currentStageId: source?.CurrentStageId ?? 0,
    customerFullName: source?.CustomerFullName ?? '',
    customerId: source?.CustomerId ?? 0,
    customerInn: source?.CustomerInn ?? '',
    customerPhysAddress: source?.CustomerPhysAddress ?? '',
    dealExecutionDate: source?.DealExecutionDate ?? '',
    dealState: adaptDealStateEnumToUI(source?.DealState),
    defaultPriceForSignDealOutSide: source?.DefaultPriceForSignDealOutSide ?? 0,
    deliveryKladrRegionCode: source?.DeliveryKladrRegionCode ?? '',
    deliveryKladrRegionName: source?.DeliveryKladrRegionName ?? '',
    deliveryPlace: source?.DeliveryPlace ?? '',
    deliveryTerms: source?.DeliveryTerms ?? '',
    description: source?.Description ?? '',
    enableKtruCode: source?.EnableKtruCode ?? false,
    enableKtruSpecifications: source?.EnableKtruSpecifications ?? false,
    enableMonetizationZmo: source?.EnableMonetizationZmo ?? false,
    enablePositionCharacteristics: source?.EnablePositionCharacteristics ?? false,
    externalContractTemplateId: source?.ExternalContractTemplateId ?? 0,
    externalSourcePlatformNumber: source?.ExternalSourcePlatformNumber ?? '',
    externalSystemId: source?.ExternalSystemId ?? 0,
    fillingApplicationEndDate: source?.FillingApplicationEndDate ?? '',
    freeWinnerSelectionEnabled: source?.FreeWinnerSelectionEnabled ?? false,
    hasDealSignedOutsideEShop: source?.HasDealSignedOutsideEShop ?? false,
    id: source?.Id ?? 0,
    initialPrice: source?.InitialPrice ?? 0,
    isCustomerAcceptOnlyManualOffers: source?.IsCustomerAcceptOnlyManualOffers ?? false,
    isEisConcludeDealRequired: source?.IsEisConcludeDealRequired ?? false,
    isHideParticipantPrice: source?.IsHideParticipantPrice ?? false,
    isHideParticipantsApplications: source?.IsHideParticipantsApplications ?? false,
    isImmediate: source?.IsImmediate ?? false,
    isInitialPriceDefined: source?.IsInitialPriceDefined ?? false,
    isLapsed: source?.IsLapsed ?? false,
    isOnlySmp: source?.IsOnlySmp ?? false,
    isOrderCreationFromExternalNotTookPlaceTradeAvailable: source?.IsOrderCreationFromExternalNotTookPlaceTradeAvailable ?? false,
    isParentContractNumberNotSpecified: source?.IsParentContractNumberNotSpecified ?? false,
    isSendContractAllowed: source?.IsSendContractAllowed ?? false,
    isSendToNonPublicEis: source?.IsSendToNonPublicEis ?? false,
    isTradeForPartner: source?.IsTradeForPartner ?? false,
    isTradeNeedConfirmCustomerTermsWhenOffer: source?.IsTradeNeedConfirmCustomerTermsWhenOffer ?? false,
    isUnitBidding: source?.IsUnitBidding ?? false,
    isWaitingPeriodEnabled: source?.IsWaitingPeriodEnabled ?? false,
    lastModificationDate: source?.LastModificationDate ?? '',
    lotAuctionId: source?.LotAuctionId ?? 0,
    lotId: source?.LotId ?? 0,
    lotItemsSumPrice: source?.LotItemsSumPrice ?? 0,
    m4DDealSignRequired: adaptM4DDealSignRequiredEnumToUI(source?.M4DDealSignRequired),
    maxDealPrice: source?.MaxDealPrice ?? 0,
    organizerId: source?.OrganizerId ?? 0,
    organizerInn: source?.OrganizerInn ?? '',
    organizerName: source?.OrganizerName ?? '',
    organizerPhysAddress: source?.OrganizerPhysAddress ?? '',
    originTradeId: source?.OriginTradeId ?? 0,
    parentContractNumber: source?.ParentContractNumber ?? '',
    participantCanCreateApplication: source?.ParticipantCanCreateApplication ?? false,
    paymentByBankCardEnable: source?.PaymentByBankCardEnable ?? false,
    planedDealSignDate: source?.PlanedDealSignDate ?? '',
    priceWithVat: source?.PriceWithVat ?? false,
    products: (source?.Products ?? []).map((item) => adaptProductToUI(item)),
    prohibitPostingCustomerComissionProtocol: source?.ProhibitPostingCustomerComissionProtocol ?? false,
    publicationDate: source?.PublicationDate ?? '',
    readOnly: source?.ReadOnly ?? false,
    redirectOn223Url: source?.RedirectOn223Url ?? '',
    relatedOrderId: source?.RelatedOrderId ?? 0,
    resultsDeliveryType: source?.ResultsDeliveryType ?? 0,
    russianPurchaseAdvantageInfo: source?.RussianPurchaseAdvantageInfo ?? '',
    showProtocol: source?.ShowProtocol ?? false,
    sourcePlatform: adaptSourcePlatformEnumToUI(source?.SourcePlatform),
    stateOfIncreasing: adaptStateOfIncreasingForFillingApplicationEndDateAltEnumToUI(source?.StateOfIncreasing),
    supplierWithSmallBusinessRequirements: source?.SupplierWithSmallBusinessRequirements ?? false,
    supplierWithUniversalRequirements: source?.SupplierWithUniversalRequirements ?? false,
    suppliersListReportResult: adaptSuppliersListReportResultToUI(source?.SuppliersListReportResult),
    tenantId: source?.TenantId ?? 0,
    tradeBusinessFlow: adaptTradeBusinessFlowEnumToUI(source?.TradeBusinessFlow),
    tradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz: source?.TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz ?? false,
    tradeDocuments: (source?.TradeDocuments ?? []).map((item) => adaptDocumentToUI(item)),
    tradeGroups: (source?.TradeGroups ?? []).map((item) => adaptTradeGroupViewToUI(item)),
    tradeIdentificationCode: source?.TradeIdentificationCode ?? '',
    tradeName: source?.TradeName ?? '',
    tradeState: adaptTradeStateEnumToUI(source?.TradeState),
    tradeWaitingTime: source?.TradeWaitingTime ?? 0,
    zmoFinanceSource: adaptZmoFinanceSourceEnumToUI(source?.ZmoFinanceSource),
    zmoFzType: source?.ZmoFzType ?? 0,
  };
}
