import { OrgSettingNameEnum } from '../../enums/org-setting-name.enum';
import { ApiOrgSettingNameEnum } from '../../../swagger/models/api-org-setting-name-enum';

export const apiOrgSettingNameEnumAdapter = (source?: OrgSettingNameEnum | null): ApiOrgSettingNameEnum => {
  switch (source) {
    case OrgSettingNameEnum.None:
      return ApiOrgSettingNameEnum.None;
    case OrgSettingNameEnum.MaxNmz:
      return ApiOrgSettingNameEnum.MaxNmz;
    case OrgSettingNameEnum.IsChatEnable:
      return ApiOrgSettingNameEnum.IsChatEnable;
    case OrgSettingNameEnum.DealDirectionFlow:
      return ApiOrgSettingNameEnum.DealDirectionFlow;
    case OrgSettingNameEnum.IsDocumentAttachRequired:
      return ApiOrgSettingNameEnum.IsDocumentAttachRequired;
    case OrgSettingNameEnum.MaxApplicationAmount:
      return ApiOrgSettingNameEnum.MaxApplicationAmount;
    case OrgSettingNameEnum.EnableRaiseApplicationPriceMoreThanTradePrice:
      return ApiOrgSettingNameEnum.EnableRaiseApplicationPriceMoreThanTradePrice;
    case OrgSettingNameEnum.EnableShowingOtherApplicationsInTrade:
      return ApiOrgSettingNameEnum.EnableShowingOtherApplicationsInTrade;
    case OrgSettingNameEnum.EnableApplicationsDenyPriceRaise:
      return ApiOrgSettingNameEnum.EnableApplicationsDenyPriceRaise;
    case OrgSettingNameEnum.CreateApplicationLogoRelativePath:
      return ApiOrgSettingNameEnum.CreateApplicationLogoRelativePath;
    case OrgSettingNameEnum.CreateApplicationText:
      return ApiOrgSettingNameEnum.CreateApplicationText;
    case OrgSettingNameEnum.ConfigSettingObject:
      return ApiOrgSettingNameEnum.ConfigSettingObject;
    case OrgSettingNameEnum.IsDealNumberAutoGenerationEnabled:
      return ApiOrgSettingNameEnum.IsDealNumberAutoGenerationEnabled;
    case OrgSettingNameEnum.EnableMonetizationZmo:
      return ApiOrgSettingNameEnum.EnableMonetizationZmo;
    case OrgSettingNameEnum.EnableMonetizationMarket:
      return ApiOrgSettingNameEnum.EnableMonetizationMarket;
    case OrgSettingNameEnum.ExcludedBftFromTenantSearch:
      return ApiOrgSettingNameEnum.ExcludedBftFromTenantSearch;
    case OrgSettingNameEnum.ProhibitionShowOutsideTenant:
      return ApiOrgSettingNameEnum.ProhibitionShowOutsideTenant;
    case OrgSettingNameEnum.RedirectTradeUrl:
      return ApiOrgSettingNameEnum.RedirectTradeUrl;
    case OrgSettingNameEnum.TradePlanTemplateLoadMode:
      return ApiOrgSettingNameEnum.TradePlanTemplateLoadMode;
    case OrgSettingNameEnum.AutoProtocolWinnerDescription:
      return ApiOrgSettingNameEnum.AutoProtocolWinnerDescription;
    case OrgSettingNameEnum.AlwaysShowCustomerConsiderationProtocol:
      return ApiOrgSettingNameEnum.AlwaysShowCustomerConsiderationProtocol;
    case OrgSettingNameEnum.DenyTradePriceRaise:
      return ApiOrgSettingNameEnum.DenyTradePriceRaise;
    case OrgSettingNameEnum.AllowInitialPriceNotDefined:
      return ApiOrgSettingNameEnum.AllowInitialPriceNotDefined;
    case OrgSettingNameEnum.EnableZeroTariff:
      return ApiOrgSettingNameEnum.EnableZeroTariff;
    case OrgSettingNameEnum.ZeroTariffDateFrom:
      return ApiOrgSettingNameEnum.ZeroTariffDateFrom;
    case OrgSettingNameEnum.ZeroTariffDateTo:
      return ApiOrgSettingNameEnum.ZeroTariffDateTo;
    case OrgSettingNameEnum.AutoProtocolFileName:
      return ApiOrgSettingNameEnum.AutoProtocolFileName;
    case OrgSettingNameEnum.AllowPaperDealForm:
      return ApiOrgSettingNameEnum.AllowPaperDealForm;
    case OrgSettingNameEnum.ExtendedBudgetForFinancingSource:
      return ApiOrgSettingNameEnum.ExtendedBudgetForFinancingSource;
    case OrgSettingNameEnum.ShowMarketPriceLists:
      return ApiOrgSettingNameEnum.ShowMarketPriceLists;
    case OrgSettingNameEnum.RequiredTradeDocumentType:
      return ApiOrgSettingNameEnum.RequiredTradeDocumentType;
    case OrgSettingNameEnum.RequiredTradeLotApplicationDocumentType:
      return ApiOrgSettingNameEnum.RequiredTradeLotApplicationDocumentType;
    case OrgSettingNameEnum.AvailableTenant:
      return ApiOrgSettingNameEnum.AvailableTenant;
    case OrgSettingNameEnum.AvailableRegion:
      return ApiOrgSettingNameEnum.AvailableRegion;
    case OrgSettingNameEnum.ShowTradeContactInfoAndDocuments:
      return ApiOrgSettingNameEnum.ShowTradeContactInfoAndDocuments;
    case OrgSettingNameEnum.ShowBankingDetailsOnCreateApplicationForm:
      return ApiOrgSettingNameEnum.ShowBankingDetailsOnCreateApplicationForm;
    case OrgSettingNameEnum.DaysForNoticeBeforeArchive:
      return ApiOrgSettingNameEnum.DaysForNoticeBeforeArchive;
    case OrgSettingNameEnum.TariffServiceId:
      return ApiOrgSettingNameEnum.TariffServiceId;
    case OrgSettingNameEnum.IsRevokeDealAllowedForNonWinnerSupplier:
      return ApiOrgSettingNameEnum.IsRevokeDealAllowedForNonWinnerSupplier;
    case OrgSettingNameEnum.EnableTradeProtocolForCompletedDeals:
      return ApiOrgSettingNameEnum.EnableTradeProtocolForCompletedDeals;
    case OrgSettingNameEnum.EnableTradeProtocolForCanceledDeals:
      return ApiOrgSettingNameEnum.EnableTradeProtocolForCanceledDeals;
    case OrgSettingNameEnum.IsMonopolist:
      return ApiOrgSettingNameEnum.IsMonopolist;
    case OrgSettingNameEnum.NewDealSignFlowForBft:
      return ApiOrgSettingNameEnum.NewDealSignFlowForBft;
    case OrgSettingNameEnum.EnableDealRejectionReasonsList:
      return ApiOrgSettingNameEnum.EnableDealRejectionReasonsList;
    case OrgSettingNameEnum.IsFinanceSourceDisplayed:
      return ApiOrgSettingNameEnum.IsFinanceSourceDisplayed;
    case OrgSettingNameEnum.ShowTradeCustomerOnTradesGrid:
      return ApiOrgSettingNameEnum.ShowTradeCustomerOnTradesGrid;
    case OrgSettingNameEnum.IsCommercialOffersAvailable:
      return ApiOrgSettingNameEnum.IsCommercialOffersAvailable;
    case OrgSettingNameEnum.AllowToCreateAdditionalAgreement:
      return ApiOrgSettingNameEnum.AllowToCreateAdditionalAgreement;
    case OrgSettingNameEnum.CreateApplicationFromMarket:
      return ApiOrgSettingNameEnum.CreateApplicationFromMarket;
    case OrgSettingNameEnum.SendNotificationsAboutTradesOnlyToMarket:
      return ApiOrgSettingNameEnum.SendNotificationsAboutTradesOnlyToMarket;
    case OrgSettingNameEnum.ShowEventLogs:
      return ApiOrgSettingNameEnum.ShowEventLogs;
    case OrgSettingNameEnum.OrganizationsForSyncExternalRoles:
      return ApiOrgSettingNameEnum.OrganizationsForSyncExternalRoles;
    case OrgSettingNameEnum.TenantCssThemeName:
      return ApiOrgSettingNameEnum.TenantCssThemeName;
    case OrgSettingNameEnum.CanSendTradeToEIS:
      return ApiOrgSettingNameEnum.CanSendTradeToEIS;
    case OrgSettingNameEnum.ShowIsImportPhaseout:
      return ApiOrgSettingNameEnum.ShowIsImportPhaseout;
    case OrgSettingNameEnum.CanMakePurchasesPP2323OnTheAmendmentPP1352:
      return ApiOrgSettingNameEnum.CanMakePurchasesPP2323OnTheAmendmentPP1352;
    case OrgSettingNameEnum.IsOfferModerationEnable:
      return ApiOrgSettingNameEnum.IsOfferModerationEnable;
    case OrgSettingNameEnum.IsCartEnable:
      return ApiOrgSettingNameEnum.IsCartEnable;
    case OrgSettingNameEnum.IsChangeSingleSupplierTradeToPriceRequest:
      return ApiOrgSettingNameEnum.IsChangeSingleSupplierTradeToPriceRequest;
    case OrgSettingNameEnum.IsPassportAuthEnable:
      return ApiOrgSettingNameEnum.IsPassportAuthEnable;
    case OrgSettingNameEnum.IsManagersNotificationsEnabled:
      return ApiOrgSettingNameEnum.IsManagersNotificationsEnabled;
    case OrgSettingNameEnum.AllowTradeUpdate:
      return ApiOrgSettingNameEnum.AllowTradeUpdate;
    case OrgSettingNameEnum.AllowTradeCancel:
      return ApiOrgSettingNameEnum.AllowTradeCancel;
    case OrgSettingNameEnum.ParticipantOfferSourceVisibilitySettings:
      return ApiOrgSettingNameEnum.ParticipantOfferSourceVisibilitySettings;
    case OrgSettingNameEnum.ParticipantLoginRedirectTenant:
      return ApiOrgSettingNameEnum.ParticipantLoginRedirectTenant;
    case OrgSettingNameEnum.Is223AuthEnabled:
      return ApiOrgSettingNameEnum.Is223AuthEnabled;
    case OrgSettingNameEnum.IsMoAuthEnabled:
      return ApiOrgSettingNameEnum.IsMoAuthEnabled;
    case OrgSettingNameEnum.IsTableEditingModeEnabled:
      return ApiOrgSettingNameEnum.IsTableEditingModeEnabled;
    case OrgSettingNameEnum.IsZeroSingleSupplierTradeEnabled:
      return ApiOrgSettingNameEnum.IsZeroSingleSupplierTradeEnabled;
    case OrgSettingNameEnum.IsOfferContentComplaintsEnabled:
      return ApiOrgSettingNameEnum.IsOfferContentComplaintsEnabled;
    case OrgSettingNameEnum.IsImportSubstitutionRegistryEnabled:
      return ApiOrgSettingNameEnum.IsImportSubstitutionRegistryEnabled;
    case OrgSettingNameEnum.IsCatalogEnabled:
      return ApiOrgSettingNameEnum.IsCatalogEnabled;
    case OrgSettingNameEnum.IsCatalogSideFilterEnabled:
      return ApiOrgSettingNameEnum.IsCatalogSideFilterEnabled;
    case OrgSettingNameEnum.IsCatalogMenuSectionEnabled:
      return ApiOrgSettingNameEnum.IsCatalogMenuSectionEnabled;
    case OrgSettingNameEnum.IsOfferManualEditingEnabled:
      return ApiOrgSettingNameEnum.IsOfferManualEditingEnabled;
    case OrgSettingNameEnum.IsStoriesEnabled:
      return ApiOrgSettingNameEnum.IsStoriesEnabled;
    case OrgSettingNameEnum.OrdersSideFilterStructure:
      return ApiOrgSettingNameEnum.OrdersSideFilterStructure;
    case OrgSettingNameEnum.PriceListsSideFilterStructure:
      return ApiOrgSettingNameEnum.PriceListsSideFilterStructure;
    case OrgSettingNameEnum.HideProtocolForTradeWithSentToEis:
      return ApiOrgSettingNameEnum.HideProtocolForTradeWithSentToEis;
    case OrgSettingNameEnum.ShowProtocolForTradeWithApplicationEndDateWithoutSentToEis:
      return ApiOrgSettingNameEnum.ShowProtocolForTradeWithApplicationEndDateWithoutSentToEis;
    case OrgSettingNameEnum.ShowProtocolForTradeWithoutApplicationEndDateWithoutSentToEis:
      return ApiOrgSettingNameEnum.ShowProtocolForTradeWithoutApplicationEndDateWithoutSentToEis;
    case OrgSettingNameEnum.IsManufacturerEnabled:
      return ApiOrgSettingNameEnum.IsManufacturerEnabled;
    case OrgSettingNameEnum.AutomaticallyDetermineTradePurchaseMethodForEis:
      return ApiOrgSettingNameEnum.AutomaticallyDetermineTradePurchaseMethodForEis;
    case OrgSettingNameEnum.ShowFilterByGuaranteedSuppliers:
      return ApiOrgSettingNameEnum.ShowFilterByGuaranteedSuppliers;
    case OrgSettingNameEnum.IsTradeIdentificationCodeRequired:
      return ApiOrgSettingNameEnum.IsTradeIdentificationCodeRequired;
    case OrgSettingNameEnum.FillingApplicationsMinTimeForImmediateTrades:
      return ApiOrgSettingNameEnum.FillingApplicationsMinTimeForImmediateTrades;
    case OrgSettingNameEnum.EnableDealRejectReasonComment:
      return ApiOrgSettingNameEnum.EnableDealRejectReasonComment;
    case OrgSettingNameEnum.HidedSection:
      return ApiOrgSettingNameEnum.HidedSection;
    case OrgSettingNameEnum.SupplierHiddenSections:
      return ApiOrgSettingNameEnum.SupplierHiddenSections;
    case OrgSettingNameEnum.IsDealSeparateAttachement:
      return ApiOrgSettingNameEnum.IsDealSeparateAttachement;
    case OrgSettingNameEnum.AllowWorkGroups:
      return ApiOrgSettingNameEnum.AllowWorkGroups;
    case OrgSettingNameEnum.EnablePositionCharacteristics:
      return ApiOrgSettingNameEnum.EnablePositionCharacteristics;
    case OrgSettingNameEnum.IsCustomerIsSubjectToSanctions:
      return ApiOrgSettingNameEnum.IsCustomerIsSubjectToSanctions;
    case OrgSettingNameEnum.ProhibitPostingCustomerComissionProtocol:
      return ApiOrgSettingNameEnum.ProhibitPostingCustomerComissionProtocol;
    case OrgSettingNameEnum.AvailableOfferTenant:
      return ApiOrgSettingNameEnum.AvailableOfferTenant;
    case OrgSettingNameEnum.HomeRegion:
      return ApiOrgSettingNameEnum.HomeRegion;
    case OrgSettingNameEnum.ShowOnlyHomeRegion:
      return ApiOrgSettingNameEnum.ShowOnlyHomeRegion;
    case OrgSettingNameEnum.ParticipantOfferRedirectTenant:
      return ApiOrgSettingNameEnum.ParticipantOfferRedirectTenant;
    case OrgSettingNameEnum.DealNegotiation:
      return ApiOrgSettingNameEnum.DealNegotiation;
    case OrgSettingNameEnum.IsPositionalComparisonEnable:
      return ApiOrgSettingNameEnum.IsPositionalComparisonEnable;
    case OrgSettingNameEnum.IsCustomerAcceptOnlyManualOffers:
      return ApiOrgSettingNameEnum.IsCustomerAcceptOnlyManualOffers;
    case OrgSettingNameEnum.IsTradeNeedConfirmCustomerTermsWhenOffer:
      return ApiOrgSettingNameEnum.IsTradeNeedConfirmCustomerTermsWhenOffer;
    case OrgSettingNameEnum.HideApplicationDataOpenPartMode:
      return ApiOrgSettingNameEnum.HideApplicationDataOpenPartMode;
    case OrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForOpenPart:
      return ApiOrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForOpenPart;
    case OrgSettingNameEnum.HiddenApplicationParameterOpenPart:
      return ApiOrgSettingNameEnum.HiddenApplicationParameterOpenPart;
    case OrgSettingNameEnum.HideApplicationDataForParticipantMode:
      return ApiOrgSettingNameEnum.HideApplicationDataForParticipantMode;
    case OrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForParticipant:
      return ApiOrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForParticipant;
    case OrgSettingNameEnum.HiddenApplicationParameterForParticipant:
      return ApiOrgSettingNameEnum.HiddenApplicationParameterForParticipant;
    case OrgSettingNameEnum.HideApplicationDataForCustomerMode:
      return ApiOrgSettingNameEnum.HideApplicationDataForCustomerMode;
    case OrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForCustomer:
      return ApiOrgSettingNameEnum.HideForCertainMinutesBeforeEndFilingApplicationsForCustomer;
    case OrgSettingNameEnum.HiddenApplicationParameterForCustomer:
      return ApiOrgSettingNameEnum.HiddenApplicationParameterForCustomer;
    case OrgSettingNameEnum.RegionalProductSignTitle:
      return ApiOrgSettingNameEnum.RegionalProductSignTitle;
    case OrgSettingNameEnum.RegionalProductSignFileGuid:
      return ApiOrgSettingNameEnum.RegionalProductSignFileGuid;
    case OrgSettingNameEnum.RegionalProductSignAvailabilityType:
      return ApiOrgSettingNameEnum.RegionalProductSignAvailabilityType;
    case OrgSettingNameEnum.IsOosNonPublic:
      return ApiOrgSettingNameEnum.IsOosNonPublic;
    case OrgSettingNameEnum.IsSendDifferencesProtocolOnlyOneTimes:
      return ApiOrgSettingNameEnum.IsSendDifferencesProtocolOnlyOneTimes;
    case OrgSettingNameEnum.IsPublishTradeOnGlobalMarketAfterProlongation:
      return ApiOrgSettingNameEnum.IsPublishTradeOnGlobalMarketAfterProlongation;
    case OrgSettingNameEnum.IsGufsin:
      return ApiOrgSettingNameEnum.IsGufsin;
    case OrgSettingNameEnum.WrongContractExecutionListUrl:
      return ApiOrgSettingNameEnum.WrongContractExecutionListUrl;
    case OrgSettingNameEnum.WrongContractExecutionInsertUrl:
      return ApiOrgSettingNameEnum.WrongContractExecutionInsertUrl;
    case OrgSettingNameEnum.IsAvailableSelectOnlyOneOfferForItem:
      return ApiOrgSettingNameEnum.IsAvailableSelectOnlyOneOfferForItem;
    case OrgSettingNameEnum.IsSingleWinnerRequired:
      return ApiOrgSettingNameEnum.IsSingleWinnerRequired;
    case OrgSettingNameEnum.IsAutoCreateDealAfterReviewApplications:
      return ApiOrgSettingNameEnum.IsAutoCreateDealAfterReviewApplications;
    case OrgSettingNameEnum.IsSortApplicationsByPriceWithoutVat:
      return ApiOrgSettingNameEnum.IsSortApplicationsByPriceWithoutVat;
    case OrgSettingNameEnum.KeepGuaranteeForParticipantsCount:
      return ApiOrgSettingNameEnum.KeepGuaranteeForParticipantsCount;
    case OrgSettingNameEnum.IsWorkWithDealsOn223:
      return ApiOrgSettingNameEnum.IsWorkWithDealsOn223;
    case OrgSettingNameEnum.IsSalesTechAuthEnable:
      return ApiOrgSettingNameEnum.IsSalesTechAuthEnable;
    case OrgSettingNameEnum.GeneratePriceJustificationFile:
      return ApiOrgSettingNameEnum.GeneratePriceJustificationFile;
    case OrgSettingNameEnum.IsPositionCharacteristicsEditable:
      return ApiOrgSettingNameEnum.IsPositionCharacteristicsEditable;
    case OrgSettingNameEnum.EnableKtruSpecifications:
      return ApiOrgSettingNameEnum.EnableKtruSpecifications;
    case OrgSettingNameEnum.RegionalProductSignText:
      return ApiOrgSettingNameEnum.RegionalProductSignText;
    case OrgSettingNameEnum.IsContractTemplatePassingEnabled:
      return ApiOrgSettingNameEnum.IsContractTemplatePassingEnabled;
    case OrgSettingNameEnum.AllowPartnerAsCustomer:
      return ApiOrgSettingNameEnum.AllowPartnerAsCustomer;
    case OrgSettingNameEnum.TradeCreateRedirectTenant:
      return ApiOrgSettingNameEnum.TradeCreateRedirectTenant;
    case OrgSettingNameEnum.AllowEditPublishedTrade:
      return ApiOrgSettingNameEnum.AllowEditPublishedTrade;
    case OrgSettingNameEnum.AllowSpeedUpTrade:
      return ApiOrgSettingNameEnum.AllowSpeedUpTrade;
    case OrgSettingNameEnum.FederalLawLimit:
      return ApiOrgSettingNameEnum.FederalLawLimit;
    case OrgSettingNameEnum.AllowApplicationReject:
      return ApiOrgSettingNameEnum.AllowApplicationReject;
    case OrgSettingNameEnum.IsSendCartToExternalSystemsEnabled:
      return ApiOrgSettingNameEnum.IsSendCartToExternalSystemsEnabled;
    case OrgSettingNameEnum.IsPositionalVatEnable:
      return ApiOrgSettingNameEnum.IsPositionalVatEnable;
    case OrgSettingNameEnum.AllowDeliveryPlaceAndTermsNotDefined:
      return ApiOrgSettingNameEnum.AllowDeliveryPlaceAndTermsNotDefined;
    case OrgSettingNameEnum.DefaultPriceListName:
      return ApiOrgSettingNameEnum.DefaultPriceListName;
    case OrgSettingNameEnum.AllowPublishApplicationWithoutFullName:
      return ApiOrgSettingNameEnum.AllowPublishApplicationWithoutFullName;
    case OrgSettingNameEnum.IsStarMorphSearchEnabled:
      return ApiOrgSettingNameEnum.IsStarMorphSearchEnabled;
    case OrgSettingNameEnum.IsStarOfferMorphSearchEnabled:
      return ApiOrgSettingNameEnum.IsStarOfferMorphSearchEnabled;
    case OrgSettingNameEnum.AvailableTenantSell:
      return ApiOrgSettingNameEnum.AvailableTenantSell;
    case OrgSettingNameEnum.IsImportPositionsFromExcelEnabled:
      return ApiOrgSettingNameEnum.IsImportPositionsFromExcelEnabled;
    case OrgSettingNameEnum.ImportExcelTemplateType:
      return ApiOrgSettingNameEnum.ImportExcelTemplateType;
    case OrgSettingNameEnum.EnableExternalDealMarket:
      return ApiOrgSettingNameEnum.EnableExternalDealMarket;
    case OrgSettingNameEnum.AutoProtocolShowSettings:
      return ApiOrgSettingNameEnum.AutoProtocolShowSettings;
    case OrgSettingNameEnum.IsReportsByWorkGroupEnabled:
      return ApiOrgSettingNameEnum.IsReportsByWorkGroupEnabled;
    case OrgSettingNameEnum.UseTradeTenantHostToGenerateNotificationLinks:
      return ApiOrgSettingNameEnum.UseTradeTenantHostToGenerateNotificationLinks;
    case OrgSettingNameEnum.IsLotItemOKPD2Required:
      return ApiOrgSettingNameEnum.IsLotItemOKPD2Required;
    case OrgSettingNameEnum.CustomProtocolShowSettings:
      return ApiOrgSettingNameEnum.CustomProtocolShowSettings;
    case OrgSettingNameEnum.MessengerEtp:
      return ApiOrgSettingNameEnum.MessengerEtp;
    case OrgSettingNameEnum.IsLandingSwitchEnabled:
      return ApiOrgSettingNameEnum.IsLandingSwitchEnabled;
    case OrgSettingNameEnum.LandingBannerForCustomerLargeText:
      return ApiOrgSettingNameEnum.LandingBannerForCustomerLargeText;
    case OrgSettingNameEnum.LandingBannerForCustomerSmallText:
      return ApiOrgSettingNameEnum.LandingBannerForCustomerSmallText;
    case OrgSettingNameEnum.LandingBannerForSupplierLargeText:
      return ApiOrgSettingNameEnum.LandingBannerForSupplierLargeText;
    case OrgSettingNameEnum.LandingBannerForSupplierSmallText:
      return ApiOrgSettingNameEnum.LandingBannerForSupplierSmallText;
    case OrgSettingNameEnum.LandingSchemeColorName:
      return ApiOrgSettingNameEnum.LandingSchemeColorName;
    case OrgSettingNameEnum.LandingYandexMetrikaCode:
      return ApiOrgSettingNameEnum.LandingYandexMetrikaCode;
    case OrgSettingNameEnum.TenantAdminHost:
      return ApiOrgSettingNameEnum.TenantAdminHost;
    case OrgSettingNameEnum.FillingApplicationsMinDays:
      return ApiOrgSettingNameEnum.FillingApplicationsMinDays;
    case OrgSettingNameEnum.RequiredDeclaration44Fz:
      return ApiOrgSettingNameEnum.RequiredDeclaration44Fz;
    case OrgSettingNameEnum.FormCreateTradeTemplateSettings:
      return ApiOrgSettingNameEnum.FormCreateTradeTemplateSettings;
    case OrgSettingNameEnum.CustomerRegulationFileGuid:
      return ApiOrgSettingNameEnum.CustomerRegulationFileGuid;
    case OrgSettingNameEnum.IsCustomerRegulationFileDisplayed:
      return ApiOrgSettingNameEnum.IsCustomerRegulationFileDisplayed;
    case OrgSettingNameEnum.SupplierDealSigningWorkingDays:
      return ApiOrgSettingNameEnum.SupplierDealSigningWorkingDays;
    case OrgSettingNameEnum.FormCreateOrderTemplateSettings:
      return ApiOrgSettingNameEnum.FormCreateOrderTemplateSettings;
    case OrgSettingNameEnum.CemIntegrationEnabled:
      return ApiOrgSettingNameEnum.CemIntegrationEnabled;
    case OrgSettingNameEnum.TradeViewFormTemplateSettings:
      return ApiOrgSettingNameEnum.TradeViewFormTemplateSettings;
    case OrgSettingNameEnum.InstructionFileGuid:
      return ApiOrgSettingNameEnum.InstructionFileGuid;
    case OrgSettingNameEnum.AllowTradeCreate:
      return ApiOrgSettingNameEnum.AllowTradeCreate;
    case OrgSettingNameEnum.IsQuotationSessionsEnabled:
      return ApiOrgSettingNameEnum.IsQuotationSessionsEnabled;
    case OrgSettingNameEnum.AllowSendToMovingPro:
      return ApiOrgSettingNameEnum.AllowSendToMovingPro;
    case OrgSettingNameEnum.MessageTemplatePostfix:
      return ApiOrgSettingNameEnum.MessageTemplatePostfix;
    case OrgSettingNameEnum.IsPriceCorridorEnabled:
      return ApiOrgSettingNameEnum.IsPriceCorridorEnabled;
    case OrgSettingNameEnum.PriceCorridorViolationEmail:
      return ApiOrgSettingNameEnum.PriceCorridorViolationEmail;
    case OrgSettingNameEnum.PriceCorridorViolationTemplateUri:
      return ApiOrgSettingNameEnum.PriceCorridorViolationTemplateUri;
    case OrgSettingNameEnum.StatisticsAndAnalyticsReportId:
      return ApiOrgSettingNameEnum.StatisticsAndAnalyticsReportId;
    case OrgSettingNameEnum.MainMenuCustomItems:
      return ApiOrgSettingNameEnum.MainMenuCustomItems;
    case OrgSettingNameEnum.OpenPartShopListParameters:
      return ApiOrgSettingNameEnum.OpenPartShopListParameters;
    case OrgSettingNameEnum.ReportRegistryTenantIds:
      return ApiOrgSettingNameEnum.ReportRegistryTenantIds;
    case OrgSettingNameEnum.ReportRegistryRegions:
      return ApiOrgSettingNameEnum.ReportRegistryRegions;
    case OrgSettingNameEnum.AllowOrderCreate:
      return ApiOrgSettingNameEnum.AllowOrderCreate;
    case OrgSettingNameEnum.InformSupplierBeforeApplicationData:
      return ApiOrgSettingNameEnum.InformSupplierBeforeApplicationData;
    case OrgSettingNameEnum.InformSupplierBeforeApplication:
      return ApiOrgSettingNameEnum.InformSupplierBeforeApplication;
    case OrgSettingNameEnum.SupplierDealDirectionFlow:
      return ApiOrgSettingNameEnum.SupplierDealDirectionFlow;
    case OrgSettingNameEnum.SendCartToExternalSystemKey:
      return ApiOrgSettingNameEnum.SendCartToExternalSystemKey;
    case OrgSettingNameEnum.ShowTradeCustomerInfo:
      return ApiOrgSettingNameEnum.ShowTradeCustomerInfo;
    case OrgSettingNameEnum.WorkDaysToAddReester:
      return ApiOrgSettingNameEnum.WorkDaysToAddReester;
    case OrgSettingNameEnum.HeaderHtml:
      return ApiOrgSettingNameEnum.HeaderHtml;
    case OrgSettingNameEnum.FillingApplicationMinimumDateCountdown:
      return ApiOrgSettingNameEnum.FillingApplicationMinimumDateCountdown;
    case OrgSettingNameEnum.CreateSingleSupplierTradeOnNotTookPlaceTrade:
      return ApiOrgSettingNameEnum.CreateSingleSupplierTradeOnNotTookPlaceTrade;
    case OrgSettingNameEnum.CanLinkNotTookPlaceTrade:
      return ApiOrgSettingNameEnum.CanLinkNotTookPlaceTrade;
    case OrgSettingNameEnum.AllowSendContractOnEtp:
      return ApiOrgSettingNameEnum.AllowSendContractOnEtp;
    case OrgSettingNameEnum.M4DDealSignRequired:
      return ApiOrgSettingNameEnum.M4DDealSignRequired;
    case OrgSettingNameEnum.AlwaysSendInvitationsForVendors:
      return ApiOrgSettingNameEnum.AlwaysSendInvitationsForVendors;
    case OrgSettingNameEnum.IsNeedEds:
      return ApiOrgSettingNameEnum.IsNeedEds;
    case OrgSettingNameEnum.ShowAppReviewDoc:
      return ApiOrgSettingNameEnum.ShowAppReviewDoc;
    case OrgSettingNameEnum.TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz:
      return ApiOrgSettingNameEnum.TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz;
    case OrgSettingNameEnum.ProlongateTradeOnceIfApplicationTermIsOverAndNoApplicationsWereSubmitted:
      return ApiOrgSettingNameEnum.ProlongateTradeOnceIfApplicationTermIsOverAndNoApplicationsWereSubmitted;
    case OrgSettingNameEnum.RetradingDuration:
      return ApiOrgSettingNameEnum.RetradingDuration;
    case OrgSettingNameEnum.FormCreateExternalDealTemplateSettings:
      return ApiOrgSettingNameEnum.FormCreateExternalDealTemplateSettings;
    case OrgSettingNameEnum.ShowHomeRegionInfoMessage:
      return ApiOrgSettingNameEnum.ShowHomeRegionInfoMessage;
    case OrgSettingNameEnum.MonetizationMarketWithoutNmz:
      return ApiOrgSettingNameEnum.MonetizationMarketWithoutNmz;
    case OrgSettingNameEnum.AutoProlongationSettings:
      return ApiOrgSettingNameEnum.AutoProlongationSettings;
    case OrgSettingNameEnum.IsTelegramEnabled:
      return ApiOrgSettingNameEnum.IsTelegramEnabled;
    case OrgSettingNameEnum.IsClarificationRequestsEnabled:
      return ApiOrgSettingNameEnum.IsClarificationRequestsEnabled;
    case OrgSettingNameEnum.IsDealAgreementEnabled:
      return ApiOrgSettingNameEnum.IsDealAgreementEnabled;
    case OrgSettingNameEnum.СommercialOfferOwnerGuid:
      return ApiOrgSettingNameEnum.СommercialOfferOwnerGuid;
    case OrgSettingNameEnum.LandingMetaDescriptionContent:
      return ApiOrgSettingNameEnum.LandingMetaDescriptionContent;
    case OrgSettingNameEnum.EnableRaiseDealPriceMoreThanApplicationPrice:
      return ApiOrgSettingNameEnum.EnableRaiseDealPriceMoreThanApplicationPrice;
    case OrgSettingNameEnum.IsEisConcludeDealRequired:
      return ApiOrgSettingNameEnum.IsEisConcludeDealRequired;
    case OrgSettingNameEnum.FormCreateApplicationTemplateSettings:
      return ApiOrgSettingNameEnum.FormCreateApplicationTemplateSettings;
    case OrgSettingNameEnum.IsDetailedMetricsEnabled:
      return ApiOrgSettingNameEnum.IsDetailedMetricsEnabled;
    case OrgSettingNameEnum.AllowFinishReviewApplications:
      return ApiOrgSettingNameEnum.AllowFinishReviewApplications;
    case OrgSettingNameEnum.AllowSendContract:
      return ApiOrgSettingNameEnum.AllowSendContract;
    case OrgSettingNameEnum.DenyEditHideApplicationSettings:
      return ApiOrgSettingNameEnum.DenyEditHideApplicationSettings;
    case OrgSettingNameEnum.IsMyPriceListsEnabled:
      return ApiOrgSettingNameEnum.IsMyPriceListsEnabled;
    case OrgSettingNameEnum.MessageKind:
      return ApiOrgSettingNameEnum.MessageKind;
    case OrgSettingNameEnum.BusinessOperatorId:
      return ApiOrgSettingNameEnum.BusinessOperatorId;
    case OrgSettingNameEnum.IsRevokeDealAllowedForWinnerSupplier:
      return ApiOrgSettingNameEnum.IsRevokeDealAllowedForWinnerSupplier;
    case OrgSettingNameEnum.FormCreatePriceListTemplateSettings:
      return ApiOrgSettingNameEnum.FormCreatePriceListTemplateSettings;
    case OrgSettingNameEnum.CommercialOfferFromOpenPartIsEnabled:
      return ApiOrgSettingNameEnum.CommercialOfferFromOpenPartIsEnabled;
    case OrgSettingNameEnum.OrderAcceptFormTemplateSettings:
      return ApiOrgSettingNameEnum.OrderAcceptFormTemplateSettings;
    case OrgSettingNameEnum.SignatureStampFormat:
      return ApiOrgSettingNameEnum.SignatureStampFormat;
    case OrgSettingNameEnum.IsImportOffersFromYMLEnabled:
      return ApiOrgSettingNameEnum.IsImportOffersFromYMLEnabled;
    case OrgSettingNameEnum.CanSendDealToEIS:
      return ApiOrgSettingNameEnum.CanSendDealToEIS;
    case OrgSettingNameEnum.AllowUserManagement:
      return ApiOrgSettingNameEnum.AllowUserManagement;
    case OrgSettingNameEnum.IsStarOkServiceEnabled:
      return ApiOrgSettingNameEnum.IsStarOkServiceEnabled;
    case OrgSettingNameEnum.CanLinkNotTookPlaceTradeOnce:
      return ApiOrgSettingNameEnum.CanLinkNotTookPlaceTradeOnce;
    case OrgSettingNameEnum.IsDealsOutOfEtpEnabled:
      return ApiOrgSettingNameEnum.IsDealsOutOfEtpEnabled;
    default:
      throw new Error(`Enum value is not defined: OrgSettingNameEnum=${String(source)}`);
  }
}
