import { NotificationTypeEnum } from '../../enums/notification-type.enum';
import { ApiNotificationTypeEnum } from '../../../swagger/models/api-notification-type-enum';

export const apiNotificationTypeEnumAdapter = (source?: NotificationTypeEnum | null): ApiNotificationTypeEnum => {
  switch (source) {
    case NotificationTypeEnum.ParticipantRegistrationPassedInSystem:
      return ApiNotificationTypeEnum.ParticipantRegistrationPassedInSystem;
    case NotificationTypeEnum.ImmediateTradeOfInterestOfParticipantPublished:
      return ApiNotificationTypeEnum.ImmediateTradeOfInterestOfParticipantPublished;
    case NotificationTypeEnum.TradeOfInterestOfParticipantPublished:
      return ApiNotificationTypeEnum.TradeOfInterestOfParticipantPublished;
    case NotificationTypeEnum.TradeWithParticipantsApplicationWasEdited:
      return ApiNotificationTypeEnum.TradeWithParticipantsApplicationWasEdited;
    case NotificationTypeEnum.TradeWithParticipantsApplicationWasRevoked:
      return ApiNotificationTypeEnum.TradeWithParticipantsApplicationWasRevoked;
    case NotificationTypeEnum.ParticipantPublishApplicationForTrade:
      return ApiNotificationTypeEnum.ParticipantPublishApplicationForTrade;
    case NotificationTypeEnum.ParticipantEditedApplication:
      return ApiNotificationTypeEnum.ParticipantEditedApplication;
    case NotificationTypeEnum.ApplicationWasRevokedFromTrade:
      return ApiNotificationTypeEnum.ApplicationWasRevokedFromTrade;
    case NotificationTypeEnum.CustomerConcludeDealOutsideEShop:
      return ApiNotificationTypeEnum.CustomerConcludeDealOutsideEShop;
    case NotificationTypeEnum.CustomerConcludeOrderDealOutsideEShop:
      return ApiNotificationTypeEnum.CustomerConcludeOrderDealOutsideEShop;
    case NotificationTypeEnum.CustomerSendDealForSign:
      return ApiNotificationTypeEnum.CustomerSendDealForSign;
    case NotificationTypeEnum.CustomerSendOrderDealForSign:
      return ApiNotificationTypeEnum.CustomerSendOrderDealForSign;
    case NotificationTypeEnum.ApplicationNotMeetRequierments:
      return ApiNotificationTypeEnum.ApplicationNotMeetRequierments;
    case NotificationTypeEnum.CustomerRejectDealAfterParticipantSign:
      return ApiNotificationTypeEnum.CustomerRejectDealAfterParticipantSign;
    case NotificationTypeEnum.CustomerRejectOrderDealAfterParticipantSign:
      return ApiNotificationTypeEnum.CustomerRejectOrderDealAfterParticipantSign;
    case NotificationTypeEnum.ApplicationWasCreatedByCustomerForParticipant:
      return ApiNotificationTypeEnum.ApplicationWasCreatedByCustomerForParticipant;
    case NotificationTypeEnum.CustomerClosedTradeWithoutSigningDeal:
      return ApiNotificationTypeEnum.CustomerClosedTradeWithoutSigningDeal;
    case NotificationTypeEnum.NewTradePublished:
      return ApiNotificationTypeEnum.NewTradePublished;
    case NotificationTypeEnum.TradeWasEdited:
      return ApiNotificationTypeEnum.TradeWasEdited;
    case NotificationTypeEnum.TradeWasRevoked:
      return ApiNotificationTypeEnum.TradeWasRevoked;
    case NotificationTypeEnum.NewApplicationForTradePublished:
      return ApiNotificationTypeEnum.NewApplicationForTradePublished;
    case NotificationTypeEnum.NewApplicationForTradeEdited:
      return ApiNotificationTypeEnum.NewApplicationForTradeEdited;
    case NotificationTypeEnum.ParticipantRevokeApplicationFromTrade:
      return ApiNotificationTypeEnum.ParticipantRevokeApplicationFromTrade;
    case NotificationTypeEnum.FillingApplicationTimeFinishedWithMoreThenOneApplication:
      return ApiNotificationTypeEnum.FillingApplicationTimeFinishedWithMoreThenOneApplication;
    case NotificationTypeEnum.TradeNotNookPlace:
      return ApiNotificationTypeEnum.TradeNotNookPlace;
    case NotificationTypeEnum.TradeIncreasedWhenNotTookPlace:
      return ApiNotificationTypeEnum.TradeIncreasedWhenNotTookPlace;
    case NotificationTypeEnum.CustomerAddDealInformationToSystem:
      return ApiNotificationTypeEnum.CustomerAddDealInformationToSystem;
    case NotificationTypeEnum.CustomerAddOrderDealInformationToSystem:
      return ApiNotificationTypeEnum.CustomerAddOrderDealInformationToSystem;
    case NotificationTypeEnum.DealSendToParticipant:
      return ApiNotificationTypeEnum.DealSendToParticipant;
    case NotificationTypeEnum.OrderDealSendToParticipant:
      return ApiNotificationTypeEnum.OrderDealSendToParticipant;
    case NotificationTypeEnum.DealSignedByParticipant:
      return ApiNotificationTypeEnum.DealSignedByParticipant;
    case NotificationTypeEnum.OrderDealSignedByParticipant:
      return ApiNotificationTypeEnum.OrderDealSignedByParticipant;
    case NotificationTypeEnum.DealConcludedAfterCustomerSign:
      return ApiNotificationTypeEnum.DealConcludedAfterCustomerSign;
    case NotificationTypeEnum.OrderDealConcludedAfterCustomerSign:
      return ApiNotificationTypeEnum.OrderDealConcludedAfterCustomerSign;
    case NotificationTypeEnum.CustomerRejectDeal:
      return ApiNotificationTypeEnum.CustomerRejectDeal;
    case NotificationTypeEnum.CustomerRejectOrderDeal:
      return ApiNotificationTypeEnum.CustomerRejectOrderDeal;
    case NotificationTypeEnum.ParticipantRejectDealForParticipant:
      return ApiNotificationTypeEnum.ParticipantRejectDealForParticipant;
    case NotificationTypeEnum.ParticipantRejectOrderDealForParticipant:
      return ApiNotificationTypeEnum.ParticipantRejectOrderDealForParticipant;
    case NotificationTypeEnum.ParticipantRejectDealForCustomer:
      return ApiNotificationTypeEnum.ParticipantRejectDealForCustomer;
    case NotificationTypeEnum.ParticipantRejectOrderDealForCustomer:
      return ApiNotificationTypeEnum.ParticipantRejectOrderDealForCustomer;
    case NotificationTypeEnum.TradeFillingApplicationEndDateWasIncreasedBecauseAllApplicationsDoNotMeetRequirementsForParticipant:
      return ApiNotificationTypeEnum.TradeFillingApplicationEndDateWasIncreasedBecauseAllApplicationsDoNotMeetRequirementsForParticipant;
    case NotificationTypeEnum.TradeWasClosedWithoutSigningDeal:
      return ApiNotificationTypeEnum.TradeWasClosedWithoutSigningDeal;
    case NotificationTypeEnum.ApplicationWasCreatedForParticipant:
      return ApiNotificationTypeEnum.ApplicationWasCreatedForParticipant;
    case NotificationTypeEnum.ParticipantSuggestedToSignPaperDealForCustomer:
      return ApiNotificationTypeEnum.ParticipantSuggestedToSignPaperDealForCustomer;
    case NotificationTypeEnum.ParticipantSuggestedToSignPaperOrderDealForCustomer:
      return ApiNotificationTypeEnum.ParticipantSuggestedToSignPaperOrderDealForCustomer;
    case NotificationTypeEnum.OrgAdminRightsAssignedToUserAfterRegistration:
      return ApiNotificationTypeEnum.OrgAdminRightsAssignedToUserAfterRegistration;
    case NotificationTypeEnum.OrderSentToParticipant:
      return ApiNotificationTypeEnum.OrderSentToParticipant;
    case NotificationTypeEnum.OrderApprovedByParticipant:
      return ApiNotificationTypeEnum.OrderApprovedByParticipant;
    case NotificationTypeEnum.OrderRejectedByParticipant:
      return ApiNotificationTypeEnum.OrderRejectedByParticipant;
    case NotificationTypeEnum.OrderCanceledByCustomer:
      return ApiNotificationTypeEnum.OrderCanceledByCustomer;
    case NotificationTypeEnum.AddingUserToOrganization:
      return ApiNotificationTypeEnum.AddingUserToOrganization;
    default:
      throw new Error(`Enum value is not defined: NotificationTypeEnum=${String(source)}`);
  }
}
