import { ProtocolTypeEnum } from '../../enums/protocol-type.enum';
import { ApiProtocolTypeEnum } from '../../../swagger/models/api-protocol-type-enum';

export const apiProtocolTypeEnumAdapter = (source?: ProtocolTypeEnum | null): ApiProtocolTypeEnum => {
  switch (source) {
    case ProtocolTypeEnum.Auction2FirstPartsConsiderationProtocol:
      return ApiProtocolTypeEnum.Auction2FirstPartsConsiderationProtocol;
    case ProtocolTypeEnum.Auction2TradingProtocol:
      return ApiProtocolTypeEnum.Auction2TradingProtocol;
    case ProtocolTypeEnum.Auction2SecondPartsConsiderationProtocol:
      return ApiProtocolTypeEnum.Auction2SecondPartsConsiderationProtocol;
    case ProtocolTypeEnum.Auction2SingleApplicationConsiderationProtocol:
      return ApiProtocolTypeEnum.Auction2SingleApplicationConsiderationProtocol;
    case ProtocolTypeEnum.TenderResultProtocol:
      return ApiProtocolTypeEnum.TenderResultProtocol;
    case ProtocolTypeEnum.ReductionConsiderationProtocol:
      return ApiProtocolTypeEnum.ReductionConsiderationProtocol;
    case ProtocolTypeEnum.ReductionTradingProtocol:
      return ApiProtocolTypeEnum.ReductionTradingProtocol;
    case ProtocolTypeEnum.AuctionConsiderationProtocol:
      return ApiProtocolTypeEnum.AuctionConsiderationProtocol;
    case ProtocolTypeEnum.AuctionTradingProtocol:
      return ApiProtocolTypeEnum.AuctionTradingProtocol;
    case ProtocolTypeEnum.TenderOpeningProtocol:
      return ApiProtocolTypeEnum.TenderOpeningProtocol;
    case ProtocolTypeEnum.TenderConsiderationProtocol:
      return ApiProtocolTypeEnum.TenderConsiderationProtocol;
    case ProtocolTypeEnum.TenderEvaluationProtocol:
      return ApiProtocolTypeEnum.TenderEvaluationProtocol;
    case ProtocolTypeEnum.TenderConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.TenderConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.TenderRetradingProtocol:
      return ApiProtocolTypeEnum.TenderRetradingProtocol;
    case ProtocolTypeEnum.QuotationsRequestMosConsiderationProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestMosConsiderationProtocol;
    case ProtocolTypeEnum.QuotationsRequestMosTradingProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestMosTradingProtocol;
    case ProtocolTypeEnum.SingleSupplierProtocol:
      return ApiProtocolTypeEnum.SingleSupplierProtocol;
    case ProtocolTypeEnum.ApplicationRequestResultProtocol:
      return ApiProtocolTypeEnum.ApplicationRequestResultProtocol;
    case ProtocolTypeEnum.DealRejectProtocol:
      return ApiProtocolTypeEnum.DealRejectProtocol;
    case ProtocolTypeEnum.ApplicationRequestOpeningProtocol:
      return ApiProtocolTypeEnum.ApplicationRequestOpeningProtocol;
    case ProtocolTypeEnum.ApplicationRequestConsiderationProtocol:
      return ApiProtocolTypeEnum.ApplicationRequestConsiderationProtocol;
    case ProtocolTypeEnum.ApplicationRequestEvaluationProtocol:
      return ApiProtocolTypeEnum.ApplicationRequestEvaluationProtocol;
    case ProtocolTypeEnum.ApplicationRequestConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.ApplicationRequestConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.ApplicationRequestRetradingProtocol:
      return ApiProtocolTypeEnum.ApplicationRequestRetradingProtocol;
    case ProtocolTypeEnum.Reduction2FirstPartsConsiderationProtocol:
      return ApiProtocolTypeEnum.Reduction2FirstPartsConsiderationProtocol;
    case ProtocolTypeEnum.Reduction2TradingProtocol:
      return ApiProtocolTypeEnum.Reduction2TradingProtocol;
    case ProtocolTypeEnum.Reduction2SecondPartsConsiderationProtocol:
      return ApiProtocolTypeEnum.Reduction2SecondPartsConsiderationProtocol;
    case ProtocolTypeEnum.Reduction2SingleApplicationConsiderationProtocol:
      return ApiProtocolTypeEnum.Reduction2SingleApplicationConsiderationProtocol;
    case ProtocolTypeEnum.PriceRequestOpeningProtocol:
      return ApiProtocolTypeEnum.PriceRequestOpeningProtocol;
    case ProtocolTypeEnum.PriceRequestConsiderationProtocol:
      return ApiProtocolTypeEnum.PriceRequestConsiderationProtocol;
    case ProtocolTypeEnum.PriceRequestRetradingProtocol:
      return ApiProtocolTypeEnum.PriceRequestRetradingProtocol;
    case ProtocolTypeEnum.PriceRequestResultProtocol:
      return ApiProtocolTypeEnum.PriceRequestResultProtocol;
    case ProtocolTypeEnum.CommercialPriceRequestOpeningProtocol:
      return ApiProtocolTypeEnum.CommercialPriceRequestOpeningProtocol;
    case ProtocolTypeEnum.CommercialPriceRequestConsiderationProtocol:
      return ApiProtocolTypeEnum.CommercialPriceRequestConsiderationProtocol;
    case ProtocolTypeEnum.CommercialPriceRequestRetradingProtocol:
      return ApiProtocolTypeEnum.CommercialPriceRequestRetradingProtocol;
    case ProtocolTypeEnum.CommercialPriceRequestResultProtocol:
      return ApiProtocolTypeEnum.CommercialPriceRequestResultProtocol;
    case ProtocolTypeEnum.QuotationsRequestOpeningProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestOpeningProtocol;
    case ProtocolTypeEnum.QuotationsRequestConsiderationProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestConsiderationProtocol;
    case ProtocolTypeEnum.QuotationsRequestRetradingProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestRetradingProtocol;
    case ProtocolTypeEnum.QuotationsRequestResultProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestResultProtocol;
    case ProtocolTypeEnum.PrequalificationConsiderationProtocol:
      return ApiProtocolTypeEnum.PrequalificationConsiderationProtocol;
    case ProtocolTypeEnum.CompetitiveNegotiationsResultProtocol:
      return ApiProtocolTypeEnum.CompetitiveNegotiationsResultProtocol;
    case ProtocolTypeEnum.CompetitiveNegotiationsOpeningProtocol:
      return ApiProtocolTypeEnum.CompetitiveNegotiationsOpeningProtocol;
    case ProtocolTypeEnum.CompetitiveNegotiationsConsiderationProtocol:
      return ApiProtocolTypeEnum.CompetitiveNegotiationsConsiderationProtocol;
    case ProtocolTypeEnum.CompetitiveNegotiationsEvaluationProtocol:
      return ApiProtocolTypeEnum.CompetitiveNegotiationsEvaluationProtocol;
    case ProtocolTypeEnum.CompetitiveNegotiationsConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.CompetitiveNegotiationsConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.CompetitiveNegotiationsRetradingProtocol:
      return ApiProtocolTypeEnum.CompetitiveNegotiationsRetradingProtocol;
    case ProtocolTypeEnum.PreliminaryStageProtocol:
      return ApiProtocolTypeEnum.PreliminaryStageProtocol;
    case ProtocolTypeEnum.SimpleCommercialPriceRequestConsiderationProtocol:
      return ApiProtocolTypeEnum.SimpleCommercialPriceRequestConsiderationProtocol;
    case ProtocolTypeEnum.PriceRequestTumenProtocol:
      return ApiProtocolTypeEnum.PriceRequestTumenProtocol;
    case ProtocolTypeEnum.ShiftTimePeriodProtocol:
      return ApiProtocolTypeEnum.ShiftTimePeriodProtocol;
    case ProtocolTypeEnum.CheckOwnersChainProtocol:
      return ApiProtocolTypeEnum.CheckOwnersChainProtocol;
    case ProtocolTypeEnum.InterRaoResultProtocol:
      return ApiProtocolTypeEnum.InterRaoResultProtocol;
    case ProtocolTypeEnum.PrequalificationOpeningProtocol:
      return ApiProtocolTypeEnum.PrequalificationOpeningProtocol;
    case ProtocolTypeEnum.PrequalificationEvaluationProtocol:
      return ApiProtocolTypeEnum.PrequalificationEvaluationProtocol;
    case ProtocolTypeEnum.PrequalificationConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.PrequalificationConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.CompetitiveSelectionTradingProtocol:
      return ApiProtocolTypeEnum.CompetitiveSelectionTradingProtocol;
    case ProtocolTypeEnum.AuctionOpeningProtocol:
      return ApiProtocolTypeEnum.AuctionOpeningProtocol;
    case ProtocolTypeEnum.ReductionOpeningProtocol:
      return ApiProtocolTypeEnum.ReductionOpeningProtocol;
    case ProtocolTypeEnum.AuctionResultProtocol:
      return ApiProtocolTypeEnum.AuctionResultProtocol;
    case ProtocolTypeEnum.ReductionResultProtocol:
      return ApiProtocolTypeEnum.ReductionResultProtocol;
    case ProtocolTypeEnum.QuotationsRequestRtcEvaluationProtocol:
      return ApiProtocolTypeEnum.QuotationsRequestRtcEvaluationProtocol;
    case ProtocolTypeEnum.CreateRetradingProtocol:
      return ApiProtocolTypeEnum.CreateRetradingProtocol;
    case ProtocolTypeEnum.FskAboutResultProtocol:
      return ApiProtocolTypeEnum.FskAboutResultProtocol;
    case ProtocolTypeEnum.SpecificationsDiscussionProtocol:
      return ApiProtocolTypeEnum.SpecificationsDiscussionProtocol;
    case ProtocolTypeEnum.SpecificationProposalsDiscussionProtocol:
      return ApiProtocolTypeEnum.SpecificationProposalsDiscussionProtocol;
    case ProtocolTypeEnum.FirstPartsConsiderationProtocol:
      return ApiProtocolTypeEnum.FirstPartsConsiderationProtocol;
    case ProtocolTypeEnum.FirstPartsConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.FirstPartsConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.ResultProtocol:
      return ApiProtocolTypeEnum.ResultProtocol;
    case ProtocolTypeEnum.QualificationProtocol:
      return ApiProtocolTypeEnum.QualificationProtocol;
    case ProtocolTypeEnum.TradingProtocol:
      return ApiProtocolTypeEnum.TradingProtocol;
    case ProtocolTypeEnum.SecondPartsConsiderationProtocol:
      return ApiProtocolTypeEnum.SecondPartsConsiderationProtocol;
    case ProtocolTypeEnum.ChangeDealTermsProtocol:
      return ApiProtocolTypeEnum.ChangeDealTermsProtocol;
    case ProtocolTypeEnum.SecondPartsConsiderationProtocolEvaluation:
      return ApiProtocolTypeEnum.SecondPartsConsiderationProtocolEvaluation;
    case ProtocolTypeEnum.OpeningProtocol:
      return ApiProtocolTypeEnum.OpeningProtocol;
    case ProtocolTypeEnum.ConsiderationProtocol:
      return ApiProtocolTypeEnum.ConsiderationProtocol;
    case ProtocolTypeEnum.EvaluationProtocol:
      return ApiProtocolTypeEnum.EvaluationProtocol;
    case ProtocolTypeEnum.ConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.ConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.RetradingProtocol:
      return ApiProtocolTypeEnum.RetradingProtocol;
    case ProtocolTypeEnum.AdditionalOffersComparisonProtocol:
      return ApiProtocolTypeEnum.AdditionalOffersComparisonProtocol;
    case ProtocolTypeEnum.Tender2SingleApplicationConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.Tender2SingleApplicationConsiderationEvaluationProtocol;
    case ProtocolTypeEnum.ApplicationRequest2SingleApplicationConsiderationEvaluationProtocol:
      return ApiProtocolTypeEnum.ApplicationRequest2SingleApplicationConsiderationEvaluationProtocol;
    default:
      throw new Error(`Enum value is not defined: ProtocolTypeEnum=${String(source)}`);
  }
}
