import { ApiDocumentTypesAltEnum } from '../../../swagger/models/api-document-types';
import { DocumentTypesAltEnum } from '../../enums/document-types-alt.enum';

export const documentTypesAltEnumAdapter = (source?: ApiDocumentTypesAltEnum | null): DocumentTypesAltEnum => {
  switch (source) {
    case ApiDocumentTypesAltEnum.Unknown:
      return DocumentTypesAltEnum.Unknown;
    case ApiDocumentTypesAltEnum.EGRIP:
      return DocumentTypesAltEnum.EGRIP;
    case ApiDocumentTypesAltEnum.EGRYL:
      return DocumentTypesAltEnum.EGRYL;
    case ApiDocumentTypesAltEnum.FoundingDocument:
      return DocumentTypesAltEnum.FoundingDocument;
    case ApiDocumentTypesAltEnum.ConfirmationOfTheHeadOffice:
      return DocumentTypesAltEnum.ConfirmationOfTheHeadOffice;
    case ApiDocumentTypesAltEnum.ApprovalOfMajorTransactions:
      return DocumentTypesAltEnum.ApprovalOfMajorTransactions;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyForAccreditation:
      return DocumentTypesAltEnum.PowerOfAttorneyForAccreditation;
    case ApiDocumentTypesAltEnum.ConfirmationOfPowers:
      return DocumentTypesAltEnum.ConfirmationOfPowers;
    case ApiDocumentTypesAltEnum.DocumentPersonalIdentification:
      return DocumentTypesAltEnum.DocumentPersonalIdentification;
    case ApiDocumentTypesAltEnum.Custom:
      return DocumentTypesAltEnum.Custom;
    case ApiDocumentTypesAltEnum.RussianPassport:
      return DocumentTypesAltEnum.RussianPassport;
    case ApiDocumentTypesAltEnum.IndividualEntrepreneurCertificate:
      return DocumentTypesAltEnum.IndividualEntrepreneurCertificate;
    case ApiDocumentTypesAltEnum.ClientAgreement:
      return DocumentTypesAltEnum.ClientAgreement;
    case ApiDocumentTypesAltEnum.PartnershipAgreement:
      return DocumentTypesAltEnum.PartnershipAgreement;
    case ApiDocumentTypesAltEnum.ActReportOfAcceptanceOfService:
      return DocumentTypesAltEnum.ActReportOfAcceptanceOfService;
    case ApiDocumentTypesAltEnum.CertificateEntityOfTaxRegistration:
      return DocumentTypesAltEnum.CertificateEntityOfTaxRegistration;
    case ApiDocumentTypesAltEnum.LastYearTaxDeclaration:
      return DocumentTypesAltEnum.LastYearTaxDeclaration;
    case ApiDocumentTypesAltEnum.SimplifiedTaxNotification:
      return DocumentTypesAltEnum.SimplifiedTaxNotification;
    case ApiDocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportAGRO:
      return DocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportAGRO;
    case ApiDocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeAGRO:
      return DocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeAGRO;
    case ApiDocumentTypesAltEnum.OGRNIP:
      return DocumentTypesAltEnum.OGRNIP;
    case ApiDocumentTypesAltEnum.CertificateOfTaxRegistration:
      return DocumentTypesAltEnum.CertificateOfTaxRegistration;
    case ApiDocumentTypesAltEnum.OGRN:
      return DocumentTypesAltEnum.OGRN;
    case ApiDocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportCOMP:
      return DocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportCOMP;
    case ApiDocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeCOMP:
      return DocumentTypesAltEnum.SignatureListToTheAgreementOnProvisionOfTheGuaranteeCOMP;
    case ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementAGRO:
      return DocumentTypesAltEnum.PersonalDataProcessingAgreementAGRO;
    case ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementCOMP:
      return DocumentTypesAltEnum.PersonalDataProcessingAgreementCOMP;
    case ApiDocumentTypesAltEnum.Other:
      return DocumentTypesAltEnum.Other;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyJPOnOTCAGRO:
      return DocumentTypesAltEnum.PowerOfAttorneyJPOnOTCAGRO;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyJPOnOTCTENDER:
      return DocumentTypesAltEnum.PowerOfAttorneyJPOnOTCTENDER;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyForWorkOnRTSTENDER:
      return DocumentTypesAltEnum.PowerOfAttorneyForWorkOnRTSTENDER;
    case ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementRTSTENDER:
      return DocumentTypesAltEnum.PersonalDataProcessingAgreementRTSTENDER;
    case ApiDocumentTypesAltEnum.UserSignedData:
      return DocumentTypesAltEnum.UserSignedData;
    case ApiDocumentTypesAltEnum.ProcurementRegulations:
      return DocumentTypesAltEnum.ProcurementRegulations;
    case ApiDocumentTypesAltEnum.ProcurementPlan:
      return DocumentTypesAltEnum.ProcurementPlan;
    case ApiDocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForIndividualEntrepreneur:
      return DocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForIndividualEntrepreneur;
    case ApiDocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForPhysicalPerson:
      return DocumentTypesAltEnum.CopiesOfDocumentPersonalIdentificationForPhysicalPerson;
    case ApiDocumentTypesAltEnum.ApplicationForAccreditationRtsTender:
      return DocumentTypesAltEnum.ApplicationForAccreditationRtsTender;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyJPOnRTSTENDER:
      return DocumentTypesAltEnum.PowerOfAttorneyJPOnRTSTENDER;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyIEOnRTSTENDER:
      return DocumentTypesAltEnum.PowerOfAttorneyIEOnRTSTENDER;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyIEOnOTCTENDER:
      return DocumentTypesAltEnum.PowerOfAttorneyIEOnOTCTENDER;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyPPOnOTCTENDER:
      return DocumentTypesAltEnum.PowerOfAttorneyPPOnOTCTENDER;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyIEOnOTCAGRO:
      return DocumentTypesAltEnum.PowerOfAttorneyIEOnOTCAGRO;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyPPOnOTCAGRO:
      return DocumentTypesAltEnum.PowerOfAttorneyPPOnOTCAGRO;
    case ApiDocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportOTCMarket:
      return DocumentTypesAltEnum.AgreementOnInformationAndTechnicalSupportOTCMarket;
    case ApiDocumentTypesAltEnum.ChangeOrganizationFullNameContract:
      return DocumentTypesAltEnum.ChangeOrganizationFullNameContract;
    case ApiDocumentTypesAltEnum.ApplicationToJoinTheCryptoSiteRules:
      return DocumentTypesAltEnum.ApplicationToJoinTheCryptoSiteRules;
    case ApiDocumentTypesAltEnum.ApplicationForCertificateOfManufacture:
      return DocumentTypesAltEnum.ApplicationForCertificateOfManufacture;
    case ApiDocumentTypesAltEnum.ThePowerOfAttorneyForACertificate:
      return DocumentTypesAltEnum.ThePowerOfAttorneyForACertificate;
    case ApiDocumentTypesAltEnum.ApplicationForCertificateRestore:
      return DocumentTypesAltEnum.ApplicationForCertificateRestore;
    case ApiDocumentTypesAltEnum.ApplicationForJoinSublicenseContract:
      return DocumentTypesAltEnum.ApplicationForJoinSublicenseContract;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyForToken:
      return DocumentTypesAltEnum.PowerOfAttorneyForToken;
    case ApiDocumentTypesAltEnum.Snils:
      return DocumentTypesAltEnum.Snils;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyForCertificateOwner:
      return DocumentTypesAltEnum.PowerOfAttorneyForCertificateOwner;
    case ApiDocumentTypesAltEnum.AgreementOfAutomaticImportFromExternalSourcesOTCMarket:
      return DocumentTypesAltEnum.AgreementOfAutomaticImportFromExternalSourcesOTCMarket;
    case ApiDocumentTypesAltEnum.AccountingDocument:
      return DocumentTypesAltEnum.AccountingDocument;
    case ApiDocumentTypesAltEnum.PowerOfAccreditationWithoutAdmin:
      return DocumentTypesAltEnum.PowerOfAccreditationWithoutAdmin;
    case ApiDocumentTypesAltEnum.AgreementForGo:
      return DocumentTypesAltEnum.AgreementForGo;
    case ApiDocumentTypesAltEnum.LicenseContractForSupplier:
      return DocumentTypesAltEnum.LicenseContractForSupplier;
    case ApiDocumentTypesAltEnum.LicenseContractForCustomer:
      return DocumentTypesAltEnum.LicenseContractForCustomer;
    case ApiDocumentTypesAltEnum.SignListForSupplier:
      return DocumentTypesAltEnum.SignListForSupplier;
    case ApiDocumentTypesAltEnum.SignListForCustomer:
      return DocumentTypesAltEnum.SignListForCustomer;
    case ApiDocumentTypesAltEnum.SmpContract:
      return DocumentTypesAltEnum.SmpContract;
    case ApiDocumentTypesAltEnum.ForeignCountryRegistrationDocument:
      return DocumentTypesAltEnum.ForeignCountryRegistrationDocument;
    case ApiDocumentTypesAltEnum.SelfRegulationOrganizationCertificate:
      return DocumentTypesAltEnum.SelfRegulationOrganizationCertificate;
    case ApiDocumentTypesAltEnum.LicenseForCulturalObjectsRepair:
      return DocumentTypesAltEnum.LicenseForCulturalObjectsRepair;
    case ApiDocumentTypesAltEnum.LicenseForCulturalObjectsProjectDocumentationDesign:
      return DocumentTypesAltEnum.LicenseForCulturalObjectsProjectDocumentationDesign;
    case ApiDocumentTypesAltEnum.AtestatForElevatorsInspection:
      return DocumentTypesAltEnum.AtestatForElevatorsInspection;
    case ApiDocumentTypesAltEnum.CertificateForLackOfTaxDebt:
      return DocumentTypesAltEnum.CertificateForLackOfTaxDebt;
    case ApiDocumentTypesAltEnum.CalculationForInsurance:
      return DocumentTypesAltEnum.CalculationForInsurance;
    case ApiDocumentTypesAltEnum.ContractForSimilarWork:
      return DocumentTypesAltEnum.ContractForSimilarWork;
    case ApiDocumentTypesAltEnum.PowerOfPrequalificationParticipant:
      return DocumentTypesAltEnum.PowerOfPrequalificationParticipant;
    case ApiDocumentTypesAltEnum.StaffList:
      return DocumentTypesAltEnum.StaffList;
    case ApiDocumentTypesAltEnum.EmployeesList:
      return DocumentTypesAltEnum.EmployeesList;
    case ApiDocumentTypesAltEnum.EmploymentHistory:
      return DocumentTypesAltEnum.EmploymentHistory;
    case ApiDocumentTypesAltEnum.Diploma:
      return DocumentTypesAltEnum.Diploma;
    case ApiDocumentTypesAltEnum.Certificate:
      return DocumentTypesAltEnum.Certificate;
    case ApiDocumentTypesAltEnum.Atestate:
      return DocumentTypesAltEnum.Atestate;
    case ApiDocumentTypesAltEnum.ActOfAcceptanceOfTheExecutedWorks:
      return DocumentTypesAltEnum.ActOfAcceptanceOfTheExecutedWorks;
    case ApiDocumentTypesAltEnum.DeclarationOfAccessionForSupplier:
      return DocumentTypesAltEnum.DeclarationOfAccessionForSupplier;
    case ApiDocumentTypesAltEnum.DeclarationOfAccessionForCustomer:
      return DocumentTypesAltEnum.DeclarationOfAccessionForCustomer;
    case ApiDocumentTypesAltEnum.AuthorizationPaymentPrintForm:
      return DocumentTypesAltEnum.AuthorizationPaymentPrintForm;
    case ApiDocumentTypesAltEnum.BoostedAccreditationAgreementPrintForm:
      return DocumentTypesAltEnum.BoostedAccreditationAgreementPrintForm;
    case ApiDocumentTypesAltEnum.EruzOriginalEgrip:
      return DocumentTypesAltEnum.EruzOriginalEgrip;
    case ApiDocumentTypesAltEnum.EruzOriginalEgryl:
      return DocumentTypesAltEnum.EruzOriginalEgryl;
    case ApiDocumentTypesAltEnum.PersonalDataDisseminationAgreementRTSTENDER:
      return DocumentTypesAltEnum.PersonalDataDisseminationAgreementRTSTENDER;
    case ApiDocumentTypesAltEnum.Agreement2323:
      return DocumentTypesAltEnum.Agreement2323;
    case ApiDocumentTypesAltEnum.DeclarationOfAccession:
      return DocumentTypesAltEnum.DeclarationOfAccession;
    case ApiDocumentTypesAltEnum.PowerOfAttorneyForAccreditationBelarus:
      return DocumentTypesAltEnum.PowerOfAttorneyForAccreditationBelarus;
    case ApiDocumentTypesAltEnum.PersonalDataProcessingAgreementEAT:
      return DocumentTypesAltEnum.PersonalDataProcessingAgreementEAT;
    case ApiDocumentTypesAltEnum.PersonalDataDisseminationAgreementEAT:
      return DocumentTypesAltEnum.PersonalDataDisseminationAgreementEAT;
    default:
      throw new Error(`Enum value is not defined: ApiDocumentTypesAltEnum=${String(source)}`);
  }
}
