import { ApiNotificationTypeEnum } from '../../../swagger/models/api-notification-type-enum';
import { NotificationTypeEnum } from '../../enums/notification-type.enum';

export const notificationTypeEnumAdapter = (source?: ApiNotificationTypeEnum | null): NotificationTypeEnum => {
  switch (source) {
    case ApiNotificationTypeEnum.ParticipantRegistrationPassedInSystem:
      return NotificationTypeEnum.ParticipantRegistrationPassedInSystem;
    case ApiNotificationTypeEnum.ImmediateTradeOfInterestOfParticipantPublished:
      return NotificationTypeEnum.ImmediateTradeOfInterestOfParticipantPublished;
    case ApiNotificationTypeEnum.TradeOfInterestOfParticipantPublished:
      return NotificationTypeEnum.TradeOfInterestOfParticipantPublished;
    case ApiNotificationTypeEnum.TradeWithParticipantsApplicationWasEdited:
      return NotificationTypeEnum.TradeWithParticipantsApplicationWasEdited;
    case ApiNotificationTypeEnum.TradeWithParticipantsApplicationWasRevoked:
      return NotificationTypeEnum.TradeWithParticipantsApplicationWasRevoked;
    case ApiNotificationTypeEnum.ParticipantPublishApplicationForTrade:
      return NotificationTypeEnum.ParticipantPublishApplicationForTrade;
    case ApiNotificationTypeEnum.ParticipantEditedApplication:
      return NotificationTypeEnum.ParticipantEditedApplication;
    case ApiNotificationTypeEnum.ApplicationWasRevokedFromTrade:
      return NotificationTypeEnum.ApplicationWasRevokedFromTrade;
    case ApiNotificationTypeEnum.CustomerConcludeDealOutsideEShop:
      return NotificationTypeEnum.CustomerConcludeDealOutsideEShop;
    case ApiNotificationTypeEnum.CustomerConcludeOrderDealOutsideEShop:
      return NotificationTypeEnum.CustomerConcludeOrderDealOutsideEShop;
    case ApiNotificationTypeEnum.CustomerSendDealForSign:
      return NotificationTypeEnum.CustomerSendDealForSign;
    case ApiNotificationTypeEnum.CustomerSendOrderDealForSign:
      return NotificationTypeEnum.CustomerSendOrderDealForSign;
    case ApiNotificationTypeEnum.ApplicationNotMeetRequierments:
      return NotificationTypeEnum.ApplicationNotMeetRequierments;
    case ApiNotificationTypeEnum.CustomerRejectDealAfterParticipantSign:
      return NotificationTypeEnum.CustomerRejectDealAfterParticipantSign;
    case ApiNotificationTypeEnum.CustomerRejectOrderDealAfterParticipantSign:
      return NotificationTypeEnum.CustomerRejectOrderDealAfterParticipantSign;
    case ApiNotificationTypeEnum.ApplicationWasCreatedByCustomerForParticipant:
      return NotificationTypeEnum.ApplicationWasCreatedByCustomerForParticipant;
    case ApiNotificationTypeEnum.CustomerClosedTradeWithoutSigningDeal:
      return NotificationTypeEnum.CustomerClosedTradeWithoutSigningDeal;
    case ApiNotificationTypeEnum.NewTradePublished:
      return NotificationTypeEnum.NewTradePublished;
    case ApiNotificationTypeEnum.TradeWasEdited:
      return NotificationTypeEnum.TradeWasEdited;
    case ApiNotificationTypeEnum.TradeWasRevoked:
      return NotificationTypeEnum.TradeWasRevoked;
    case ApiNotificationTypeEnum.NewApplicationForTradePublished:
      return NotificationTypeEnum.NewApplicationForTradePublished;
    case ApiNotificationTypeEnum.NewApplicationForTradeEdited:
      return NotificationTypeEnum.NewApplicationForTradeEdited;
    case ApiNotificationTypeEnum.ParticipantRevokeApplicationFromTrade:
      return NotificationTypeEnum.ParticipantRevokeApplicationFromTrade;
    case ApiNotificationTypeEnum.FillingApplicationTimeFinishedWithMoreThenOneApplication:
      return NotificationTypeEnum.FillingApplicationTimeFinishedWithMoreThenOneApplication;
    case ApiNotificationTypeEnum.TradeNotNookPlace:
      return NotificationTypeEnum.TradeNotNookPlace;
    case ApiNotificationTypeEnum.TradeIncreasedWhenNotTookPlace:
      return NotificationTypeEnum.TradeIncreasedWhenNotTookPlace;
    case ApiNotificationTypeEnum.CustomerAddDealInformationToSystem:
      return NotificationTypeEnum.CustomerAddDealInformationToSystem;
    case ApiNotificationTypeEnum.CustomerAddOrderDealInformationToSystem:
      return NotificationTypeEnum.CustomerAddOrderDealInformationToSystem;
    case ApiNotificationTypeEnum.DealSendToParticipant:
      return NotificationTypeEnum.DealSendToParticipant;
    case ApiNotificationTypeEnum.OrderDealSendToParticipant:
      return NotificationTypeEnum.OrderDealSendToParticipant;
    case ApiNotificationTypeEnum.DealSignedByParticipant:
      return NotificationTypeEnum.DealSignedByParticipant;
    case ApiNotificationTypeEnum.OrderDealSignedByParticipant:
      return NotificationTypeEnum.OrderDealSignedByParticipant;
    case ApiNotificationTypeEnum.DealConcludedAfterCustomerSign:
      return NotificationTypeEnum.DealConcludedAfterCustomerSign;
    case ApiNotificationTypeEnum.OrderDealConcludedAfterCustomerSign:
      return NotificationTypeEnum.OrderDealConcludedAfterCustomerSign;
    case ApiNotificationTypeEnum.CustomerRejectDeal:
      return NotificationTypeEnum.CustomerRejectDeal;
    case ApiNotificationTypeEnum.CustomerRejectOrderDeal:
      return NotificationTypeEnum.CustomerRejectOrderDeal;
    case ApiNotificationTypeEnum.ParticipantRejectDealForParticipant:
      return NotificationTypeEnum.ParticipantRejectDealForParticipant;
    case ApiNotificationTypeEnum.ParticipantRejectOrderDealForParticipant:
      return NotificationTypeEnum.ParticipantRejectOrderDealForParticipant;
    case ApiNotificationTypeEnum.ParticipantRejectDealForCustomer:
      return NotificationTypeEnum.ParticipantRejectDealForCustomer;
    case ApiNotificationTypeEnum.ParticipantRejectOrderDealForCustomer:
      return NotificationTypeEnum.ParticipantRejectOrderDealForCustomer;
    case ApiNotificationTypeEnum.TradeFillingApplicationEndDateWasIncreasedBecauseAllApplicationsDoNotMeetRequirementsForParticipant:
      return NotificationTypeEnum.TradeFillingApplicationEndDateWasIncreasedBecauseAllApplicationsDoNotMeetRequirementsForParticipant;
    case ApiNotificationTypeEnum.TradeWasClosedWithoutSigningDeal:
      return NotificationTypeEnum.TradeWasClosedWithoutSigningDeal;
    case ApiNotificationTypeEnum.ApplicationWasCreatedForParticipant:
      return NotificationTypeEnum.ApplicationWasCreatedForParticipant;
    case ApiNotificationTypeEnum.ParticipantSuggestedToSignPaperDealForCustomer:
      return NotificationTypeEnum.ParticipantSuggestedToSignPaperDealForCustomer;
    case ApiNotificationTypeEnum.ParticipantSuggestedToSignPaperOrderDealForCustomer:
      return NotificationTypeEnum.ParticipantSuggestedToSignPaperOrderDealForCustomer;
    case ApiNotificationTypeEnum.OrgAdminRightsAssignedToUserAfterRegistration:
      return NotificationTypeEnum.OrgAdminRightsAssignedToUserAfterRegistration;
    case ApiNotificationTypeEnum.OrderSentToParticipant:
      return NotificationTypeEnum.OrderSentToParticipant;
    case ApiNotificationTypeEnum.OrderApprovedByParticipant:
      return NotificationTypeEnum.OrderApprovedByParticipant;
    case ApiNotificationTypeEnum.OrderRejectedByParticipant:
      return NotificationTypeEnum.OrderRejectedByParticipant;
    case ApiNotificationTypeEnum.OrderCanceledByCustomer:
      return NotificationTypeEnum.OrderCanceledByCustomer;
    case ApiNotificationTypeEnum.AddingUserToOrganization:
      return NotificationTypeEnum.AddingUserToOrganization;
    default:
      throw new Error(`Enum value is not defined: ApiNotificationTypeEnum=${String(source)}`);
  }
}
