import { ApiProtocolTypeEnum } from '../../../swagger/models/api-protocol-type-enum';
import { ProtocolTypeEnum } from '../../enums/protocol-type.enum';

export const protocolTypeEnumAdapter = (source?: ApiProtocolTypeEnum | null): ProtocolTypeEnum => {
  switch (source) {
    case ApiProtocolTypeEnum.Auction2FirstPartsConsiderationProtocol:
      return ProtocolTypeEnum.Auction2FirstPartsConsiderationProtocol;
    case ApiProtocolTypeEnum.Auction2TradingProtocol:
      return ProtocolTypeEnum.Auction2TradingProtocol;
    case ApiProtocolTypeEnum.Auction2SecondPartsConsiderationProtocol:
      return ProtocolTypeEnum.Auction2SecondPartsConsiderationProtocol;
    case ApiProtocolTypeEnum.Auction2SingleApplicationConsiderationProtocol:
      return ProtocolTypeEnum.Auction2SingleApplicationConsiderationProtocol;
    case ApiProtocolTypeEnum.TenderResultProtocol:
      return ProtocolTypeEnum.TenderResultProtocol;
    case ApiProtocolTypeEnum.ReductionConsiderationProtocol:
      return ProtocolTypeEnum.ReductionConsiderationProtocol;
    case ApiProtocolTypeEnum.ReductionTradingProtocol:
      return ProtocolTypeEnum.ReductionTradingProtocol;
    case ApiProtocolTypeEnum.AuctionConsiderationProtocol:
      return ProtocolTypeEnum.AuctionConsiderationProtocol;
    case ApiProtocolTypeEnum.AuctionTradingProtocol:
      return ProtocolTypeEnum.AuctionTradingProtocol;
    case ApiProtocolTypeEnum.TenderOpeningProtocol:
      return ProtocolTypeEnum.TenderOpeningProtocol;
    case ApiProtocolTypeEnum.TenderConsiderationProtocol:
      return ProtocolTypeEnum.TenderConsiderationProtocol;
    case ApiProtocolTypeEnum.TenderEvaluationProtocol:
      return ProtocolTypeEnum.TenderEvaluationProtocol;
    case ApiProtocolTypeEnum.TenderConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.TenderConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.TenderRetradingProtocol:
      return ProtocolTypeEnum.TenderRetradingProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestMosConsiderationProtocol:
      return ProtocolTypeEnum.QuotationsRequestMosConsiderationProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestMosTradingProtocol:
      return ProtocolTypeEnum.QuotationsRequestMosTradingProtocol;
    case ApiProtocolTypeEnum.SingleSupplierProtocol:
      return ProtocolTypeEnum.SingleSupplierProtocol;
    case ApiProtocolTypeEnum.ApplicationRequestResultProtocol:
      return ProtocolTypeEnum.ApplicationRequestResultProtocol;
    case ApiProtocolTypeEnum.DealRejectProtocol:
      return ProtocolTypeEnum.DealRejectProtocol;
    case ApiProtocolTypeEnum.ApplicationRequestOpeningProtocol:
      return ProtocolTypeEnum.ApplicationRequestOpeningProtocol;
    case ApiProtocolTypeEnum.ApplicationRequestConsiderationProtocol:
      return ProtocolTypeEnum.ApplicationRequestConsiderationProtocol;
    case ApiProtocolTypeEnum.ApplicationRequestEvaluationProtocol:
      return ProtocolTypeEnum.ApplicationRequestEvaluationProtocol;
    case ApiProtocolTypeEnum.ApplicationRequestConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.ApplicationRequestConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.ApplicationRequestRetradingProtocol:
      return ProtocolTypeEnum.ApplicationRequestRetradingProtocol;
    case ApiProtocolTypeEnum.Reduction2FirstPartsConsiderationProtocol:
      return ProtocolTypeEnum.Reduction2FirstPartsConsiderationProtocol;
    case ApiProtocolTypeEnum.Reduction2TradingProtocol:
      return ProtocolTypeEnum.Reduction2TradingProtocol;
    case ApiProtocolTypeEnum.Reduction2SecondPartsConsiderationProtocol:
      return ProtocolTypeEnum.Reduction2SecondPartsConsiderationProtocol;
    case ApiProtocolTypeEnum.Reduction2SingleApplicationConsiderationProtocol:
      return ProtocolTypeEnum.Reduction2SingleApplicationConsiderationProtocol;
    case ApiProtocolTypeEnum.PriceRequestOpeningProtocol:
      return ProtocolTypeEnum.PriceRequestOpeningProtocol;
    case ApiProtocolTypeEnum.PriceRequestConsiderationProtocol:
      return ProtocolTypeEnum.PriceRequestConsiderationProtocol;
    case ApiProtocolTypeEnum.PriceRequestRetradingProtocol:
      return ProtocolTypeEnum.PriceRequestRetradingProtocol;
    case ApiProtocolTypeEnum.PriceRequestResultProtocol:
      return ProtocolTypeEnum.PriceRequestResultProtocol;
    case ApiProtocolTypeEnum.CommercialPriceRequestOpeningProtocol:
      return ProtocolTypeEnum.CommercialPriceRequestOpeningProtocol;
    case ApiProtocolTypeEnum.CommercialPriceRequestConsiderationProtocol:
      return ProtocolTypeEnum.CommercialPriceRequestConsiderationProtocol;
    case ApiProtocolTypeEnum.CommercialPriceRequestRetradingProtocol:
      return ProtocolTypeEnum.CommercialPriceRequestRetradingProtocol;
    case ApiProtocolTypeEnum.CommercialPriceRequestResultProtocol:
      return ProtocolTypeEnum.CommercialPriceRequestResultProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestOpeningProtocol:
      return ProtocolTypeEnum.QuotationsRequestOpeningProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestConsiderationProtocol:
      return ProtocolTypeEnum.QuotationsRequestConsiderationProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestRetradingProtocol:
      return ProtocolTypeEnum.QuotationsRequestRetradingProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestResultProtocol:
      return ProtocolTypeEnum.QuotationsRequestResultProtocol;
    case ApiProtocolTypeEnum.PrequalificationConsiderationProtocol:
      return ProtocolTypeEnum.PrequalificationConsiderationProtocol;
    case ApiProtocolTypeEnum.CompetitiveNegotiationsResultProtocol:
      return ProtocolTypeEnum.CompetitiveNegotiationsResultProtocol;
    case ApiProtocolTypeEnum.CompetitiveNegotiationsOpeningProtocol:
      return ProtocolTypeEnum.CompetitiveNegotiationsOpeningProtocol;
    case ApiProtocolTypeEnum.CompetitiveNegotiationsConsiderationProtocol:
      return ProtocolTypeEnum.CompetitiveNegotiationsConsiderationProtocol;
    case ApiProtocolTypeEnum.CompetitiveNegotiationsEvaluationProtocol:
      return ProtocolTypeEnum.CompetitiveNegotiationsEvaluationProtocol;
    case ApiProtocolTypeEnum.CompetitiveNegotiationsConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.CompetitiveNegotiationsConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.CompetitiveNegotiationsRetradingProtocol:
      return ProtocolTypeEnum.CompetitiveNegotiationsRetradingProtocol;
    case ApiProtocolTypeEnum.PreliminaryStageProtocol:
      return ProtocolTypeEnum.PreliminaryStageProtocol;
    case ApiProtocolTypeEnum.SimpleCommercialPriceRequestConsiderationProtocol:
      return ProtocolTypeEnum.SimpleCommercialPriceRequestConsiderationProtocol;
    case ApiProtocolTypeEnum.PriceRequestTumenProtocol:
      return ProtocolTypeEnum.PriceRequestTumenProtocol;
    case ApiProtocolTypeEnum.ShiftTimePeriodProtocol:
      return ProtocolTypeEnum.ShiftTimePeriodProtocol;
    case ApiProtocolTypeEnum.CheckOwnersChainProtocol:
      return ProtocolTypeEnum.CheckOwnersChainProtocol;
    case ApiProtocolTypeEnum.InterRaoResultProtocol:
      return ProtocolTypeEnum.InterRaoResultProtocol;
    case ApiProtocolTypeEnum.PrequalificationOpeningProtocol:
      return ProtocolTypeEnum.PrequalificationOpeningProtocol;
    case ApiProtocolTypeEnum.PrequalificationEvaluationProtocol:
      return ProtocolTypeEnum.PrequalificationEvaluationProtocol;
    case ApiProtocolTypeEnum.PrequalificationConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.PrequalificationConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.CompetitiveSelectionTradingProtocol:
      return ProtocolTypeEnum.CompetitiveSelectionTradingProtocol;
    case ApiProtocolTypeEnum.AuctionOpeningProtocol:
      return ProtocolTypeEnum.AuctionOpeningProtocol;
    case ApiProtocolTypeEnum.ReductionOpeningProtocol:
      return ProtocolTypeEnum.ReductionOpeningProtocol;
    case ApiProtocolTypeEnum.AuctionResultProtocol:
      return ProtocolTypeEnum.AuctionResultProtocol;
    case ApiProtocolTypeEnum.ReductionResultProtocol:
      return ProtocolTypeEnum.ReductionResultProtocol;
    case ApiProtocolTypeEnum.QuotationsRequestRtcEvaluationProtocol:
      return ProtocolTypeEnum.QuotationsRequestRtcEvaluationProtocol;
    case ApiProtocolTypeEnum.CreateRetradingProtocol:
      return ProtocolTypeEnum.CreateRetradingProtocol;
    case ApiProtocolTypeEnum.FskAboutResultProtocol:
      return ProtocolTypeEnum.FskAboutResultProtocol;
    case ApiProtocolTypeEnum.SpecificationsDiscussionProtocol:
      return ProtocolTypeEnum.SpecificationsDiscussionProtocol;
    case ApiProtocolTypeEnum.SpecificationProposalsDiscussionProtocol:
      return ProtocolTypeEnum.SpecificationProposalsDiscussionProtocol;
    case ApiProtocolTypeEnum.FirstPartsConsiderationProtocol:
      return ProtocolTypeEnum.FirstPartsConsiderationProtocol;
    case ApiProtocolTypeEnum.FirstPartsConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.FirstPartsConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.ResultProtocol:
      return ProtocolTypeEnum.ResultProtocol;
    case ApiProtocolTypeEnum.QualificationProtocol:
      return ProtocolTypeEnum.QualificationProtocol;
    case ApiProtocolTypeEnum.TradingProtocol:
      return ProtocolTypeEnum.TradingProtocol;
    case ApiProtocolTypeEnum.SecondPartsConsiderationProtocol:
      return ProtocolTypeEnum.SecondPartsConsiderationProtocol;
    case ApiProtocolTypeEnum.ChangeDealTermsProtocol:
      return ProtocolTypeEnum.ChangeDealTermsProtocol;
    case ApiProtocolTypeEnum.SecondPartsConsiderationProtocolEvaluation:
      return ProtocolTypeEnum.SecondPartsConsiderationProtocolEvaluation;
    case ApiProtocolTypeEnum.OpeningProtocol:
      return ProtocolTypeEnum.OpeningProtocol;
    case ApiProtocolTypeEnum.ConsiderationProtocol:
      return ProtocolTypeEnum.ConsiderationProtocol;
    case ApiProtocolTypeEnum.EvaluationProtocol:
      return ProtocolTypeEnum.EvaluationProtocol;
    case ApiProtocolTypeEnum.ConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.ConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.RetradingProtocol:
      return ProtocolTypeEnum.RetradingProtocol;
    case ApiProtocolTypeEnum.AdditionalOffersComparisonProtocol:
      return ProtocolTypeEnum.AdditionalOffersComparisonProtocol;
    case ApiProtocolTypeEnum.Tender2SingleApplicationConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.Tender2SingleApplicationConsiderationEvaluationProtocol;
    case ApiProtocolTypeEnum.ApplicationRequest2SingleApplicationConsiderationEvaluationProtocol:
      return ProtocolTypeEnum.ApplicationRequest2SingleApplicationConsiderationEvaluationProtocol;
    default:
      throw new Error(`Enum value is not defined: ApiProtocolTypeEnum=${String(source)}`);
  }
}
