import { MarketTradeView } from '../../models/market-trade-view.interface';
import { ApiMarketTradeViewDto } from '../../../swagger/models/api-market-trade-view-dto';
import { apiAdditionalRequirementDto2Adapter } from './api-additional-requirement-dto-2.adapter';
import { apiApplicationParametersDtoAdapter } from './api-application-parameters-dto.adapter';
import { apiApplicationStateEnumAdapter } from '../enums/api-application-state-enum.adapter';
import { apiAvailableVatTypeEnumAdapter } from '../enums/api-available-vat-type-enum.adapter';
import { apiDealSignerAltDtoAdapter } from './api-deal-signer.adapter';
import { apiDealStateEnumAdapter } from '../enums/api-deal-state-enum.adapter';
import { apiDeliveryMethodAltEnumAdapter } from '../enums/api-delivery-method.adapter';
import { apiDictionaryItemAltDtoAdapter } from './api-dictionary-item.adapter';
import { apiEisIntegrationDataAltDtoAdapter } from './api-eis-integration-data.adapter';
import { apiEisTradeInfoAltDtoAdapter } from './api-eis-trade-info.adapter';
import { apiFederalLawLimitAltEnumAdapter } from '../enums/api-federal-law-limit.adapter';
import { apiLotStateEnumAdapter } from '../enums/api-lot-state-enum.adapter';
import { apiM4DDealSignRequiredEnumAdapter } from '../enums/api-m-4-d-deal-sign-required-enum.adapter';
import { apiMarketDealStateEnumAdapter } from '../enums/api-market-deal-state-enum.adapter';
import { apiMarketEntityTypeAltEnumAdapter } from '../enums/api-market-entity-type.adapter';
import { apiMarketTradeDealAltDtoAdapter } from './api-market-trade-deal.adapter';
import { apiMarketTradePersonAltDtoAdapter } from './api-market-trade-person.adapter';
import { apiMarketTradeProductAltDtoAdapter } from './api-market-trade-product.adapter';
import { apiMeetsRequirementsEnumAdapter } from '../enums/api-meets-requirements-enum.adapter';
import { apiMyTermsAltDtoAdapter } from './api-my-terms.adapter';
import { apiOrderStateEnumAdapter } from '../enums/api-order-state-enum.adapter';
import { apiPriceCorridorDtoAdapter } from './api-price-corridor-dto.adapter';
import { apiPurchaseMethodTypeEnumAdapter } from '../enums/api-purchase-method-type-enum.adapter';
import { apiRegulationInfoDtoAdapter } from './api-regulation-info-dto.adapter';
import { apiRetradingTypeEnumAdapter } from '../enums/api-retrading-type-enum.adapter';
import { apiShortTenantSettingAltDtoAdapter } from './api-short-tenant-setting.adapter';
import { apiTradeBusinessFlowEnumAdapter } from '../enums/api-trade-business-flow-enum.adapter';
import { apiTradeLotSpecificationDtoAdapter } from './api-trade-lot-specification-dto.adapter';
import { apiTradeStateEnumAdapter } from '../enums/api-trade-state-enum.adapter';
import { apiTradeViewFormOptionsDtoAdapter } from './api-trade-view-form-options-dto.adapter';
import { apiVatRateStateEnumAdapter } from '../enums/api-vat-rate-state-enum.adapter';
import { apiZmoFinanceSourceEnumAdapter } from '../enums/api-zmo-finance-source-enum.adapter';

export const apiMarketTradeViewDtoAdapter = (source?: MarketTradeView | null): ApiMarketTradeViewDto => {
  return {
    AdditionalRequirements: source?.additionalRequirements?.map((item) => apiAdditionalRequirementDto2Adapter(item)),
    AllowApplicationReject: source?.allowApplicationReject,
    ApplicationId: source?.applicationId,
    ApplicationParameters: source?.applicationParameters === null ? undefined : apiApplicationParametersDtoAdapter(source?.applicationParameters),
    ApplicationState: source?.applicationState === null ? undefined : apiApplicationStateEnumAdapter(source?.applicationState),
    BusinessFlowType: source?.businessFlowType === null ? undefined : apiTradeBusinessFlowEnumAdapter(source?.businessFlowType),
    CanSuggestPaperFormSigning: source?.canSuggestPaperFormSigning,
    ChildTradeBusinessFlowType: source?.childTradeBusinessFlowType === null ? undefined : apiTradeBusinessFlowEnumAdapter(source?.childTradeBusinessFlowType),
    ChildTradeHosts: source?.childTradeHosts,
    ChildTradeId: source?.childTradeId,
    ConditionsOfPayment: source?.conditionsOfPayment,
    ContactPerson: source?.contactPerson === null ? undefined : apiMarketTradePersonAltDtoAdapter(source?.contactPerson),
    ContractAmountInfo: source?.contractAmountInfo,
    CurrencyCode: source?.currencyCode,
    CurrentStageId: source?.currentStageId,
    CustomerExternalOrganizationId: source?.customerExternalOrganizationId,
    CustomerFullName: source?.customerFullName,
    CustomerGuid: source?.customerGuid,
    CustomerId: source?.customerId,
    CustomerPhysAddress: source?.customerPhysAddress,
    CustomerSource: source?.customerSource,
    DealBelongToCurrentOrg: source?.dealBelongToCurrentOrg,
    DealConclusionTermInfo: source?.dealConclusionTermInfo,
    DealDirectionFlow: source?.dealDirectionFlow,
    DealExecutionDate: source?.dealExecutionDate,
    DealId: source?.dealId,
    DealState: source?.dealState === null ? undefined : apiDealStateEnumAdapter(source?.dealState),
    Deals: source?.deals?.map((item) => apiMarketTradeDealAltDtoAdapter(item)),
    DeliveryKladrRegionCode: source?.deliveryKladrRegionCode,
    DeliveryKladrRegionCodes: source?.deliveryKladrRegionCodes?.map((item) => apiDictionaryItemAltDtoAdapter(item)),
    DeliveryKladrRegionName: source?.deliveryKladrRegionName,
    DeliveryMethod: source?.deliveryMethod === null ? undefined : apiDeliveryMethodAltEnumAdapter(source?.deliveryMethod),
    DeliveryTerms: source?.deliveryTerms,
    Description: source?.description,
    DisplayApproveBtn: source?.displayApproveBtn,
    DisplayDealDontConcludeBtn: source?.displayDealDontConcludeBtn,
    EisIntegrationData: source?.eisIntegrationData === null ? undefined : apiEisIntegrationDataAltDtoAdapter(source?.eisIntegrationData),
    EisTradeInfo: source?.eisTradeInfo === null ? undefined : apiEisTradeInfoAltDtoAdapter(source?.eisTradeInfo),
    EnableKtruSpecifications: source?.enableKtruSpecifications,
    EnableMonetizationMarket: source?.enableMonetizationMarket,
    EnablePositionCharacteristics: source?.enablePositionCharacteristics,
    EntityType: source?.entityType === null ? undefined : apiMarketEntityTypeAltEnumAdapter(source?.entityType),
    ExternalId: source?.externalId,
    ExternalSystemId: source?.externalSystemId,
    FederalLawLimit: source?.federalLawLimit === null ? undefined : apiFederalLawLimitAltEnumAdapter(source?.federalLawLimit),
    FillingApplicationEndDate: source?.fillingApplicationEndDate,
    HasDealFile: source?.hasDealFile,
    HasManualParticipantOfferToTrade: source?.hasManualParticipantOfferToTrade,
    HasUncompletedEisOutgoingSaga: source?.hasUncompletedEisOutgoingSaga,
    Hosts: source?.hosts,
    Id: source?.id,
    InitialPriceWithVat: source?.initialPriceWithVat,
    InitialPriceWithoutVat: source?.initialPriceWithoutVat,
    InitialTenantSetting: source?.initialTenantSetting === null ? undefined : apiShortTenantSettingAltDtoAdapter(source?.initialTenantSetting),
    IsApprovalRequestExists: source?.isApprovalRequestExists,
    IsAutoCreateDealAfterReviewApplications: source?.isAutoCreateDealAfterReviewApplications,
    IsAvailableSelectOnlyOneOfferForItem: source?.isAvailableSelectOnlyOneOfferForItem,
    IsBy223Fz: source?.isBy223Fz,
    IsBy44Fz: source?.isBy44Fz,
    IsContractInElectronicForm: source?.isContractInElectronicForm,
    IsCustomPrice: source?.isCustomPrice,
    IsCustomer: source?.isCustomer,
    IsCustomerAcceptByOkeiOffers: source?.isCustomerAcceptByOkeiOffers,
    IsCustomerAcceptOnlyManualOffers: source?.isCustomerAcceptOnlyManualOffers,
    IsDealSigningExpired: source?.isDealSigningExpired,
    IsEditable: source?.isEditable,
    IsEisConcludeDealRequired: source?.isEisConcludeDealRequired,
    IsEisTradeAccelerated: source?.isEisTradeAccelerated,
    IsFederalLawsEnable: source?.isFederalLawsEnable,
    IsHiddenContract: source?.isHiddenContract,
    IsImmediate: source?.isImmediate,
    IsImportPhaseout: source?.isImportPhaseout,
    IsInEisWasChanged: source?.isInEisWasChanged,
    IsInitialPriceDefined: source?.isInitialPriceDefined,
    IsInitialPriceReduction: source?.isInitialPriceReduction,
    IsLapsed: source?.isLapsed,
    IsLotPriceEnteredWithVAT: source?.isLotPriceEnteredWithVAT,
    IsLotPriceWithVat: source?.isLotPriceWithVat,
    IsModificationSentToOos: source?.isModificationSentToOos,
    IsOnlySmp: source?.isOnlySmp,
    IsOrganizer: source?.isOrganizer,
    IsParentContractNumberNotSpecified: source?.isParentContractNumberNotSpecified,
    IsPositionalVatEnable: source?.isPositionalVatEnable,
    IsPrivate: source?.isPrivate,
    IsRetradingEnabled: source?.isRetradingEnabled,
    IsRussianPurchaseObjectHasAdvantage: source?.isRussianPurchaseObjectHasAdvantage,
    IsSanctionedPurchase: source?.isSanctionedPurchase,
    IsSendToEis: source?.isSendToEis,
    IsSingleWinner: source?.isSingleWinner,
    IsSmallBusinessEntity: source?.isSmallBusinessEntity,
    IsSortApplicationsByPriceWithoutVat: source?.isSortApplicationsByPriceWithoutVat,
    IsTradeNeedConfirmCustomerTermsWhenOffer: source?.isTradeNeedConfirmCustomerTermsWhenOffer,
    IsUnitBidding: source?.isUnitBidding,
    ItemsCount: source?.itemsCount,
    LotAuctionId: source?.lotAuctionId,
    LotId: source?.lotId,
    LotItemsSumPrice: source?.lotItemsSumPrice,
    M4DDealSignRequired: source?.m4DDealSignRequired === null ? undefined : apiM4DDealSignRequiredEnumAdapter(source?.m4DDealSignRequired),
    MarketState: source?.marketState === null ? undefined : apiMarketDealStateEnumAdapter(source?.marketState),
    MarketStateDescription: source?.marketStateDescription,
    MaxDealPriceWithVat: source?.maxDealPriceWithVat,
    MaxDealPriceWithoutVat: source?.maxDealPriceWithoutVat,
    MeetsRequirements: source?.meetsRequirements === null ? undefined : apiMeetsRequirementsEnumAdapter(source?.meetsRequirements),
    MovingProLink: source?.movingProLink,
    NeedBlockMoney: source?.needBlockMoney,
    OfferId: source?.offerId,
    OfferTerms: source?.offerTerms === null ? undefined : apiMyTermsAltDtoAdapter(source?.offerTerms),
    OnlyOneRetradingBidAllowed: source?.onlyOneRetradingBidAllowed,
    OrderState: source?.orderState === null ? undefined : apiOrderStateEnumAdapter(source?.orderState),
    OrganizerExternalOrganizationId: source?.organizerExternalOrganizationId,
    OrganizerFullName: source?.organizerFullName,
    OrganizerGuid: source?.organizerGuid,
    OrganizerId: source?.organizerId,
    OrganizerSource: source?.organizerSource,
    Original223TradeLotState: source?.original223TradeLotState === null ? undefined : apiLotStateEnumAdapter(source?.original223TradeLotState),
    ParentContractNumber: source?.parentContractNumber,
    ParentNotTookPlaceTradeBusinessFlowType: source?.parentNotTookPlaceTradeBusinessFlowType === null ? undefined : apiTradeBusinessFlowEnumAdapter(source?.parentNotTookPlaceTradeBusinessFlowType),
    ParentNotTookPlaceTradeHosts: source?.parentNotTookPlaceTradeHosts,
    ParentNotTookPlaceTradeId: source?.parentNotTookPlaceTradeId,
    ParticipantExternalOrganizationId: source?.participantExternalOrganizationId,
    ParticipantFullName: source?.participantFullName,
    ParticipantGuid: source?.participantGuid,
    ParticipantId: source?.participantId,
    ParticipantSource: source?.participantSource,
    PictureGuids: source?.pictureGuids,
    PlanNumber: source?.planNumber,
    PlanPositionNumber: source?.planPositionNumber,
    PlanedDealSignDate: source?.planedDealSignDate,
    PossibleSelfDelivery: source?.possibleSelfDelivery,
    PossibleSendByTransportCompany: source?.possibleSendByTransportCompany,
    Price: source?.price,
    PriceCorridor: source?.priceCorridor === null ? undefined : apiPriceCorridorDtoAdapter(source?.priceCorridor),
    PriceWithVat: source?.priceWithVat,
    Products: source?.products?.map((item) => apiMarketTradeProductAltDtoAdapter(item)),
    ProhibitPostingCustomerComissionProtocol: source?.prohibitPostingCustomerComissionProtocol,
    ProtocolReadyToPublish: source?.protocolReadyToPublish,
    PublicationDate: source?.publicationDate,
    PurchaseMethodType: source?.purchaseMethodType === null ? undefined : apiPurchaseMethodTypeEnumAdapter(source?.purchaseMethodType),
    RateVat: source?.rateVat === null ? undefined : apiAvailableVatTypeEnumAdapter(source?.rateVat),
    RegulationInfo: source?.regulationInfo === null ? undefined : apiRegulationInfoDtoAdapter(source?.regulationInfo),
    RequiredSupplierRegistration: source?.requiredSupplierRegistration,
    RequirementsInfo: source?.requirementsInfo,
    RetradingBidLeftCount: source?.retradingBidLeftCount,
    RetradingEndDate: source?.retradingEndDate,
    RetradingStartDate: source?.retradingStartDate,
    RetradingType: source?.retradingType === null ? undefined : apiRetradingTypeEnumAdapter(source?.retradingType),
    RussianPurchaseAdvantageInfo: source?.russianPurchaseAdvantageInfo,
    ShowProtocol: source?.showProtocol,
    ShowProtocolDocument: source?.showProtocolDocument,
    Signer: source?.signer === null ? undefined : apiDealSignerAltDtoAdapter(source?.signer),
    Specifications: source?.specifications?.map((item) => apiTradeLotSpecificationDtoAdapter(item)),
    SupplierWithSmallBusinessRequirements: source?.supplierWithSmallBusinessRequirements,
    SupplierWithUniversalRequirements: source?.supplierWithUniversalRequirements,
    Tags: source?.tags,
    TenantId: source?.tenantId,
    TradeName: source?.tradeName,
    TradeNumber: source?.tradeNumber,
    TradeState: source?.tradeState === null ? undefined : apiTradeStateEnumAdapter(source?.tradeState),
    TradeSum: source?.tradeSum,
    TradeViewFormOptions: source?.tradeViewFormOptions === null ? undefined : apiTradeViewFormOptionsDtoAdapter(source?.tradeViewFormOptions),
    VatRate: source?.vatRate,
    VatRateDescription: source?.vatRateDescription,
    VatRateState: source?.vatRateState === null ? undefined : apiVatRateStateEnumAdapter(source?.vatRateState),
    WinnerTradeLotApplicationId: source?.winnerTradeLotApplicationId,
    WorkGroupIds: source?.workGroupIds,
    ZmoFinanceSource: source?.zmoFinanceSource === null ? undefined : apiZmoFinanceSourceEnumAdapter(source?.zmoFinanceSource),
    ZmoFinanceSourceDescription: source?.zmoFinanceSourceDescription,
    ZmoFzType: source?.zmoFzType,
    ZmoFzTypeDescription: source?.zmoFzTypeDescription,
    ZmoFzTypeHint: source?.zmoFzTypeHint,
    ZmoFzTypeName: source?.zmoFzTypeName,
  };
}
