import { TradeView } from '../../models/trade-view.interface';
import { ApiTradeViewDto } from '../../../swagger/models/api-trade-view-dto';
import { apiAdditionalRequirementDtoAdapter } from './api-additional-requirement-dto.adapter';
import { apiCustomerContactInfoAltDtoAdapter } from './api-customer-contact-info.adapter';
import { apiDealStateEnumAdapter } from '../enums/api-deal-state-enum.adapter';
import { apiDocumentDtoAdapter } from './api-document-dto.adapter';
import { apiM4DDealSignRequiredEnumAdapter } from '../enums/api-m-4-d-deal-sign-required-enum.adapter';
import { apiProductDtoAdapter } from './api-product-dto.adapter';
import { apiSourcePlatformEnumAdapter } from '../enums/api-source-platform-enum.adapter';
import { apiStateOfIncreasingForFillingApplicationEndDateAltEnumAdapter } from '../enums/api-state-of-increasing-for-filling-application-end-date.adapter';
import { apiSuppliersListReportResultDtoAdapter } from './api-suppliers-list-report-result-dto.adapter';
import { apiTradeBusinessFlowEnumAdapter } from '../enums/api-trade-business-flow-enum.adapter';
import { apiTradeGroupViewDtoAdapter } from './api-trade-group-view-dto.adapter';
import { apiTradeStateEnumAdapter } from '../enums/api-trade-state-enum.adapter';
import { apiViewApplicationsForTradeDtoAdapter } from './api-view-applications-for-trade-dto.adapter';
import { apiZmoFinanceSourceEnumAdapter } from '../enums/api-zmo-finance-source-enum.adapter';

export const apiTradeViewDtoAdapter = (source?: TradeView | null): ApiTradeViewDto => {
  return {
    ActualChildOrderId: source?.actualChildOrderId,
    ActualChildTradeId: source?.actualChildTradeId,
    AdditionalInfo: source?.additionalInfo,
    AdditionalRequirements: source?.additionalRequirements?.map((item) => apiAdditionalRequirementDtoAdapter(item)),
    ApplicationSet: source?.applicationSet === null ? undefined : apiViewApplicationsForTradeDtoAdapter(source?.applicationSet),
    AutoInvitationVendors: source?.autoInvitationVendors,
    CanBeShownOnZmo: source?.canBeShownOnZmo,
    CanCheckParticipant: source?.canCheckParticipant,
    CanDownloadApplicationsData: source?.canDownloadApplicationsData,
    CanManageApplications: source?.canManageApplications,
    CanPossibleCreateDealOutsideEShop: source?.canPossibleCreateDealOutsideEShop,
    CancellationReason: source?.cancellationReason,
    ConcludeReviewApplication: source?.concludeReviewApplication,
    ConditionsOfPayment: source?.conditionsOfPayment,
    ContactInfo: source?.contactInfo === null ? undefined : apiCustomerContactInfoAltDtoAdapter(source?.contactInfo),
    CurrentCustomerHasDealForThisTrade: source?.currentCustomerHasDealForThisTrade,
    CurrentParticipantHasDealForThisTrade: source?.currentParticipantHasDealForThisTrade,
    CurrentStageId: source?.currentStageId,
    CustomerFullName: source?.customerFullName,
    CustomerId: source?.customerId,
    CustomerInn: source?.customerInn,
    CustomerPhysAddress: source?.customerPhysAddress,
    DealExecutionDate: source?.dealExecutionDate,
    DealState: source?.dealState === null ? undefined : apiDealStateEnumAdapter(source?.dealState),
    DefaultPriceForSignDealOutSide: source?.defaultPriceForSignDealOutSide,
    DeliveryKladrRegionCode: source?.deliveryKladrRegionCode,
    DeliveryKladrRegionName: source?.deliveryKladrRegionName,
    DeliveryPlace: source?.deliveryPlace,
    DeliveryTerms: source?.deliveryTerms,
    Description: source?.description,
    EnableKtruCode: source?.enableKtruCode,
    EnableKtruSpecifications: source?.enableKtruSpecifications,
    EnableMonetizationZmo: source?.enableMonetizationZmo,
    EnablePositionCharacteristics: source?.enablePositionCharacteristics,
    ExternalContractTemplateId: source?.externalContractTemplateId,
    ExternalSourcePlatformNumber: source?.externalSourcePlatformNumber,
    ExternalSystemId: source?.externalSystemId,
    FillingApplicationEndDate: source?.fillingApplicationEndDate,
    FreeWinnerSelectionEnabled: source?.freeWinnerSelectionEnabled,
    HasDealSignedOutsideEShop: source?.hasDealSignedOutsideEShop,
    Id: source?.id,
    InitialPrice: source?.initialPrice,
    IsCustomerAcceptOnlyManualOffers: source?.isCustomerAcceptOnlyManualOffers,
    IsEisConcludeDealRequired: source?.isEisConcludeDealRequired,
    IsHideParticipantPrice: source?.isHideParticipantPrice,
    IsHideParticipantsApplications: source?.isHideParticipantsApplications,
    IsImmediate: source?.isImmediate,
    IsInitialPriceDefined: source?.isInitialPriceDefined,
    IsLapsed: source?.isLapsed,
    IsOnlySmp: source?.isOnlySmp,
    IsOrderCreationFromExternalNotTookPlaceTradeAvailable: source?.isOrderCreationFromExternalNotTookPlaceTradeAvailable,
    IsParentContractNumberNotSpecified: source?.isParentContractNumberNotSpecified,
    IsSendContractAllowed: source?.isSendContractAllowed,
    IsSendToNonPublicEis: source?.isSendToNonPublicEis,
    IsTradeForPartner: source?.isTradeForPartner,
    IsTradeNeedConfirmCustomerTermsWhenOffer: source?.isTradeNeedConfirmCustomerTermsWhenOffer,
    IsUnitBidding: source?.isUnitBidding,
    IsWaitingPeriodEnabled: source?.isWaitingPeriodEnabled,
    LastModificationDate: source?.lastModificationDate,
    LotAuctionId: source?.lotAuctionId,
    LotId: source?.lotId,
    LotItemsSumPrice: source?.lotItemsSumPrice,
    M4DDealSignRequired: source?.m4DDealSignRequired === null ? undefined : apiM4DDealSignRequiredEnumAdapter(source?.m4DDealSignRequired),
    MaxDealPrice: source?.maxDealPrice,
    OrganizerId: source?.organizerId,
    OrganizerInn: source?.organizerInn,
    OrganizerName: source?.organizerName,
    OrganizerPhysAddress: source?.organizerPhysAddress,
    OriginTradeId: source?.originTradeId,
    ParentContractNumber: source?.parentContractNumber,
    ParticipantCanCreateApplication: source?.participantCanCreateApplication,
    PaymentByBankCardEnable: source?.paymentByBankCardEnable,
    PlanedDealSignDate: source?.planedDealSignDate,
    PriceWithVat: source?.priceWithVat,
    Products: source?.products?.map((item) => apiProductDtoAdapter(item)),
    ProhibitPostingCustomerComissionProtocol: source?.prohibitPostingCustomerComissionProtocol,
    PublicationDate: source?.publicationDate,
    ReadOnly: source?.readOnly,
    RedirectOn223Url: source?.redirectOn223Url,
    RelatedOrderId: source?.relatedOrderId,
    ResultsDeliveryType: source?.resultsDeliveryType,
    RussianPurchaseAdvantageInfo: source?.russianPurchaseAdvantageInfo,
    ShowProtocol: source?.showProtocol,
    SourcePlatform: source?.sourcePlatform === null ? undefined : apiSourcePlatformEnumAdapter(source?.sourcePlatform),
    StateOfIncreasing: source?.stateOfIncreasing === null ? undefined : apiStateOfIncreasingForFillingApplicationEndDateAltEnumAdapter(source?.stateOfIncreasing),
    SupplierWithSmallBusinessRequirements: source?.supplierWithSmallBusinessRequirements,
    SupplierWithUniversalRequirements: source?.supplierWithUniversalRequirements,
    SuppliersListReportResult: source?.suppliersListReportResult === null ? undefined : apiSuppliersListReportResultDtoAdapter(source?.suppliersListReportResult),
    TenantId: source?.tenantId,
    TradeBusinessFlow: source?.tradeBusinessFlow === null ? undefined : apiTradeBusinessFlowEnumAdapter(source?.tradeBusinessFlow),
    TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz: source?.tradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz,
    TradeDocuments: source?.tradeDocuments?.map((item) => apiDocumentDtoAdapter(item)),
    TradeGroups: source?.tradeGroups?.map((item) => apiTradeGroupViewDtoAdapter(item)),
    TradeIdentificationCode: source?.tradeIdentificationCode,
    TradeName: source?.tradeName,
    TradeState: source?.tradeState === null ? undefined : apiTradeStateEnumAdapter(source?.tradeState),
    TradeWaitingTime: source?.tradeWaitingTime,
    ZmoFinanceSource: source?.zmoFinanceSource === null ? undefined : apiZmoFinanceSourceEnumAdapter(source?.zmoFinanceSource),
    ZmoFzType: source?.zmoFzType,
  };
}
