import { ApiMarketTradeViewDto } from '../../../swagger/models/api-market-trade-view-dto';
import { MarketTradeView } from '../../models/market-trade-view.interface';
import { additionalRequirementDto2Adapter } from './additional-requirement-dto-2.adapter';
import { applicationParametersAdapter } from './application-parameters.adapter';
import { applicationStateEnumAdapter } from '../enums/application-state-enum.adapter';
import { availableVatTypeEnumAdapter } from '../enums/available-vat-type-enum.adapter';
import { dealSignerAltAdapter } from './deal-signer-alt.adapter';
import { dealStateEnumAdapter } from '../enums/deal-state-enum.adapter';
import { deliveryMethodAltEnumAdapter } from '../enums/delivery-method-alt-enum.adapter';
import { dictionaryItemAltAdapter } from './dictionary-item-alt.adapter';
import { eisIntegrationDataAltAdapter } from './eis-integration-data-alt.adapter';
import { eisTradeInfoAltAdapter } from './eis-trade-info-alt.adapter';
import { federalLawLimitAltEnumAdapter } from '../enums/federal-law-limit-alt-enum.adapter';
import { lotStateEnumAdapter } from '../enums/lot-state-enum.adapter';
import { m4DDealSignRequiredEnumAdapter } from '../enums/m-4-d-deal-sign-required-enum.adapter';
import { marketDealStateEnumAdapter } from '../enums/market-deal-state-enum.adapter';
import { marketEntityTypeAltEnumAdapter } from '../enums/market-entity-type-alt-enum.adapter';
import { marketTradeDealAltAdapter } from './market-trade-deal-alt.adapter';
import { marketTradePersonAltAdapter } from './market-trade-person-alt.adapter';
import { marketTradeProductAltAdapter } from './market-trade-product-alt.adapter';
import { meetsRequirementsEnumAdapter } from '../enums/meets-requirements-enum.adapter';
import { myTermsAltAdapter } from './my-terms-alt.adapter';
import { orderStateEnumAdapter } from '../enums/order-state-enum.adapter';
import { priceCorridorAdapter } from './price-corridor.adapter';
import { purchaseMethodTypeEnumAdapter } from '../enums/purchase-method-type-enum.adapter';
import { regulationInfoAdapter } from './regulation-info.adapter';
import { retradingTypeEnumAdapter } from '../enums/retrading-type-enum.adapter';
import { shortTenantSettingAltAdapter } from './short-tenant-setting-alt.adapter';
import { tradeBusinessFlowEnumAdapter } from '../enums/trade-business-flow-enum.adapter';
import { tradeLotSpecificationAdapter } from './trade-lot-specification.adapter';
import { tradeStateEnumAdapter } from '../enums/trade-state-enum.adapter';
import { tradeViewFormOptionsAdapter } from './trade-view-form-options.adapter';
import { vatRateStateEnumAdapter } from '../enums/vat-rate-state-enum.adapter';
import { zmoFinanceSourceEnumAdapter } from '../enums/zmo-finance-source-enum.adapter';

export const marketTradeViewAdapter = (source?: ApiMarketTradeViewDto | null): MarketTradeView => {
  return {
    additionalRequirements: source?.AdditionalRequirements?.map((item) => additionalRequirementDto2Adapter(item)),
    allowApplicationReject: source?.AllowApplicationReject,
    applicationId: source?.ApplicationId,
    applicationParameters: source?.ApplicationParameters === null ? undefined : applicationParametersAdapter(source?.ApplicationParameters),
    applicationState: source?.ApplicationState === null ? undefined : applicationStateEnumAdapter(source?.ApplicationState),
    businessFlowType: source?.BusinessFlowType === null ? undefined : tradeBusinessFlowEnumAdapter(source?.BusinessFlowType),
    canSuggestPaperFormSigning: source?.CanSuggestPaperFormSigning,
    childTradeBusinessFlowType: source?.ChildTradeBusinessFlowType === null ? undefined : tradeBusinessFlowEnumAdapter(source?.ChildTradeBusinessFlowType),
    childTradeHosts: source?.ChildTradeHosts,
    childTradeId: source?.ChildTradeId,
    conditionsOfPayment: source?.ConditionsOfPayment,
    contactPerson: source?.ContactPerson === null ? undefined : marketTradePersonAltAdapter(source?.ContactPerson),
    contractAmountInfo: source?.ContractAmountInfo,
    currencyCode: source?.CurrencyCode,
    currentStageId: source?.CurrentStageId,
    customerExternalOrganizationId: source?.CustomerExternalOrganizationId,
    customerFullName: source?.CustomerFullName,
    customerGuid: source?.CustomerGuid,
    customerId: source?.CustomerId,
    customerPhysAddress: source?.CustomerPhysAddress,
    customerSource: source?.CustomerSource,
    dealBelongToCurrentOrg: source?.DealBelongToCurrentOrg,
    dealConclusionTermInfo: source?.DealConclusionTermInfo,
    dealDirectionFlow: source?.DealDirectionFlow,
    dealExecutionDate: source?.DealExecutionDate,
    dealId: source?.DealId,
    dealState: source?.DealState === null ? undefined : dealStateEnumAdapter(source?.DealState),
    deals: source?.Deals?.map((item) => marketTradeDealAltAdapter(item)),
    deliveryKladrRegionCode: source?.DeliveryKladrRegionCode,
    deliveryKladrRegionCodes: source?.DeliveryKladrRegionCodes?.map((item) => dictionaryItemAltAdapter(item)),
    deliveryKladrRegionName: source?.DeliveryKladrRegionName,
    deliveryMethod: source?.DeliveryMethod === null ? undefined : deliveryMethodAltEnumAdapter(source?.DeliveryMethod),
    deliveryTerms: source?.DeliveryTerms,
    description: source?.Description,
    displayApproveBtn: source?.DisplayApproveBtn,
    displayDealDontConcludeBtn: source?.DisplayDealDontConcludeBtn,
    eisIntegrationData: source?.EisIntegrationData === null ? undefined : eisIntegrationDataAltAdapter(source?.EisIntegrationData),
    eisTradeInfo: source?.EisTradeInfo === null ? undefined : eisTradeInfoAltAdapter(source?.EisTradeInfo),
    enableKtruSpecifications: source?.EnableKtruSpecifications,
    enableMonetizationMarket: source?.EnableMonetizationMarket,
    enablePositionCharacteristics: source?.EnablePositionCharacteristics,
    entityType: source?.EntityType === null ? undefined : marketEntityTypeAltEnumAdapter(source?.EntityType),
    externalId: source?.ExternalId,
    externalSystemId: source?.ExternalSystemId,
    federalLawLimit: source?.FederalLawLimit === null ? undefined : federalLawLimitAltEnumAdapter(source?.FederalLawLimit),
    fillingApplicationEndDate: source?.FillingApplicationEndDate,
    hasDealFile: source?.HasDealFile,
    hasManualParticipantOfferToTrade: source?.HasManualParticipantOfferToTrade,
    hasUncompletedEisOutgoingSaga: source?.HasUncompletedEisOutgoingSaga,
    hosts: source?.Hosts,
    id: source?.Id,
    initialPriceWithVat: source?.InitialPriceWithVat,
    initialPriceWithoutVat: source?.InitialPriceWithoutVat,
    initialTenantSetting: source?.InitialTenantSetting === null ? undefined : shortTenantSettingAltAdapter(source?.InitialTenantSetting),
    isApprovalRequestExists: source?.IsApprovalRequestExists,
    isAutoCreateDealAfterReviewApplications: source?.IsAutoCreateDealAfterReviewApplications,
    isAvailableSelectOnlyOneOfferForItem: source?.IsAvailableSelectOnlyOneOfferForItem,
    isBy223Fz: source?.IsBy223Fz,
    isBy44Fz: source?.IsBy44Fz,
    isContractInElectronicForm: source?.IsContractInElectronicForm,
    isCustomPrice: source?.IsCustomPrice,
    isCustomer: source?.IsCustomer,
    isCustomerAcceptByOkeiOffers: source?.IsCustomerAcceptByOkeiOffers,
    isCustomerAcceptOnlyManualOffers: source?.IsCustomerAcceptOnlyManualOffers,
    isDealSigningExpired: source?.IsDealSigningExpired,
    isEditable: source?.IsEditable,
    isEisConcludeDealRequired: source?.IsEisConcludeDealRequired,
    isEisTradeAccelerated: source?.IsEisTradeAccelerated,
    isFederalLawsEnable: source?.IsFederalLawsEnable,
    isHiddenContract: source?.IsHiddenContract,
    isImmediate: source?.IsImmediate,
    isImportPhaseout: source?.IsImportPhaseout,
    isInEisWasChanged: source?.IsInEisWasChanged,
    isInitialPriceDefined: source?.IsInitialPriceDefined,
    isInitialPriceReduction: source?.IsInitialPriceReduction,
    isLapsed: source?.IsLapsed,
    isLotPriceEnteredWithVAT: source?.IsLotPriceEnteredWithVAT,
    isLotPriceWithVat: source?.IsLotPriceWithVat,
    isModificationSentToOos: source?.IsModificationSentToOos,
    isOnlySmp: source?.IsOnlySmp,
    isOrganizer: source?.IsOrganizer,
    isParentContractNumberNotSpecified: source?.IsParentContractNumberNotSpecified,
    isPositionalVatEnable: source?.IsPositionalVatEnable,
    isPrivate: source?.IsPrivate,
    isRetradingEnabled: source?.IsRetradingEnabled,
    isRussianPurchaseObjectHasAdvantage: source?.IsRussianPurchaseObjectHasAdvantage,
    isSanctionedPurchase: source?.IsSanctionedPurchase,
    isSendToEis: source?.IsSendToEis,
    isSingleWinner: source?.IsSingleWinner,
    isSmallBusinessEntity: source?.IsSmallBusinessEntity,
    isSortApplicationsByPriceWithoutVat: source?.IsSortApplicationsByPriceWithoutVat,
    isTradeNeedConfirmCustomerTermsWhenOffer: source?.IsTradeNeedConfirmCustomerTermsWhenOffer,
    isUnitBidding: source?.IsUnitBidding,
    itemsCount: source?.ItemsCount,
    lotAuctionId: source?.LotAuctionId,
    lotId: source?.LotId,
    lotItemsSumPrice: source?.LotItemsSumPrice,
    m4DDealSignRequired: source?.M4DDealSignRequired === null ? undefined : m4DDealSignRequiredEnumAdapter(source?.M4DDealSignRequired),
    marketState: source?.MarketState === null ? undefined : marketDealStateEnumAdapter(source?.MarketState),
    marketStateDescription: source?.MarketStateDescription,
    maxDealPriceWithVat: source?.MaxDealPriceWithVat,
    maxDealPriceWithoutVat: source?.MaxDealPriceWithoutVat,
    meetsRequirements: source?.MeetsRequirements === null ? undefined : meetsRequirementsEnumAdapter(source?.MeetsRequirements),
    movingProLink: source?.MovingProLink,
    needBlockMoney: source?.NeedBlockMoney,
    offerId: source?.OfferId,
    offerTerms: source?.OfferTerms === null ? undefined : myTermsAltAdapter(source?.OfferTerms),
    onlyOneRetradingBidAllowed: source?.OnlyOneRetradingBidAllowed,
    orderState: source?.OrderState === null ? undefined : orderStateEnumAdapter(source?.OrderState),
    organizerExternalOrganizationId: source?.OrganizerExternalOrganizationId,
    organizerFullName: source?.OrganizerFullName,
    organizerGuid: source?.OrganizerGuid,
    organizerId: source?.OrganizerId,
    organizerSource: source?.OrganizerSource,
    original223TradeLotState: source?.Original223TradeLotState === null ? undefined : lotStateEnumAdapter(source?.Original223TradeLotState),
    parentContractNumber: source?.ParentContractNumber,
    parentNotTookPlaceTradeBusinessFlowType: source?.ParentNotTookPlaceTradeBusinessFlowType === null ? undefined : tradeBusinessFlowEnumAdapter(source?.ParentNotTookPlaceTradeBusinessFlowType),
    parentNotTookPlaceTradeHosts: source?.ParentNotTookPlaceTradeHosts,
    parentNotTookPlaceTradeId: source?.ParentNotTookPlaceTradeId,
    participantExternalOrganizationId: source?.ParticipantExternalOrganizationId,
    participantFullName: source?.ParticipantFullName,
    participantGuid: source?.ParticipantGuid,
    participantId: source?.ParticipantId,
    participantSource: source?.ParticipantSource,
    pictureGuids: source?.PictureGuids,
    planNumber: source?.PlanNumber,
    planPositionNumber: source?.PlanPositionNumber,
    planedDealSignDate: source?.PlanedDealSignDate,
    possibleSelfDelivery: source?.PossibleSelfDelivery,
    possibleSendByTransportCompany: source?.PossibleSendByTransportCompany,
    price: source?.Price,
    priceCorridor: source?.PriceCorridor === null ? undefined : priceCorridorAdapter(source?.PriceCorridor),
    priceWithVat: source?.PriceWithVat,
    products: source?.Products?.map((item) => marketTradeProductAltAdapter(item)),
    prohibitPostingCustomerComissionProtocol: source?.ProhibitPostingCustomerComissionProtocol,
    protocolReadyToPublish: source?.ProtocolReadyToPublish,
    publicationDate: source?.PublicationDate,
    purchaseMethodType: source?.PurchaseMethodType === null ? undefined : purchaseMethodTypeEnumAdapter(source?.PurchaseMethodType),
    rateVat: source?.RateVat === null ? undefined : availableVatTypeEnumAdapter(source?.RateVat),
    regulationInfo: source?.RegulationInfo === null ? undefined : regulationInfoAdapter(source?.RegulationInfo),
    requiredSupplierRegistration: source?.RequiredSupplierRegistration,
    requirementsInfo: source?.RequirementsInfo,
    retradingBidLeftCount: source?.RetradingBidLeftCount,
    retradingEndDate: source?.RetradingEndDate,
    retradingStartDate: source?.RetradingStartDate,
    retradingType: source?.RetradingType === null ? undefined : retradingTypeEnumAdapter(source?.RetradingType),
    russianPurchaseAdvantageInfo: source?.RussianPurchaseAdvantageInfo,
    showProtocol: source?.ShowProtocol,
    showProtocolDocument: source?.ShowProtocolDocument,
    signer: source?.Signer === null ? undefined : dealSignerAltAdapter(source?.Signer),
    specifications: source?.Specifications?.map((item) => tradeLotSpecificationAdapter(item)),
    supplierWithSmallBusinessRequirements: source?.SupplierWithSmallBusinessRequirements,
    supplierWithUniversalRequirements: source?.SupplierWithUniversalRequirements,
    tags: source?.Tags,
    tenantId: source?.TenantId,
    tradeName: source?.TradeName,
    tradeNumber: source?.TradeNumber,
    tradeState: source?.TradeState === null ? undefined : tradeStateEnumAdapter(source?.TradeState),
    tradeSum: source?.TradeSum,
    tradeViewFormOptions: source?.TradeViewFormOptions === null ? undefined : tradeViewFormOptionsAdapter(source?.TradeViewFormOptions),
    vatRate: source?.VatRate,
    vatRateDescription: source?.VatRateDescription,
    vatRateState: source?.VatRateState === null ? undefined : vatRateStateEnumAdapter(source?.VatRateState),
    winnerTradeLotApplicationId: source?.WinnerTradeLotApplicationId,
    workGroupIds: source?.WorkGroupIds,
    zmoFinanceSource: source?.ZmoFinanceSource === null ? undefined : zmoFinanceSourceEnumAdapter(source?.ZmoFinanceSource),
    zmoFinanceSourceDescription: source?.ZmoFinanceSourceDescription,
    zmoFzType: source?.ZmoFzType,
    zmoFzTypeDescription: source?.ZmoFzTypeDescription,
    zmoFzTypeHint: source?.ZmoFzTypeHint,
    zmoFzTypeName: source?.ZmoFzTypeName,
  };
}
