import { ApiTradeViewDto } from '../../../swagger/models/api-trade-view-dto';
import { TradeView } from '../../models/trade-view.interface';
import { additionalRequirementAdapter } from './additional-requirement.adapter';
import { customerContactInfoAltAdapter } from './customer-contact-info-alt.adapter';
import { dealStateEnumAdapter } from '../enums/deal-state-enum.adapter';
import { documentAdapter } from './document.adapter';
import { m4DDealSignRequiredEnumAdapter } from '../enums/m-4-d-deal-sign-required-enum.adapter';
import { productAdapter } from './product.adapter';
import { sourcePlatformEnumAdapter } from '../enums/source-platform-enum.adapter';
import { stateOfIncreasingForFillingApplicationEndDateAltEnumAdapter } from '../enums/state-of-increasing-for-filling-application-end-date-alt-enum.adapter';
import { suppliersListReportResultAdapter } from './suppliers-list-report-result.adapter';
import { tradeBusinessFlowEnumAdapter } from '../enums/trade-business-flow-enum.adapter';
import { tradeGroupViewAdapter } from './trade-group-view.adapter';
import { tradeStateEnumAdapter } from '../enums/trade-state-enum.adapter';
import { viewApplicationsForTradeAdapter } from './view-applications-for-trade.adapter';
import { zmoFinanceSourceEnumAdapter } from '../enums/zmo-finance-source-enum.adapter';

export const tradeViewAdapter = (source?: ApiTradeViewDto | null): TradeView => {
  return {
    actualChildOrderId: source?.ActualChildOrderId,
    actualChildTradeId: source?.ActualChildTradeId,
    additionalInfo: source?.AdditionalInfo,
    additionalRequirements: source?.AdditionalRequirements?.map((item) => additionalRequirementAdapter(item)),
    applicationSet: source?.ApplicationSet === null ? undefined : viewApplicationsForTradeAdapter(source?.ApplicationSet),
    autoInvitationVendors: source?.AutoInvitationVendors,
    canBeShownOnZmo: source?.CanBeShownOnZmo,
    canCheckParticipant: source?.CanCheckParticipant,
    canDownloadApplicationsData: source?.CanDownloadApplicationsData,
    canManageApplications: source?.CanManageApplications,
    canPossibleCreateDealOutsideEShop: source?.CanPossibleCreateDealOutsideEShop,
    cancellationReason: source?.CancellationReason,
    concludeReviewApplication: source?.ConcludeReviewApplication,
    conditionsOfPayment: source?.ConditionsOfPayment,
    contactInfo: source?.ContactInfo === null ? undefined : customerContactInfoAltAdapter(source?.ContactInfo),
    currentCustomerHasDealForThisTrade: source?.CurrentCustomerHasDealForThisTrade,
    currentParticipantHasDealForThisTrade: source?.CurrentParticipantHasDealForThisTrade,
    currentStageId: source?.CurrentStageId,
    customerFullName: source?.CustomerFullName,
    customerId: source?.CustomerId,
    customerInn: source?.CustomerInn,
    customerPhysAddress: source?.CustomerPhysAddress,
    dealExecutionDate: source?.DealExecutionDate,
    dealState: source?.DealState === null ? undefined : dealStateEnumAdapter(source?.DealState),
    defaultPriceForSignDealOutSide: source?.DefaultPriceForSignDealOutSide,
    deliveryKladrRegionCode: source?.DeliveryKladrRegionCode,
    deliveryKladrRegionName: source?.DeliveryKladrRegionName,
    deliveryPlace: source?.DeliveryPlace,
    deliveryTerms: source?.DeliveryTerms,
    description: source?.Description,
    enableKtruCode: source?.EnableKtruCode,
    enableKtruSpecifications: source?.EnableKtruSpecifications,
    enableMonetizationZmo: source?.EnableMonetizationZmo,
    enablePositionCharacteristics: source?.EnablePositionCharacteristics,
    externalContractTemplateId: source?.ExternalContractTemplateId,
    externalSourcePlatformNumber: source?.ExternalSourcePlatformNumber,
    externalSystemId: source?.ExternalSystemId,
    fillingApplicationEndDate: source?.FillingApplicationEndDate,
    freeWinnerSelectionEnabled: source?.FreeWinnerSelectionEnabled,
    hasDealSignedOutsideEShop: source?.HasDealSignedOutsideEShop,
    id: source?.Id,
    initialPrice: source?.InitialPrice,
    isCustomerAcceptOnlyManualOffers: source?.IsCustomerAcceptOnlyManualOffers,
    isEisConcludeDealRequired: source?.IsEisConcludeDealRequired,
    isHideParticipantPrice: source?.IsHideParticipantPrice,
    isHideParticipantsApplications: source?.IsHideParticipantsApplications,
    isImmediate: source?.IsImmediate,
    isInitialPriceDefined: source?.IsInitialPriceDefined,
    isLapsed: source?.IsLapsed,
    isOnlySmp: source?.IsOnlySmp,
    isOrderCreationFromExternalNotTookPlaceTradeAvailable: source?.IsOrderCreationFromExternalNotTookPlaceTradeAvailable,
    isParentContractNumberNotSpecified: source?.IsParentContractNumberNotSpecified,
    isSendContractAllowed: source?.IsSendContractAllowed,
    isSendToNonPublicEis: source?.IsSendToNonPublicEis,
    isTradeForPartner: source?.IsTradeForPartner,
    isTradeNeedConfirmCustomerTermsWhenOffer: source?.IsTradeNeedConfirmCustomerTermsWhenOffer,
    isUnitBidding: source?.IsUnitBidding,
    isWaitingPeriodEnabled: source?.IsWaitingPeriodEnabled,
    lastModificationDate: source?.LastModificationDate,
    lotAuctionId: source?.LotAuctionId,
    lotId: source?.LotId,
    lotItemsSumPrice: source?.LotItemsSumPrice,
    m4DDealSignRequired: source?.M4DDealSignRequired === null ? undefined : m4DDealSignRequiredEnumAdapter(source?.M4DDealSignRequired),
    maxDealPrice: source?.MaxDealPrice,
    organizerId: source?.OrganizerId,
    organizerInn: source?.OrganizerInn,
    organizerName: source?.OrganizerName,
    organizerPhysAddress: source?.OrganizerPhysAddress,
    originTradeId: source?.OriginTradeId,
    parentContractNumber: source?.ParentContractNumber,
    participantCanCreateApplication: source?.ParticipantCanCreateApplication,
    paymentByBankCardEnable: source?.PaymentByBankCardEnable,
    planedDealSignDate: source?.PlanedDealSignDate,
    priceWithVat: source?.PriceWithVat,
    products: source?.Products?.map((item) => productAdapter(item)),
    prohibitPostingCustomerComissionProtocol: source?.ProhibitPostingCustomerComissionProtocol,
    publicationDate: source?.PublicationDate,
    readOnly: source?.ReadOnly,
    redirectOn223Url: source?.RedirectOn223Url,
    relatedOrderId: source?.RelatedOrderId,
    resultsDeliveryType: source?.ResultsDeliveryType,
    russianPurchaseAdvantageInfo: source?.RussianPurchaseAdvantageInfo,
    showProtocol: source?.ShowProtocol,
    sourcePlatform: source?.SourcePlatform === null ? undefined : sourcePlatformEnumAdapter(source?.SourcePlatform),
    stateOfIncreasing: source?.StateOfIncreasing === null ? undefined : stateOfIncreasingForFillingApplicationEndDateAltEnumAdapter(source?.StateOfIncreasing),
    supplierWithSmallBusinessRequirements: source?.SupplierWithSmallBusinessRequirements,
    supplierWithUniversalRequirements: source?.SupplierWithUniversalRequirements,
    suppliersListReportResult: source?.SuppliersListReportResult === null ? undefined : suppliersListReportResultAdapter(source?.SuppliersListReportResult),
    tenantId: source?.TenantId,
    tradeBusinessFlow: source?.TradeBusinessFlow === null ? undefined : tradeBusinessFlowEnumAdapter(source?.TradeBusinessFlow),
    tradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz: source?.TradeComesInFillingApplicationStateIfAllApplicationsAreNotSatisfyTz,
    tradeDocuments: source?.TradeDocuments?.map((item) => documentAdapter(item)),
    tradeGroups: source?.TradeGroups?.map((item) => tradeGroupViewAdapter(item)),
    tradeIdentificationCode: source?.TradeIdentificationCode,
    tradeName: source?.TradeName,
    tradeState: source?.TradeState === null ? undefined : tradeStateEnumAdapter(source?.TradeState),
    tradeWaitingTime: source?.TradeWaitingTime,
    zmoFinanceSource: source?.ZmoFinanceSource === null ? undefined : zmoFinanceSourceEnumAdapter(source?.ZmoFinanceSource),
    zmoFzType: source?.ZmoFzType,
  };
}
